// ==UserScript==
// @name           TexAgs GM - Forward and Back Buttons
// @namespace      Texags
// @description    Adds forward and back buttons to multi-page topics
// @include        http://www.texags.com/main/forum.reply.*
// @include        http://texags.com/main/forum.reply.*
// ==/UserScript==


function getElementsByClass(searchClass,node,tag) {
	var classElements = new Array();
	if ( node == null )
		node = document;
	if ( tag == null )
		tag = '*';
	var els = node.getElementsByTagName(tag);
	var pattern = new RegExp("(^|\\s)"+searchClass+"(\\s|$)");
	for (i = 0, j = 0; i < els.length; i++) {
		if ( pattern.test(els[i].className) ) {
			classElements[j] = els[i];
			j++;
		}
	}
	return classElements;
}

var pageNumber, lastPage, testPageNumbers = /Page:/, findPageNumber = /\s(\d+)\s/;
var pageNumbers = getElementsByClass("mediumboxtitle", null, "div");
for(i=0;i<pageNumbers.length;i++) 
	if (testPageNumbers.test(pageNumbers[i].innerHTML)) {
		pageNumbers[i].innerHTML.match(findPageNumber);
		pageNumber = RegExp.$1;
		lastPage = (pageNumbers[i].childNodes.length+1)/2;
		if (pageNumber < lastPage) {
			var nextPage = document.createElement('a');
			nextPage.href = pageNumbers[i].childNodes[pageNumber*2-1].href;
			pageNumbers[i].insertBefore(nextPage, pageNumbers[i].lastChild.nextSibling);
			var nextArrow = document.createElement('img');
			nextArrow.src = 'data:image/gif;base64,R0lGODlhDAAMAIcAAAAAAGZmZsvLy93d3e7u7v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAMAAAYALAAAAAAMAAwA'+
				'AAhDAA0IGEiwoMACCBMqHFiAgMOHDgcwhBjgoUQBDR8GqEjgYsONICt6JBByY8eJGjmO1GgRJcSI'+
				'DAfInDlTgMCCOA0EBAA7';
			nextPage.insertBefore(nextArrow, nextPage.firstChild);
		}
		if (pageNumber > 1) {
			var prevPage = document.createElement('a');
			prevPage.href = pageNumbers[i].childNodes[pageNumber*2-3].href;
			pageNumbers[i].insertBefore(prevPage, pageNumbers[i].firstChild);
			var prevArrow = document.createElement('img');
			prevArrow.src = 'data:image/gif;base64,R0lGODlhDAAMAIcAAAAAAGZmZsvLy93d3e7u7v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'+
				'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAMAAAYALAAAAAAMAAwA'+
				'AAhCAA0IGEiwoMACCBMqHFiAgMOHDgcwfBgAokQBDQkEqPjwYsONICt61BhS5ESSFk9qTIkRIssC'+
				'A2LKlClAYMGbBgICADs=';
			prevArrow.style.paddingRight = 3;
			prevPage.insertBefore(prevArrow, prevPage.firstChild);
		}
	}
