// Generated by CoffeeScript 1.3.3

// ==UserScript==
// @name        eRepublik Battle
// @namespace   Zifc
// @include     http://www.erepublik.com/*/military/battlefield/*
// @require     http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
// @version     0.6
// @license     http://unlicense.org/
// ==/UserScript==
;

var $diffs, $dominations, battleId, division, i, lastDominations, oldAjax, updateTime, _i, _ref;

GM_addStyle('.console_holder .campaign_details .entry .cz3 span {\n  width: 38px;\n}\n\n.console_holder .campaign_details .entry .cz3.domi_left .pdomi_left {\n  right: 80px;\n}\n\n.console_holder .campaign_details .entry .cz3.domi_right .pdomi_right {\n  left: 80px;\n}\n\n.console_holder h3 {\n  text-align: center;\n  min-width: 70px;\n}\n\n.pdomi_left em,\n.pdomi_right em {\n  display: none;\n}\n\n.eb-diff {\n  color: white;\n  font-size: 11px;\n  position: absolute;\n  right: 85px;\n  top: 5px;\n  color: #4397d3;\n}\n\n.eb-diff-negative {\n  color: #f95555;\n  left: 85px;\n}');

$('.heading .cz3').text('%');

$dominations = {};

$diffs = {};

for (i = _i = 1; _i <= 4; i = ++_i) {
  $dominations[i] = $(".div" + i + " .cz3 span");
  $diffs[i] = $('<b/>', {
    "class": 'eb-diff'
  }).appendTo($(".div" + i + " .cz3"));
}

updateTime = setInterval(function() {
  var time;
  time = $('#battle_countdown').text();
  if (time) {
    return $('#qonsole h3').text(time);
  } else {
    return clearInterval(updateTime);
  }
}, 1000);

lastDominations = false;

oldAjax = unsafeWindow.jQuery.ajax;

unsafeWindow.jQuery.ajax = function() {
  var oldSuccess, url;
  url = arguments[0].url;
  if (url.match(/battle-stats/) || url.match(/battle-status/)) {
    oldSuccess = arguments[0].success;
    arguments[0].success = function(data) {
      var diff, domination, dominations, _j;
      dominations = $.extend({}, data.division.domination);
      for (i = _j = 1; _j <= 4; i = ++_j) {
        if (unsafeWindow.SERVER_DATA.mustInvert) {
          dominations[i] = 100 - dominations[i];
        }
        domination = dominations[i];
        if (domination !== 100) {
          domination = parseFloat(domination).toFixed(2);
        }
        $dominations[i].text(domination);
        if (lastDominations) {
          diff = domination - lastDominations[i];
          diff = parseFloat(diff).toFixed(2);
          if (parseFloat(diff) === 0) {
            diff = '';
          } else if (diff < 0) {
            diff = diff.replace('-', '+');
            $diffs[i].addClass('eb-diff-negative');
          } else {
            diff = '+' + diff;
            $diffs[i].removeClass('eb-diff-negative');
          }
          $diffs[i].text(diff);
        }
      }
      if (oldSuccess) {
        oldSuccess.apply(this, arguments);
      }
      return lastDominations = dominations;
    };
  }
  return oldAjax.apply(this, arguments);
};

setTimeout(function() {
  return unsafeWindow.openConsole();
}, 1000);

_ref = unsafeWindow.SERVER_DATA, battleId = _ref.battleId, division = _ref.division;

unsafeWindow.jQuery.getJSON("/en/military/battle-stats/" + battleId + "/" + division);