// ==UserScript==
// @name          StackOverflow layout fixes for Firefox in Zoom Text Only mode
// @description   Fix broken layout on Stackoverflow/Stackexchange in zoom-text-only mode with high zoom levels.
// @version       0.1.0.20130528
// @namespace     http://jakub-g.github.io/
// @author        http://jakub-g.github.io/
// @downloadURL   https://raw.github.com/jakub-g/greasemonkey-userscripts/master/stackoverflow/fx-zoom-text-only-fixes.user.js
// @homepage      http://userstyles.org/styles/88234
// @grant         GM_addStyle
// @run-at        document-start
// ==/UserScript==

/*
 * Generated by Userstyles.org, with metadata manual tweaks.
 * If you use Stylish and prefer a pure CSS stylesheet, grab http://userstyles.org/styles/88234 instead
 */

(function() {
var css = "";
if (false || (location.href.replace(location.hash,'') == "http://stackoverflow.com/") || (location.href.replace(location.hash,'') == "http://superuser.com/") || (location.href.replace(location.hash,'') == "http://serverfault.com/") || (location.href.replace(location.hash,'') == "http://meta.stackoverflow.com/") || (location.href.replace(location.hash,'') == "http://meta.superuser.com/") || (location.href.replace(location.hash,'') == "http://meta.serverfault.com/"))
	css += "#question-mini-list\n    \n    {clear:both;}";
if (false || (document.location.href.indexOf("http://stackoverflow.com/users/") == 0) || (document.location.href.indexOf("http://superuser.com/users/") == 0) || (document.location.href.indexOf("http://serverfault.com/users/") == 0) || (document.location.href.indexOf("http://meta.stackoverflow.com/users/") == 0) || (document.location.href.indexOf("http://meta.superuser.com/users/") == 0) || (document.location.href.indexOf("http://meta.serverfault.com/users/") == 0) || (new RegExp("^http://\\w+.stackexchange.com/users/$")).test(document.location.href))
	css += ".user-header-left,\n    .user-panel > .user-panel-content > table\n    \n    {clear:both;}";
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		var node = document.createElement("style");
		node.type = "text/css";
		node.appendChild(document.createTextNode(css));
		heads[0].appendChild(node);
	}
}
})();
