// ==UserScript==

// @name           TFA.Index

// @namespace      Travian Ally

// @include        http://www.travian.hk/index.php

// @include        http://www.travian.hk/

// @include        http://hsbc.a.forumable.net/tc/index.php
// @include        http://hsbc.a.forumable.net/tc/
// ==/UserScript==
document.writeln("<html><head><meta http-equiv=\"Content-Language\" content=\"zh-tw\"><meta http-equiv=\"Content-Type\" content=\"text\/html; charset=big5\"><title>TravianAllyForce.Index<\/title><\/head><body bgcolor=\"#FFFFFF\">");
document.writeln("<div style=\"border:1px dashed #C0C0C0; position: absolute; width: 200px; height: 230px; z-index: 3; left: 575px; top: 274px\" id=\"layer10\">	<div align=\"center\">		<table border=\"0\" width=\"95%\" id=\"table19\">			<tr>				<td><b>");
document.writeln("	<font color=\"#82D61F\" size=\"2\">其他建議輔助工具<\/font><\/b><\/td>			<\/tr>			<tr>				<td>				<a href=\"http:\/\/userscripts.org\/scripts\/source\/15943.user.js\">				<span style=\"text-decoration: none\"><font color=\"#000000\">				．TravianBeyond<\/font><\/span><\/a><font size=\"2\">(輔助介面)<\/font><br>				<a href=\"http:\/\/userscripts.org\/scripts\/source\/13872.user.js\">				<span style=\"text-decoration: none\"><font color=\"#000000\">				．Attack builder<\/font><\/span><\/a><font size=\"2\">(多波攻擊)<br>				<\/font>				<a href=\"http:\/\/userscripts.org\/scripts\/search?q=travian\">				<span style=\"text-decoration: none\"><font color=\"#000000\">．<\/font><font color=\"#000000\" size=\"2\">Other...<\/font><\/span><\/a><\/td>			<\/tr>		<\/table>	<\/div><\/div><div style=\"border:1px dashed #C0C0C0; position: absolute; width: 200; height: 86px; z-index: 4; left: 575px; top: 170px\" id=\"layer9\">	<div align=\"center\">		<table border=\"0\" width=\"102%\" id=\"table12\" bordercolor=\"#C0C0C0\" height=\"67\">			<tr>				<td height=\"59\">				<table border=\"0\" width=\"100%\" id=\"table13\" bordercolor=\"#C0C0C0\" height=\"100%\">					<tr>						<td>						");
document.writeln("	<font size=\"2\">						<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/t2\/spieler.gif\" width=\"160\" height=\"15\"><br>");
document.writeln("<IFRAME SRC=\"http:\/\/now-visitor4.ziyu.net\/c.php?kogptn\/default\/10\/ffffff\/000000\/%BA%DF%C0%FE%B4%E1%B2%C8%A1%A1\/+\/\" WIDTH=150 HEIGHT=15 SCROLLING=NO FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 BORDER=0 allowtransparency=true target=\"_blank\">[PR]<A href=\"http:\/\/www.ziyu.net\/\">&#12502;&#12525;&#12464;&#12497;&#12540;&#12484;<\/A><IMG SRC=\"http:\/\/now-visitor4.ziyu.net\/nojs_cnt.php?kogptn\/default\/\" border=0 alt=\"\"><\/IFRAME><br>						");
document.writeln("	<iframe name=\"I2\" src=\"http:\/\/hsbc.a.forumable.net\/tc\/forumdisplay.php?fid=64\" scrolling=\"no\" border=\"0\" frameborder=\"0\" width=\"149\" height=\"19\">						您的瀏覽器不支援內置框架或目前的設定為不顯示內置框架。<\/iframe>");
document.writeln("<br>");
document.writeln("		訪問人數　<script type=\"text\/javascript\">");
document.writeln("sc_project=3728484; ");
document.writeln("sc_invisible=0; ");
document.writeln("sc_partition=45; ");
document.writeln("sc_security=\"29226680\"; ");
document.writeln("sc_text=1; ");
document.writeln("<\/script><script type=\"text\/javascript\" src=\"http:\/\/www.statcounter.com\/counter\/counter_xhtml.js\"><\/script>　　<noscript><div class=\"statcounter\"><a href=\"http:\/\/www.statcounter.com\/\" target=\"_blank\"><img class=\"statcounter\" src=\"http:\/\/c46.statcounter.com\/3728484\/0\/29226680\/0\/\" alt=\"web site hit counter\" ><\/a><\/div><\/noscript><\/font><\/td>					<\/tr>				<\/table>				<\/td>			<\/tr>		<\/table>	<\/div><\/div><div style=\"border:0px dashed #C0C0C0; position: absolute; width: 384px; height: 45px; z-index: 5; left: 175px; top: 170px\" id=\"layer8\">	<b>");
document.writeln("	<font color=\"#82D61F\" face=\"Arial\" size=\"2\">What is TravianAllyForce?<\/font><\/b><font size=\"2\"><br>	TravianAllyForce 是一個以瀏覽器為本的聯盟輔助器，在TravianAllyForce之中，每一名聯盟的盟友都可以得到全面的支援...	<\/font><b><font size=\"2\" color=\"#82D61F\">&raquo;<\/font><span class=\"f9 c2 b\"><font size=\"2\" color=\"#FF9933\">進入系統教學<\/font><\/span><\/b><\/div>	<div style=\"position: absolute; width: 100px; height: 262px; z-index: 6; left: 175px; top: 241px\" id=\"layer1\">	<div align=\"center\">				<table border=\"2\" width=\"102%\" id=\"table1\" bordercolor=\"#C0C0C0\" height=\"264\">			<tr>				<td>				<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/t2\/spielwelt.gif\" width=\"200\" height=\"15\"><br>				<a href=\"http:\/\/hsbc.a.forumable.net\/tc\/forumdisplay.php?fid=2\">				<img border=\"0\" src=\"http:\/\/i238.photobucket.com\/albums\/ff129\/kogptn\/LOGIN.png\" width=\"361\" height=\"64\"><\/a><p>			<a href=\"http:\/\/s1.travian.hk\/login.php\">				<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/welten\/hk1_g.jpg\" width=\"175\" height=\"46\"><\/a><a href=\"http:\/\/s2.travian.hk\/login.php\"><img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/welten\/hk2_g.jpg\" width=\"175\" height=\"46\"><\/a><br>				<a href=\"http:\/\/s3.travian.hk\/login.php\">				<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/welten\/hk3_g.jpg\" width=\"175\" height=\"46\"><\/a><a href=\"http:\/\/s4.travian.hk\/login.php\"><img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/welten\/hk4_g.jpg\" width=\"175\" height=\"46\"><\/a><br>				<a href=\"http:\/\/s5.travian.hk\/login.php\">				<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/welten\/hk5_g.jpg\" width=\"175\" height=\"46\"><\/a><a href=\"http:\/\/speed.travian.hk\/login.php\"><img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/welten\/hkx_g.jpg\" width=\"175\" height=\"46\"><\/a><\/td>			<\/tr>		<\/table>	<\/div><\/div><div style=\"position: absolute; width: 180px; height: 14px; z-index: 7; left: 223px; top: 100px\" id=\"layer2\" align=\"center\">	<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/t1\/welcome.gif\" width=\"468\" height=\"60\"><\/div>	");
document.writeln("<div style=\"position: absolute; width: 170px; height: 100%; z-index: 8; top: -20; right: 20; border-left: 1px dashed #C0C0C0\" id=\"layer7\">	<div align=\"center\">		");
document.writeln("	<table border=\"0\" width=\"100%\" id=\"table6\" bordercolor=\"#C0C0C0\" height=\"100%\">			<tr>				");
document.writeln("		<td>				<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/t2\/newsbox1.gif\" width=\"160\" height=\"15\"><div align=\"left\">						");
document.writeln("			<div align=\"center\">");
document.writeln("				<table border=\"1\" style=\"border-collapse: collapse; border: 1px dashed #C0C0C0\" width=\"75%\" id=\"table20\" bordercolor=\"#C0C0C0\">						<tr>							<td><b><font size=\"2\" color=\"#82D61F\">&raquo;<\/font><\/b><font size=\"2\">24\/5 							");
document.writeln("新增玩家統計<\/font><br>");
document.writeln("<b><font size=\"2\" color=\"#82D61F\">&raquo;<\/font><\/b><font size=\"2\" color=\"#0000FF\">23\/5 							首頁更新<\/font><\/td>						<\/tr>					<\/table>					");
document.writeln("			<\/div>");
document.writeln("			<p>　<\/div>					<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/t2\/newsbox2.gif\" width=\"160\" height=\"15\"><div align=\"left\">							");
document.writeln("			<div align=\"center\">");
document.writeln("				<table border=\"1\" style=\"border-collapse: collapse; border: 1px dashed #C0C0C0\" width=\"75%\" id=\"table21\" bordercolor=\"#C0C0C0\">						<tr>							<td>　<\/td>						<\/tr>					<\/table>						");
document.writeln("			<\/div>");
document.writeln("			<p>　<\/div>					<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/t2\/newsbox3.gif\" width=\"160\" height=\"15\"><div align=\"center\">							");
document.writeln("			<table border=\"1\" style=\"border-collapse: collapse; border: 1px dashed #C0C0C0\" width=\"75%\" id=\"table22\" bordercolor=\"#C0C0C0\" height=\"15\">						<tr>							");
document.writeln("				<td align=\"center\">");
document.writeln("<script type=\"text\/javascript\" src=\"http:\/\/gostats.cn\/js\/counter.js\"><\/script>");
document.writeln("<script type=\"text\/javascript\">_gos=\'c4.gostats.cn\';_goa=315404;");
document.writeln("_got=3;_goi=97;_goz=0;_gol=\'統計表\';_GoStatsRun();<\/script>");
document.writeln("<noscript><a target=\"_blank\" title=\"免&#36153;&#35745;&#25968;器申&#35831;\" ");
document.writeln("href=\"http:\/\/gostats.cn\"><img alt=\"免&#36153;&#35745;&#25968;器申&#35831;\" ");
document.writeln("src=\"http:\/\/c4.gostats.cn\/bin\/count\/a_315404\/t_3\/i_97\/counter.png\" ");
document.writeln("style=\"border-width:0\" \/><\/a><\/noscript>");
document.writeln("<\/td>						<\/tr>					<\/table>				<\/div>				<\/td>			<\/tr>			<\/table>	<\/div><\/div>	<div style=\"position: absolute; width: 150px; height: 100%; z-index: 9; left: 0; top: -20; border-right: 1px dashed #C0C0C0\" id=\"layer4\">	<div align=\"center\">		<table border=\"0\" width=\"100%\" id=\"table2\" bordercolor=\"#C0C0C0\">			<tr>				<td height=\"100\">　<\/td>			<\/tr>			<tr>				<td>				<table border=\"0\" width=\"100%\" id=\"table3\" bordercolor=\"#C0C0C0\">					<tr>						<td>						<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/hk\/travian0.gif\" width=\"116\" height=\"60\"><\/td>					<\/tr>				<\/table>				<\/td>			<\/tr>			<tr>				<td>	<font size=\"2\">．在TravianAllyForce內<br>&nbsp;&nbsp;&nbsp; ．聯合行動<br>&nbsp;&nbsp;&nbsp; ．聯盟幹事<br>				　．行政制度<br>&nbsp;&nbsp;&nbsp; ．認可聯盟<br>				　．統一外交<br>&nbsp;&nbsp;&nbsp; ．建築快速連結<br>&nbsp;&nbsp;&nbsp; ．TB市場按鈕<br>&nbsp;&nbsp;&nbsp; ．TB軍事按鈕<br>&nbsp;&nbsp;&nbsp; ．世界地圖<br>&nbsp;&nbsp;&nbsp; ．全系兵檢<\/font><p>	<font size=\"2\">．對外支援<br>				<b><font color=\"#82D61F\">&nbsp;&nbsp;&nbsp; ．FireFox<br>&nbsp;&nbsp;&nbsp; ．GreaseMonkey<br>&nbsp;&nbsp;&nbsp; ．Opera<\/font><br>				<font color=\"#FF0000\">　．Internet Explorer<\/font><\/b><\/font><font color=\"#C0C0C0\" size=\"2\"><br>");
document.writeln("	---------------------------------<br>");
document.writeln("	<\/font><font size=\"2\">&nbsp;&nbsp;&nbsp;				<a href=\"http:\/\/www.travian.hk\/index.php\"><font color=\"#000000\">				<span style=\"text-decoration: none\">．主頁<\/span><\/font><\/a><br>&nbsp;&nbsp;&nbsp; ．系統指南<br>&nbsp;&nbsp;&nbsp; ．系統簡介<br>&nbsp;&nbsp;&nbsp; <a href=\"http:\/\/www.travian.hk\/anleitung.php\">				<font color=\"#000000\"><span style=\"text-decoration: none\">．遊戲指南<\/span><\/font><\/a><br>&nbsp;&nbsp;&nbsp; <a href=\"http:\/\/www.travian.hk\/tutorial.php\">				<font color=\"#000000\"><span style=\"text-decoration: none\">．遊戲簡介<\/span><\/font><\/a><br>&nbsp;&nbsp;&nbsp; <a href=\"http:\/\/forum.travian.hk\/\"><font color=\"#000000\">				<span style=\"text-decoration: none\">．遊戲論壇<\/span><\/font><\/a><\/font><\/td>			<\/tr>			<\/table>	<\/div><\/div><div style=\"position: absolute; width: 100%; height: 100px; z-index: 10; left: 0; top: 0\" id=\"layer6\">	<img border=\"0\" src=\"http:\/\/www.travian.hk\/img\/un\/m.gif\" width=\"100%\" height=\"100\"><\/div><div style=\"position: absolute; width: 100%; height: 100%; z-index: 2; left: 0; top: 0; background-color: #FFFFFF\" id=\"layer11\"><\/div><\/body><\/html><noscript><comment><XML>\")\")")