// Generated by CoffeeScript 1.7.1
// ==UserScript==
// @name          Virtuous Juick Captain Unity
// @namespace     http://dluciv.name/
// @description   Juick automatically like on ~1/2 posts you see (Virtuous Captain Unity / Добрый капитан Единица)
// @author        dluciv
// @license       WTFPLv2 (http://wtfpl.net/)
// @version       0.0.0.7
// @icon          http://s3.amazonaws.com/uso_ss/icon/337070/large.png
// @homepage      http://userscripts.org/scripts/show/337070
// @updateURL     http://userscripts.org/scripts/source/337070.meta.js
// @downloadURL   http://userscripts.org/scripts/source/337070.user.js
//
// @include       http://juick.com/*
// ==/UserScript==
;
window.addEventListener('load', function() {
  var $, likeprob, randomClick;
  $ = unsafeWindow.jQuery;
  likeprob = 0.5;
  randomClick = function(e, idx) {
    if (Math.random() < likeprob) {
      return setTimeout(function() {
        return e.click();
      }, Math.round(20 + (idx + Math.random() * 15) * 1000));
    }
  };
  $('a.vote-up').each(function(idx) {
    return randomClick($(this), idx);
  });
});
