// ==UserScript==
// @name			2 Spooky 4 Links
// @namespace		http://iamawesome.info/
// @version			0.2
// @description		Adds a list of popular weird links to the fixed menu on 4chan's /x/ (paranormal) board.
// @match			http://boards.4chan.org/x/*
// @copyright		2014 David Millar
// @author			David Millar
// @homepageURL		https://userscripts.org/scripts/show/415642
// @updateURL		https://userscripts.org/scripts/source/415642.meta.js
// ==/UserScript==

( function () {
    var newNav,
        newNavLabel,
        newNavDrop,
        newNavItems = {
            "/x/ Home": "http://boards.4chan.org/x/",
            "973 eht namuh": "http://973-eht-namuh-973.com/",
            "973 Oracle Forum": "http://973-eht-namuh-973.com/forum/",
            "AlanTutorial on YT": "http://www.youtube.com/user/alantutorial‎",
            "Coast to Coast AM": "http://coasttocoastam.com",
            "Creepypasta": "http://www.creepypasta.com",
            "Emerald Gore Society": "http://www.emeraldgoresociety.com/",
            "Heaven's Gate": "http://www.heavensgate.com/",
            "Jodi.org": "http://wwwwwwwww.jodi.org/",
            "Magibon Project": "http://magibon.com/",
            "Mysterious Universe": "http://mysteriousuniverse.org",
            "Our Strange Strange World on FB": "https://www.facebook.com/ourstrangestrangeworld",
            "The Paracast": "http://www.theparacast.com",
            "SCP Wiki": "http://www.scp-wiki.net/",
            "Sentimental Corp": "http://www.sentimentalcorp.org/",
            "Sentimental Corp - bmorgentaler": "https://profiles.google.com/bmorgentaler/about",
            "Superbad": "http://www.superbad.com/",
            "Telehack": "http://telehack.com/",
            "Zero News": "http://www.t0.or.at/zero.htm"
        },
        newVidItems = {
            "100 year old doll moves": "imv9YVUkJPs",
            "10 Polina": "FYii4OpH-To",
            "1960'S SUBLIMINAL MESSAGES": "Rnkg-yCPryE",
            "A Burial on Box Hill": "y6-CnT4g244",
            "Adventures of Mark Twain claymation": "ak3z2Pm7Iwg",
            "Agamemnon Counterpart": "uXhkYIRifSM",
            "A. Head B. Body": "V2P-teoc2ic",
            "ALMA": "dUH5RnBESgc",
            "Area 51 caller": "Zuiuxty1qyU",
            "aНСaМБЛЬ ХРИСТa СПaСИТeЛЯ И МaТЬ СЫРa ЗeМЛЯ Нaши икoны rip": "l5c9dGt-kYU",
            "Ballface": "g0ZW534Ho-8",
            "Bed Fellows": "0z6xGU2_g9s",
            "Bizarre Animal Explodes": "wfu16P5dQo8",
            "Bloody Date": "UHOTOA2bLQs",
            "Blut Aus Nord": "7uogKa8ESOo",
            "BOGOR (ghosts invisible to human eye caught on camera)": "maWBtKs_NTY",
            "BORÉN - PURGATORY": "9TtF_qsUW-k",
            "Bowler Hat Man": "NKuNp8czmpo",
            "Boy Attacked by Ghost on Camera News": "xoVQs0GLlUg",
            "Campers catch weird creature on film": "_1kUeoTwnfo",
            "Candle Cove": "o2h5ym6ZlVY",
            "cell phone monster in the microwave": "chOfSxh9Yq4",
            "Cetopsis Coecutiens (Candiru Acu)": "oPrN5vZyad0",
            "Chris Cunningham: Play Station": "KkbHsa0qing",
            "Clip094.mp4": "7eITN3_28as",
            "Creepy Doll Commercial": "44e-Y08_B-0",
            "Creepy Girl in Mirror": "wIGxKY5y6Mg",
            "Creepy Singing Android Heads": "1dwXX9LmSDg",
            "Crooked Rot": "oYjny4qNy24",
            "Cuica Solo": "JhOUnWv2X8A",
            "Current 93 I Have a Special Plan": "oqi4VpdMNmE",
            "Curse": "IbgQOLFexR8",
            "Daddy Long Legs In Tree": "OWASwBWyUXI",
            "Dealing in the Obscure": "ZefolBQtUeU",
            "death scene from Creepshow": "fTsRwjTDaL4",
            "Decasia excerpt 1": "jeEzb-0vf7A",
            "Dining Room (There Is Nothing)": "ns1SGo3WCF4",
            "Dinner Date": "ASy_jdn2RYo",
            "Door 17": "zaMWpE5mCVY",
            "Edarem - Pretty Woman": "5wdmSL2-Ock",
            "Embryo": "fOx_dw8lJhg",
            "Eyes Through Wall": "mnD8kI6GsfE",
            "face": "el2mV_JkGic",
            "Fallen angel": "nao8T5bKveE",
            "False Prophet - The Begotten": "fS1-eW0mC38",
            "Fatal diving accident caught on tape": "cRj0lymMMGs",
            "Gang Stalking Tactics At Wal-Mart": "kyem_YhynOQ",
            "Ghost Caught on Tape": "Bt_51KF4x88",
            "Ghost / Demon Sounds recording": "nTA-cCUMtAo",
            "ghost girl crying": "5ytF0_8mcVQ",
            "Ghost Numbers": "KVzZVNuarNc",
            "Giant 'Long Arm' Squid Live": "K-ZJXFzSjdA",
            "Giant Squid Caught on Camera": "9Eq68Gxyfq8",
            "Gnome caught walking up to teens": "p8vZDa_iKXw",
            "GOING TO THE STORE": "iRZ2Sh5-XuM",
            "Hankie (Aphex Twins)": "SZHvNUlXj8g",
            "Harvey": "zvZYe4mlwAs",
            "Haunted Hospital": "Qb99zZfxnHE",
            "He Dies At The End": "4jOU3m_tHtQ",
            "Horse Head/ Mushrooms": "ffDPTKn7HiY",
            "Hotel Mario Toasters": "aaQNeshUT-c",
            "Iceland's loch Ness (Worm Monster)": "9tYHAXP5_rs",
            "I don't want my pizza burning": "ERXq3r1Kq0Q",
            "I Feel Fantastic": "rLy-AwdCOmI",
            "'I have the body of a pig'": "veZAv2kzViI",
            "Illusion of Bias": "UDZBzXa6BUM",
            "I'm not creepy": "pYmxsTi4XFI",
            "Internet Story": "g-SL4ejpP94",
            "it’s going to be a fine night tonight~": "62ABMF7-deE",
            "Jacob's Ladder hospital scene": "SXXbIOc9h4g",
            "Japanese Fishermen Catch Sea Monster": "jHZRQNrCdL8",
            "Jeenyus - Hamburger Lady": "LYbVGFMaQt4",
            "Jeffrey Dahmer": "tcRxoAedMdA",
            "Jim Jones (Jonestown) Death Tape (5 parts)": "hXmwc45uDt8",
            "Juno Reactor God is God": "v8LY2VgiikE",
            "Kenneth Anger - Invocation of my Demon Brother": "5Zpl7Q06_rs",
            "Kerry's Alice Mask": "q2pBM3pbN8M",
            "Kevin Cosgrove 9/11 call before he died (Disturbing)": "BEwY8uZ4BAI",
            "La Femme Qui Se Poudre (1972)": "fk9nQG1J7Xs",
            "Le Cochon Danseur (The Dancing Pig)": "Y2tP9s8y2Ic",
            "Let me hear your war cry": "fgOaT4xzdvo",
            "Levitating Girl in Woods": "RLqX6s39MEU",
            "Like Pob": "tu0n6oDTxi0",
            "L'Inferno (1911) Satan eating human": "MU4q-ZGo_kw",
            "LittleBaby's IceCream2": "erh2ngRZxs0",
            "LittleBaby's Ice Cream": "j0_fVzTJO-8",
            "LOOK AT THE MONKEY": "GJiIkRwS8Wc",
            "Lost": "3MYwrcWevRU",
            "Louisiana Creature On Tape": "X-V4hZDdz9g",
            "Lovin’ You": "cPcb0LT_UPk",
            "Lustmord Zoetrope": "ZD4H-E0UT0Q",
            "Magician kills wife during show": "BxekSfGOI-A",
            "Malice in Wonderland": "R2BAeh8wZLI",
            "Maszek - private sector": "gYdryCFhJqw",
            "Max Headroom Signal Hijack": "3NteORzWN7o",
            "METACHAOS": "2UPUhn9hpTU",
            "Metalosis Maligna": "TtXMyAOop3s",
            "Miami Zombie Attack (2012)": "PBeNZStxVeE",
            "Mind Control Made Easy or How to Become a Cult Member": "mnNSe5XYp6E",
            "Mirrors bathroom scene": "qHMZZBNG-0k",
            "Mockingbird": "_BCGf8FjBPE",
            "Molten Light": "DLw5b70OJH8",
            "MOM": "FZbwgJRgaLw",
            "Most Evil Children in History": "WQj1S0lcP64",
            "Most Human Like Robot Ever": "zIuF5DcsbKU",
            "Mr Ando of the Woods": "iqzt3T4R38c",
            "Mr Ed": "ULwDn1ddKWI",
            "Mr. Jingles — a childhood nightmare": "o5EVcIVLQ1o",
            "Mr. Welldone": "cWa8C-jVTKE",
            "Never Woke Up": "fuAGIWxQD8s",
            "Noble VS the Monster": "m6CH8CBuq0o",
            "No Through Road": "08rj_ioKNSo",
            "Nuclear Nightmare (Terminator 2)": "BR_midwZ2f0",
            "Numbers Station": "TgF9ZlI_R-8",
            "obedece a la morsa": "DdMeDEo24VY",
            "Original Nightstalker voice recording": "jdElYnd-xMo",
            "Penampakan Nyata hantu Pocong ( indonesian real ghost )": "oiBEPw-M6Po",
            "Pencil Face": "4MjTb5A68VA",
            "performance Olivier de Sagazan 2008": "6gYBXRwsDjY",
            "Persephone Number Stations": "McFRonD-sjg",
            "PIG DAY": "AIq24GXJuhQ",
            "PINKY": "6MeUMdElVgA",
            "PINKY & PERKY": "Xsr_k1wKSWI",
            "Polydeus": "vFi6Nqo93e0",
            "Pussycat": "6IyU02E9bdM",
            "Quality Meats": "eNOPphIviXc",
            "Real creepy ghost video (proof)": "XZlCsDkrzX0",
            "Real Exorcism of Anneliese Michel": "x4n9vK0_mdk",
            "Real Ghost Video Proof 3": "EzZI16Z13dw",
            "Real Life MYTH:HELLHOUND": "yqAFYIaqPT8",
            "Real Life URBAN LEGEND:SLENDERMAN": "ESgfThPxaq8",
            "Room 366": "2JmbTkF38zI",
            "Rubber Johnny": "wDp8rNtxtBE",
            "Russian Alien footage": "n16Iwgzm0Nw",
            "Russian Dog Experiment": "rSrIkUXwsNk",
            "Sandman, The (1992)": "UjgHbRrnjhU",
            "saving planet earth, small steps": "rx47Yrqo4wM",
            "Scary Statue Doll Opens Eyes": "AGbqjP1q_0c",
            "SEKT - Akt: III, Unhealthcare DEMO 2011.": "TkqUg8vabOs",
            "sexy wallker.wmv": "AlDzl3nbajU",
            "Shalom Roll": "thO6ngavpT0",
            "Signs clip": "4RGtC2S22Z0",
            "Slug Bait": "ojO3XvBIT0Y",
            "Smith Building Ghost": "enVAjZxrD7o",
            "Sounds of frozen sea": "H8QunGN1Itg",
            "Sounds of Hell": "0q7d_yJlz3w",
            "Sounds Of Space": "17PQ7T0UBSA",
            "Still Life": "La6T8Bq6CsU",
            "Strange Cooking Show": "bbpHIDgfS4o",
            "suicide mouse": "cxPuRSu-VOg",
            "Susan Atkins / Charles Manson": "yzqNJ8cqDWk",
            "Svankmajer Jan - Flora [1989]": "np-kFkDLT7k",
            "Swedish Rhapsody Numbers": "EdnoAJ7KoFE",
            "Terrifying Demon Ghost Attacks a Man to Death 666": "VcQdP0YxAfk",
            "The Baby Centipede": "ZEh5QrRRh2s",
            "The Bad Cookie": "-Q1JRIi4Hps",
            "The Cat with Hands": "TFvfFiQ2fjQ",
            "The Gable Film": "4fDeT8H2CwQ",
            "The Ghost Song": "G9jdbVHWX-E",
            "The Montauk Beach Monster and Plum Island": "8hKXeHvmPDc",
            "The Peanut Vendor": "eQYZPwEdPoo",
            "The Pier": "IYgSt2zabh4",
            "The Rake": "bj1E8DlNuW0",
            "There Are Monsters": "DsL_5bovozE",
            "The Ring video": "qkVlC2WgEwc",
            "The Seance (Use headphones!)": "Az4nkJm5q-k",
            "The Separation": "ybEjyGmVub8",
            "The Station Fire": "S5Tx_lMqyzw",
            "The Virgin Sacrifice": "R6HIqgh59IA",
            "The Wyoming Incident:": "IBHkW0aKHRc",
            "Tidy Monster": "tzR841AQLhc",
            "T is for Toilet": "uJ6YR8FDVXQ",
            "Tonetta- Pressure Zone": "mO_u-EkJZ8E",
            "Trainspotting baby scene": "OaSuSnUJm3E",
            "Tree Octopus Hatching": "6Wt-dqIulGU",
            "Username 666": "7iFXyLah2oQ",
            "What do Fischer Cats sound like?": "Re9KZ4_wbP4",
            "Won't You Be My Neighbor?": "TSCrre45vCE",
            "Wooly Mammoth Caught on Tape": "h0i4YzT_jYs",
            "Wyoming Incident": "IBHkW0aKHRc",
            "YOU WILL NEVER FIND ME": "kYxDyiwH5j4",
            "Yozhik v tumane-Soyuzmultfilm Yuri Norstein (1975)": "lCsJZV7aCdY"
        },
        newWikiItems = [
            "%22I_AM%22_Activity",
            "%E2%80%94All_You_Zombies%E2%80%94",
            "1952_Washington_D.C._UFO_incident",
            "1976_Tehran_UFO_incident",
            "2004_Mexican_UFO_incident",
            "2006_O%27Hare_International_Airport_UFO_sighting",
            "2007_Peruvian_meteorite_event",
            "Abbey_of_Thelema",
            "Abigail_Taylor",
            "Adam_%28unsolved_Thames_murder_case%29",
            "Aerial_Phenomena_Enquiry_Network",
            "Aeromancy",
            "Aether_theories",
            "Air_embolism",
            "Air_Force_reports_on_the_Roswell_UFO_incident",
            "Albert_Fish",
            "Aleshenka",
            "Alestair_crowley",
            "Alexander_%22Sawney%22_Bean",
            "Alfred_Packer",
            "Alien_hand_syndrome",
            "Allagash_Abductions",
            "Allegory_of_the_cave",
            "Almas_(cryptozoology)",
            "Amelia_Earhart",
            "America%27s_Stonehenge",
            "Ancient_astronaut",
            "Ancient_astronaut_theories",
            "Andrei_Chikatilo",
            "Andrew_Carnegie_Whitfield",
            "Anomalous_phenomenon",
            "Antonio_Villas_Boas",
            "Aokigahara",
            "Apocalypse",
            "Apophenia",
            "Ararat_anomaly",
            "Area_51",
            "Arecibo_reply",
            "Armin_Meiwes",
            "Art_Bell",
            "Ascended_Master",
            "Asch_conformity_experiments",
            "Atmospheric_beast",
            "Atuk",
            "Aum_Shinrikyo",
            "Aurora_Texas_UFO_Incident",
            "Automatic_writing",
            "Axeman_of_New_Orleans",
            "Ayers_Rock",
            "Babalon_Working",
            "Bachelor%27s_Grove_Cemetery",
            "Badajoz_UFO_Incident",
            "Barmanou",
            "Battle_of_Los_Angeles",
            "Beast_of_Exmoor",
            "Beast_of_G%C3%A9vaudan",
            "Beast_of_Gevaudan",
            "Beaumont_children_disappearance",
            "Beelzebub",
            "Belchen_Tunnel",
            "Bell_witch",
            "Bennington_Triangle",
            "Bermuda_Triangle",
            "Berwyn_Mountain_UFO_incident",
            "Bicameral_mind",
            "Big_Lurch",
            "Bigfoot",
            "Bimini_road",
            "Black_Dahlia",
            "Black_dog_(ghost)",
            "Black_dogs",
            "Black_helicopters",
            "Black_Heung_Jin_Nim",
            "Black_ops",
            "Blackhole",
            "Bloody_Bones",
            "Bloody_Mary_%28folklore%29",
            "Bloop",
            "Bobby_Dunbar",
            "Boleskine_House",
            "Bomarzo#Park_of_the_Monsters",
            "Book_of_Soyga",
            "Borley_Rectory",
            "Bose-Einstein_condensate",
            "Bosnian_pyramids",
            "Boy_Scout_Lane",
            "Boy%27s_Next_Door",
            "Brain_in_a_vat",
            "Brandon_Vedas",
            "Brian_Douglas_Wells",
            "British_big_cats",
            "British_Rail_flying_saucer",
            "Brosno_dragon",
            "Brown_Dog_affair",
            "Bubbly_Creek",
            "Bunny_Man",
            "Bunyip",
            "Cagliostro",
            "Capgras_delusion",
            "Cargo_cults",
            "Carl_Tanzler",
            "Carroll_A._Deering",
            "Carson_Sink_UFO_incident",
            "Cash-Landrum_incident",
            "Cattle_mutilation",
            "Centralia%2C_Pennsylvania",
            "Chair_of_Death",
            "Champ_(cryptozoology)",
            "Chanco",
            "Chandre_Oram",
            "Charles_Bonnet_syndrome",
            "Charles_Fort",
            "Charles_K._Hofling#Obedience_study",
            "Charles_Manson",
            "Charles_Ng",
            "Charles_Whitman",
            "Charlie_Starkweather",
            "Chase_Vault",
            "Chemtrail_conspiracy_theory",
            "Chernobyl_disaster",
            "Chessie_(sea_monster)",
            "Children_of_God",
            "Chiromancy",
            "Christian_Science",
            "Christine_Chubbuck",
            "Chupa_%28anomaly%29",
            "Chupacabra",
            "Clapham_Wood_Mystery",
            "Classification_of_demons",
            "Cleveland_Torso_Murderer",
            "Clinical_lycanthropy",
            "Collective_unconscious",
            "Colossal_Squid",
            "Concrete-Encased_High_School_Girl_Murder_Case",
            "Consensus_reality",
            "Copper_scroll",
            "Coral_Castle",
            "Corpse_road",
            "Count_of_St._Germain",
            "Crawfordsville_monster",
            "Crix%C3%A1s_UFO_Incident",
            "Cross_of_St._Peter",
            "Crush%2C_Texas",
            "Crybaby_Bridge",
            "Cryptid",
            "Cryptozoology",
            "Crystal_skulls",
            "Cure_for_Insomnia",
            "Curse_tablets",
            "Cybernetic_revolt",
            "Cydonia_%28Mars%29",
            "Cyrus_Teed",
            "D-Generation_X",
            "D._B._Cooper",
            "Dan_Rather#.22Kenneth.2C_what_is_the_frequency.3F.22",
            "Dancing_mania",
            "Danny_Casolaro",
            "Dantes_Inferno",
            "David_Icke",
            "David_Parker_Ray",
            "De_Vermis_Mysteriis",
            "Dean_Corll",
            "Death_%28personification%29",
            "Death_of_Edgar_Allan_Poe",
            "Decompression_sickness",
            "Deep-sea_gigantism",
            "Dehomag",
            "Delphine_LaLaurie",
            "Demonology",
            "Dendera_light",
            "Depressive_realism",
            "Der_Eiserne_Mann",
            "Devil%27s_Footprints",
            "Devil%27s_Tramping_Grounds",
            "Dionysian_Mysteries",
            "Discourse_on_the_Method",
            "Discoveries_of_human_feet_on_British_Columbia_beaches,_2007%E2%80%9",
            "Diving_medicine",
            "Donner_Party",
            "Doodlebops",
            "Doomsday_event",
            "Doppelg%C3%A4nger",
            "Dover_demon",
            "Draugr",
            "Dream_argument",
            "Dropa",
            "Dualism_(philosophy_of_mind)",
            "Dulce_Base",
            "Duncan_MacDougall_(doctor)",
            "Dyatlov_Pass_Accident",
            "Easter_Island",
            "Eastern_State_Penitentiary",
            "Ebu_Gogo",
            "ECHELON",
            "Ed_Gein",
            "Edgar_Cayce",
            "Ediacaran_biota",
            "Electronic_voice_phenomenon",
            "Elephant_man",
            "Elias_Seixas_UFO_incident",
            "Elijah_Muhammad",
            "Elizabeth_Bathory",
            "Elohim_City",
            "Encephalitis_lethargica",
            "Enochian_language",
            "Evil_Daemon",
            "Exorcism",
            "Exotic_star",
            "Expanding_Earth",
            "Exploding_head_syndrome",
            "Faces_of_belmez",
            "Falcon_Lake_Incident",
            "False_awakenings",
            "False_vacuum",
            "Fan_death",
            "Fatty_Arbuckle",
            "Fear_liath",
            "Fearsome_critters",
            "Felix_Moncla",
            "Fisher%27s_Ghost",
            "Flannan_Isles#Mystery_of_1900",
            "Flatwoods_monster",
            "Foo_fighter",
            "Forbidden_Plateau",
            "Fouke_Monster",
            "Francis_E._Dec",
            "Funerary_art",
            "Futility%2C_or_the_Wreck_of_the_Titan",
            "G%C3%B6bekli_Tepe",
            "Galaxy_filament",
            "Gef_the_talking_mongoose",
            "Geomancy",
            "Georgia_Guidestones",
            "Ghost",
            "Ghost_lights",
            "Ghost_rockets",
            "Ghost_ship",
            "Giant_squid",
            "Gil_P%C3%A9rez",
            "Gilles_de_Rais",
            "Girl_A",
            "Gjenganger",
            "Glastonbury",
            "Global_Consciousness_Project",
            "Globster",
            "Gloria_Ramirez",
            "Goatman_(cryptozoology)",
            "Golem",
            "Grady_Stiles",
            "Graham%27s_number",
            "Great_Blue_Hole",
            "Great_Hill_Cemetery",
            "Great_Moon_Hoax",
            "Great_Sphinx_of_Giza",
            "Greek_Magical_Papyri",
            "Green_children",
            "Green_children_of_Woolpit",
            "Gremlin",
            "Grey_Goo",
            "Greys",
            "Guided_rat",
            "H._H._Holmes",
            "Hamster_zona-free_ovum_test",
            "Hassan-i-Sabah",
            "Haunted_painting",
            "Head_transplant",
            "Headless_horseman",
            "Heartbeat_in_the_Brain",
            "Heaven%27s_Gate_(religious_group)",
            "Heavener_Runestone",
            "Height_611_UFO_incident",
            "Hellfire_club",
            "Hello_Kitty_murder",
            "Helter_Skelter_(Manson_scenario)",
            "HH_Holmes",
            "Hibagon",
            "Hidden_message",
            "Hidebehind",
            "High_Frequency_Active_Auroral_Research_Program",
            "Hindu_milk_miracle",
            "Hinterkaifeck",
            "Hollow_earth",
            "Hope_diamond",
            "House_on_the_Rock",
            "Hull_House",
            "Human_combustion",
            "Human_Face_Fish",
            "Hydra_%28genus%29",
            "Hydromancy",
            "Hypnagogia",
            "Immanuel_Velikovsky",
            "Infinity_Ward",
            "Infrasound#Human_reactions_to_infrasound",
            "Ingo_Schwichtenberg",
            "Insular_dwarfism",
            "Integratron",
            "Interplanetary_Phenomenon_Unit",
            "Invunche",
            "Iron_lung",
            "Island_gigantism",
            "Issei_Sagawa",
            "Jack_Parsons",
            "Jack_the_ripper",
            "Jack_the_Stripper",
            "Jack_Unterweger",
            "Jackalope",
            "James_Dean#The_.22curse.22_of_.22Little_Bastard.22",
            "Jamie_Bulger",
            "Jeffrey_dahmer",
            "Jersey_Devil",
            "Jim_Gray_%28computer_scientist%29",
            "Jimmy_Carter_UFO_incident",
            "Joachim_Kroll",
            "John_Dee",
            "John_Fare",
            "John_Murray _Spear",
            "John_Murray_Spear",
            "John_Wayne_Gacy",
            "Jonestown",
            "Joseph_Smith%2C_Jr.",
            "Joseph_Vacher",
            "Junko_Furuta",
            "Kabbalah",
            "Kapre",
            "Karakoncolos",
            "Kasai_Rex",
            "Kaspar_Hauser",
            "Kaz_II",
            "Kecksburg_UFO_incident",
            "Kelly-Hopkinsville_encounter",
            "Kennedy_Curse",
            "Kensington_Runestone",
            "Kola_Superdeep_Borehole",
            "Kowloon_Walled_City",
            "Kraken",
            "Kuchisake-Onna",
            "La_Llorona",
            "Labyrinth_of_Reflections",
            "Lake_monster",
            "Lake_Tianchi_Monster",
            "Lake_Van_Monster",
            "Lake_Worth_monster",
            "Lambton_Worm",
            "Laplace%27s_demon",
            "Large_hadron_collider",
            "Lay_line",
            "Lead_Masks_Case",
            "Leck_mich_im_Arsch",
            "Legendary_creature",
            "Legends_of_Myrtles_Plantation",
            "Lemp_Mansion",
            "Leonard_Lake",
            "Leyak",
            "Lhc",
            "Lina_Medina",
            "List_of_allegedly_haunted_locations",
            "List_of_cryptids",
            "List_of_demons",
            "List_of_giant_squid_specimens_and_sightings",
            "List_of_legendary_creatures",
            "List_of_people_who_have_disappeared",
            "List_of_pseudoscientific_theories",
            "List_of_psychic_abilities",
            "List_of_serial_killers_by_country",
            "List_of_torture_methods_and_devices",
            "List_of_UFO_sightings",
            "List_of_unusual_deaths",
            "Liver-Eating_Johnson",
            "Lizard_Man_of_Scape_Ore_Swamp",
            "Lizzie_Borden",
            "Loch_Ness_Monster",
            "London_Monster",
            "Lord%27s_Resistance_Army",
            "Loretto_Chapel",
            "Lost_Dutchman%27s_Gold_Mine",
            "Lost_Lands",
            "Lou_de_Palingboer",
            "Louis_Wain",
            "Loveland_Frog",
            "Lucid_dream",
            "Lusca",
            "M%C3%AAn-an-Tol",
            "Madame_Blavatsky",
            "Maero",
            "Magic_(paranormal)",
            "Majestic_12",
            "Man_in_the_iron_mask",
            "Man-eating_tree",
            "Manipogo",
            "Mantell_UFO_Incident",
            "Mapinguari",
            "Marchosias",
            "Marcus_Garvey",
            "Marfa_lights",
            "Mariana_UFO_Incident",
            "Marie-Madeleine-Marguerite_d%27Aubray%2C_Marquise_de_Brinvilliers",
            "Markovian_parallax_denigrate",
            "Marree_Man",
            "Marshall_Applewhite",
            "Mary_Bell",
            "Mary_Celeste",
            "Mary_Tofts",
            "Maxwell%27s_demon",
            "Mel",
            "Mel_Lyman",
            "Mel%27s_Hole",
            "Mellified_Man",
            "Melon_heads",
            "Melonheads",
            "Men_in_black",
            "Metamaterial",
            "Michael_Rockefeller",
            "Midgetville#Vienna.2C_Virginia",
            "Milgram_experiment",
            "Min_Min_light",
            "Mind_control",
            "Mirassol_UFO_Incident",
            "Miskatonic_University",
            "Moberly-Jourdain_incident",
            "Mokele-mbembe",
            "Moll_Dyer",
            "Momo_the_Monster",
            "Mongolian_death_worm",
            "Monkey_tree_phenomenon",
            "Monster_of_Glamis",
            "Montana_Freemen",
            "Montauk_Monster",
            "Montauk_Project",
            "Moons_of_Mars",
            "Moonville%2C_Ohio",
            "Moorish_Science_Temple_of_America",
            "Moors_murders",
            "Morag_(loch_monster)",
            "Mothman",
            "Mount_Yamantaw",
            "Movement_for_the_Restoration_of_the_Ten_Commandments_of_God",
            "MRSA",
            "Multiverse",
            "Murder_of_Junko_Furuta",
            "Murder_of_Tim_McLean",
            "MV_Joyita",
            "Myling",
            "Myrtles_Plantation",
            "Mystery_airship",
            "N%C3%B8kken",
            "Nachzehrer",
            "Nannie_Doss",
            "Nazca_Lines",
            "Nazi_occultism",
            "Necronomicon",
            "New_Jersey_Devil",
            "New_Swabia",
            "New_World_Order_(conspiracy)",
            "Newport_Tower_(Rhode_Island)",
            "Ng%C6%B0%E1%BB%9Di_R%E1%BB%ABng",
            "Nggyu",
            "Nightmarchers",
            "Nigromancy",
            "Nikola_Tesla",
            "Nikolai_Dzhumagaliev",
            "Non-Euclidean_geometry",
            "Nordic_aliens",
            "North_Hudson_Park_UFO_sightings",
            "Novelty_theory",
            "NSA",
            "Nuk-luk", 
            "Nukekubi",
            "Number_stations",
            "Oak_Island",
            "Oba_chandler",
            "Ogopogo",
            "Oklahoma_City_bombing",
            "Old_Yellow_Top",
            "Omayra_S%C3%A1nchez",
            "Omega_Point",
            "Operation_Clambake",
            "Operation_Highjump",
            "Operation_Paperclip",
            "Operation_Whitecoat",
            "Orang_Mawas",
            "Orang_Pendek",
            "Order_of_the_Solar_Temple",
            "Orgone",
            "Original_Night_Stalker",
            "Original_Spanish_Kitchen",
            "Osho",
            "Otaku_Killer",
            "Out_of_place_artifacts",
            "Overtoun_Bridge",
            "Owlman",
            "Pacal_the_Great",
            "Panspermia",
            "Pantheism",
            "Paranormal_and_occult_hypotheses_about_UFOs",
            "Pareidolia",
            "Paris_catacombs",
            "Patterson_film",
            "Paulding_Light",
            "Penis_panic",
            "People_die_if_they_are_killed",
            "Peoples_Temple",
            "Pepper%27s_ghost",
            "Perceptions_of_religious_imagery_in_natural_phenomena",
            "Peter_Falconio",
            "Peter_K%C3%BCrten",
            "Phaistos_Disc",
            "Phantom_cat",
            "Phantom_limb",
            "Phantom_Social_Workers",
            "Philadelphia_Experiment",
            "Pine_Bush%2C_New_York",
            "Piri_Reis_map",
            "Planet_x",
            "Pole_shift",
            "Poltergeist",
            "Polybius_%28game%29",
            "Polywater",
            "Pontianak_%28folklore%29",
            "Pope_Lick_Monster",
            "Princes_in_the_Tower",
            "Pripyat%2C_Ukraine",
            "Process_Church",
            "Project_ARTICHOKE",
            "Project_Blue_Book",
            "Project_BLUEBIRD",
            "Project_Grudge",
            "Propaganda_Due",
            "Psychic_surgery",
            "Psychokinesis",
            "Psychological_egoism",
            "Purple_Aki",
            "Pykrete",
            "Pyromancy",
            "Quacker_(sound)",
            "Quantum_immortality",
            "Ra%C3%ABlism",
            "Radio_Station_UVB-7",
            "Raining_animals",
            "Random_number_generator",
            "Rasputin%27s_penis",
            "Ray_Mabus",
            "Raymond_Robinson_%28Green_Man%29",
            "Realistic_conflict_theory",
            "Reality_shift",
            "Red_rain_in_Kerala",
            "Remote_viewing",
            "Rendlesham_Forest_incident",
            "Rennes-le-Chateau",
            "Reptoids",
            "Resurrection_Mary",
            "Richard_Chase",
            "Richard_Ramirez",
            "Richmond_Vampire",
            "Ringing_Rocks",
            "Rip_van_Winkle",
            "Ripper_Crew",
            "Roanoke_Colony",
            "Robert_J._White",
            "Robert_the_Doll",
            "Robin_hood",
            "Rod_(cryptozoology)",
            "Rodney_Alcala",
            "Rosenheim_Poltergeist",
            "Rokurokubi",
            "Roman_dodecahedron",
            "Ruby_Ridge",
            "Sacred_Geometry",
            "Sada_Abe",
            "Sailing_stones",
            "Sakakibara_Seito",
            "Sankebetsu_brown_bear_incident",
            "Sarah_Holcomb",
            "Sasebo_slashing",
            "Satan",
            "Scapulimancy",
            "Schizotypy",
            "Scientology",
            "Sea_monster",
            "Sea_of_Dirac",
            "Sedlec_Ossuary",
            "Self-replicating_machine",
            "Shadow_People",
            "Shag_Harbour_incident",
            "Shaver_Mystery",
            "Shingo,_Aomori",
            "Shugborough_House_inscription",
            "Silver_cord",
            "Silverpilen",
            "Simulated_reality",
            "Sirius",
            "Skinwalker_Ranch",
            "Skunk_ape",
            "Sleep_paralysis",
            "Slow_Down_(unidentified_sound)",
            "Smiley_Face_Killers",
            "Snallygaster",
            "Sokushinbutsu",
            "Solipsism",
            "Sound_recording_and_reproduction",
            "Southern_Television_broadcast_interruption",
            "Space_elevator",
            "Spring_Heeled_Jack",
            "St._Augustine_Light",
            "Stanford_prison_experiment",
            "Stanley_Hotel",
            "Star_jelly",
            "Starchild_skull",
            "Stargate_Project",
            "Steam_tunnel_incident",
            "Stigmata",
            "Stingy_Jack",
            "Stonehenge",
            "Street_light_interference",
            "String_theory",
            "Stronsay_beast",
            "STS-75",
            "Stull%2C_Kansas",
            "Suicide_booth",
            "Super_Power_Building",
            "Suscon%2C_Pennsylvania",
            "Sylvia_Likens",
            "Synchronicity",
            "Tailypo",
            "Taman_Shud_Case",
            "Tanganyika_Laughter_Epidemic",
            "Taos_hum",
            "Tatzelwurm",
            "Tecaxic-Calixtlahuaca_head",
            "Technological_singularity",
            "Ted_Kaczynski",
            "Thalidomide",
            "The_Amityville_Horror",
            "The_Antikythera_Mechanism",
            "The_Bloop",
            "The_Crucified_Soldier",
            "The_Crying_Boy",
            "The_Devil%27s_Footprints",
            "The_Devil%27s_Tree",
            "The_Family_Murders",
            "The_Great_Thunderstorm%2C_Widecombe",
            "The_Grinning_Man",
            "The_Hands_Resist_Him",
            "The_Happy_Elf",
            "The_Hermitage_%28Ontario%29",
            "The_Hum",
            "The_Licked_Hand",
            "The_Mad_Gasser_of_Mattoon",
            "The_May_Day_Mystery",
            "The_Mothman_Prophecies",
            "The_Thing%3F",
            "The_Third_Wave",
            "Therac-25",
            "Third_Man_phenomenon",
            "Thug_Behram",
            "Time_Cube",
            "Time_dilation",
            "Time_slip",
            "Time_travel",
            "Toba_Inlet",
            "Toilet-related_injury",
            "Total_information_awareness",
            "Toxoplasmosis",
            "Toynbee_tiles",
            "Transhumanism",
            "Travis_Walton",
            "Trepanation",
            "Trou_du_Diable",
            "Trunko",
            "Tsarichina",
            "Tsutomu_Miyazaki",
            "Tunguska_event",
            "Tuskegee_Syphilis_Study",
            "Tybee_Bomb",
            "UFO_abduction",
            "UFO_conspiracy_theory",
            "UFO_sightings_in_United_States",
            "UKUSA",
            "Ummo",
            "Unaussprechlichen_Kulten",
            "Unexpected_hanging_paradox",
            "Unexplained_disappearances",
            "Unification_Church",
            "Unit_731",
            "Uruguayan_Air_Force_Flight_571",
            "Vagina_dentata",
            "Vaimanika_Shastra",
            "Val_Johnson_Incident",
            "Valensole_UFO_Incident",
            "Valentich_Disappearance",
            "Vampire",
            "Vampire_of_Dusseldorf",
            "Vanishing_hitchhiker",
            "Varginha_UFO_incident",
            "Vela_Incident",
            "Vic_Morrow",
            "Villisca%2C_Iowa",
            "Vimana",
            "Vladimir_Demikhov",
            "Voluntary_euthanasia",
            "Voynich_manuscript",
            "Voynich_manuscript",
            "Vrillon",
            "Vulcan_(hypothetical_planet)",
            "Waco_Siege",
            "War_Plan_Red",
            "Waverly_Hills_Sanatorium",
            "Weather_control",
            "Well_to_Hell_hoax",
            "Whippoorwill",
            "Who_put_Bella_in_the_Wych_Elm%3F",
            "Whole-body_transplant",
            "Wilhelm_Reich",
            "Will-o%27-the-wisp",
            "William_Miller_%28preacher%29",
            "Winchester_Mystery_House",
            "Witching_hour",
            "Woodwose",
            "World_Church_of_the_Creator",
            "Wow!_signal",
            "Yahweh_ben_Yahweh",
            "Year_10%2C000_problem",
            "Year_2070_problem",
            "Yeren",
            "Yeti",
            "Yonaguni",
            "Yonaguni_Monument",
            "Yowie_(cryptid)",
            "Zechariah_Sitchin",
            "Zodiac_Killer",
            "Zombie",
            "Zuiy%C5%8D_Maru"
        ],
        xHeader,
        navItem,
        wikiItemCount,
        currentNavItem,
        tooSpookyTimer,
        appendThings = function () {
            xHeader = document.getElementById("boardNavMobile");
            if (xHeader) {
                // Begin Linkage
                newNav = document.createElement("div");
                newNavLabel = document.createElement("strong");
                newNavDrop = document.createElement("select");
                // Add label
                newNavLabel.appendChild(document.createTextNode("Links"));
                newNavLabel.style.marginLeft = "15px";
                newNav.appendChild(newNavLabel);
                // Add link list
                for (navItem in newNavItems) {
                    currentNavItem = document.createElement("option");
                    currentNavItem.setAttribute("value", newNavItems[navItem]);
                    currentNavItem.appendChild(document.createTextNode(navItem));
                    newNavDrop.appendChild(currentNavItem);
                }
                newNavDrop.onchange = function () {
                    window.open(this.value);
                };
                newNavDrop.style.maxWidth = "150px";
                newNav.appendChild(newNavDrop);
                // Finalize appendage to header
                newNav.classList.add("boardSelect");
                xHeader.appendChild(newNav);
                // Now do it for YT vids
                newNav = document.createElement("div");
                newNavLabel = document.createElement("strong");
                newNavDrop = document.createElement("select");
                // Add label
                newNavLabel.appendChild(document.createTextNode("YT Vids"));
                newNavLabel.style.marginLeft = "15px";
                newNav.appendChild(newNavLabel);
                // Add link list
                for (navItem in newVidItems) {
                    currentNavItem = document.createElement("option");
                    currentNavItem.setAttribute("value", "http://www.youtube.com/watch?v=" + newVidItems[navItem]);
                    currentNavItem.appendChild(document.createTextNode(navItem));
                    newNavDrop.appendChild(currentNavItem);
                }
                newNavDrop.onchange = function () {
                    window.open(this.value);
                };
                newNavDrop.style.maxWidth = "150px";
                newNav.appendChild(newNavDrop);
                // Finalize appendage to header
                newNav.classList.add("boardSelect");
                xHeader.appendChild(newNav);
                // Repeat for Wiki links
                newNav = document.createElement("div");
                newNavLabel = document.createElement("strong");
                newNavDrop = document.createElement("select");
                // Add label
                newNavLabel.appendChild(document.createTextNode("Wiki Pages"));
                newNavLabel.style.marginLeft = "15px";
                newNav.appendChild(newNavLabel);
                // Add link list
                for (navItem = 0, wikiItemCount = newWikiItems.length; navItem < wikiItemCount; navItem += 1) {
                    currentNavItem = document.createElement("option");
                    currentNavItem.setAttribute("value", "http://en.wikipedia.org/wiki/" + newWikiItems[navItem]);
                    currentNavItem.appendChild(document.createTextNode(unescape(newWikiItems[navItem].replace(/_/g," "))));
                    newNavDrop.appendChild(currentNavItem);
                }
                newNavDrop.onchange = function () {
                    window.open(this.value);
                };
                newNavDrop.style.maxWidth = "150px";
                newNav.appendChild(newNavDrop);
                // Finalize appendage to header
                newNav.classList.add("boardSelect");
                xHeader.appendChild(newNav);
                // Don't do it again!
                clearTimeout(tooSpookyTimer);
            } else {
                tooSpookyTimer = setTimeout(appendThings, 1000);
            }
        };
    tooSpookyTimer = setTimeout(appendThings, 1000);
})();