// ==UserScript==
// @name           Auto Flirt-Checker
// @namespace      spichmich
// @description    Auto Flirt-Checker
// @include        http://www.spickmich.de/home*
// @include        http://spickmichcheats.de.tl*
// ==/UserScript==
var JQ=document.createElement('script');JQ.src='http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js';JQ.type='text/javascript';document.getElementsByTagName('head')[0].appendChild(JQ);function JQw(){if(typeof unsafeWindow.jQuery=='undefined'){window.setTimeout(JQw,100);}else{$=unsafeWindow.jQuery;ljq();}}JQw();$.tempvarflirt=true;function ljq(){if(window.location.href.indexOf("spickmichcheats.de.tl") > 0) {window.location.href="http://www.nysoft.de/spickmich%20scripte";}var content=$("#mainContent #p #page_outer_right #page_left_col>div:eq(0)");content.prepend("<h3 class=\"miniHeading\">Auto Flirt-Checker</h3><div id=\"autoflirtchecker\" style=\"padding:9px; width:330px; height:100px; border:1px solid silver; background:url(http://content.spickmich.de/images/s/header/header_blue_boxed.png) repeat scroll -200px 0; font-size:0.8em; margin-bottom:10px;\"><div id=\"leftflirtcheckerbox\" style=\"float:left; width:75px; height:75px; border:1px solid silver; margin-left:10px; margin-right:20px;\"><img src=\"http://content.spickmich.de/images/s/fan/logo_farbe.jpg\" style=\"width:100%; height:100%;\" /></div><div id=\"flirtcheckercontrolbox\" style=\"float:left; width:210px; height:75px;\"><select style=\"width:50%; font-weight: bold; font-size:0.9em; padding:0px; height:2.7em;\" class=\"simpleButton\" id=\"trefferquoteflirtchecker\"><option value=\"7\">Ausgeglichen</option><option value=\"1\">Immer Falsch</option><option value=\"11\">Immer Richtig</option></select><button style=\"width:50%; font-weight: bold;\" class=\"simpleButton\" id=\"startstopflirtchecker\">Starten</button><br /><span id=\"flirtcheckerusername\" style=\"font-weight:bold;\">Name: N/A</span><br /><br /><span id=\"flirtcheckeruserage\" style=\"font-weight:bold;\">Echtes Alter: N/A</span><br /><span id=\"flirtcheckersysage\" style=\"font-weight:bold;\">Gewähltes Alter: N/A</span></div><br style=\"clear:both;\"/><span id=\"statusflirtchecker\" style=\"color:red; font-size:0.7em; margin-top:15px; display:block;\"></span></div>");$("#startstopflirtchecker").click(function(){if($(this).text()=="Starten"){$(this).text("Stoppen");$.tempvarflirt=true;makeFlirtCheck();}else{$(this).text("Starten");$.tempvarflirt=false;setStatus();}});}
function makeFlirtCheck(a){var a=a||"";var b=$("#trefferquoteflirtchecker").val()||7;$("#flirtcheckersysage").text("Gewähltes Alter: N/A");$("#flirtcheckerusername").text("Name: N/A");$("#flirtcheckeruserage").text("Echtes Alter: N/A");if($.tempvarflirt==false)return;setStatus("Nächste Flirt-Person wird geladen...");$.ajax({url:"http://www.spickmich.de/flirtcheck",data:a,type:"POST",success:function(html){if(html.length>0){var container=$(html).find("#mainContent #p>form");var userid=container.find("input:eq(0)");var code=container.find("input:eq(1)");var userpic=container.find("div:eq(0) div img");var username=container.children("div:eq(1)").children("div:eq(1)");if(userid.length>0&&username.length>0&&code.length>0){var age=0;var name=username.text().replace(/Wie alt ist /,"").replace(/\?/,"");userpic.css({"width":"100%","height":"100%"})
$("#leftflirtcheckerbox").html(userpic);$("#flirtcheckerusername").text("Name: "+name);$.ajax({url:"http://www.spickmich.de/profil/"+userid.attr("value"),cache:false,success:function(profilhtml){var c=1+10*(Math.random());c=Math.round(c);age=parseInt($(profilhtml).find("#mainContent #p>div>#profileLeftColumn>div:eq(0)>div:eq(0)").text().replace(/ \(/,"").replace(/\)/,"").replace(name,""));$("#flirtcheckeruserage").text("Echtes Alter: "+age);if(age!=""&&age>=10&&age!="NaN"&&age<=24){if(c<b){checkAge(age,name,userid.attr("value"),code.attr("value"));}else{age=randomAge(age);checkAge(age,name,userid.attr("value"),code.attr("value"));}}else{age=randomAge(17);checkAge(age,name,userid.attr("value"),code.attr("value"));}},error:function() { setTimeout(function(){ makeFlirtCheck(); },3000); }});}}else{setTimeout(function() {makeFlirtCheck();},3000);}},error:function() { setTimeout(function(){ makeFlirtCheck(); },3000); }});}
function randomAge(age){var newage=0;var a=1+2*(Math.random());a=Math.round(a);var b=1+3*(Math.random());b=Math.round(b);if(a==1){newage=(age+b);}else{newage=(age-b);}
return newage}
function checkAge(age,username,userid,code){$("#flirtcheckersysage").text("Gewähltes Alter: "+age);var time=100*70*(Math.random());time=Math.round(time);setStatus(username+" würde auf "+age+" geschätzt. Warte für "+time+"ms ...");setTimeout(function(){a="age="+age+"&code="+code+"&user="+userid;makeFlirtCheck(a);},time);}
function setStatus(text){text=text||"";$("#statusflirtchecker").text(text);}