// ==UserScript==
// @name           vk.com audio playlist manager
// @description    This script allows you to remove and change the order of songs from the playlist generated by vkontakte
// @namespace      http://files-search.com/userscripts/vk.com
// @include        http://vk.com/gsearch.php?section=audio&q=*
// @include        http://vkontakte.ru/gsearch.php?section=audio&q=*
// @version        20100307
// @require        http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js
// @resource       imageclose http://i48.tinypic.com/u7yom.gif
// @resource       imageup http://i50.tinypic.com/2qxas0p.gif
// @resource       imagedown http://i48.tinypic.com/jfggvd.gif
// ==/UserScript==


GM_addStyle('div.breaks{  background:#EEE5B8 none repeat scroll 0 0; height:3px; margin-top:12px;}');
GM_addStyle('.tdUp, .tdDown, .tdX{  cursor:pointer; color:#2B587A; }');
GM_addStyle('span#koumpia:hover {  background: #DAE1E8;  color:#36638E;  text-decoration:none;}');
GM_addStyle('span#koumpia {  background: white;  display: inline;  padding: 3px 6px 3px 6px;}');


$('.audioActions').each(function(){
     maldiv = $(this).children()[0];
	$(maldiv).css('width','26px');
	});

$('.audioRow').each(function(){	
	var niceplace = $(this).children()[0].childNodes[0].childNodes[1].childNodes[0];
	var niceplace2 = $(this).children()[0].childNodes[0].childNodes[3].childNodes[2];
	
	$(niceplace2).before('<td></td><td></td><td></td>');
	$(niceplace).before('<td style="width: 15px; vertical-align: top;"><img src="'+GM_getResourceURL('imageclose')+'" nosorthandle="true" id="koumpia" class="tdX"></td>'); 
	$(niceplace).before('<td style="width: 15px; vertical-align: top;"><img src="'+GM_getResourceURL('imageup')+'" nosorthandle="true" id="koumpia" class="tdUp"></td>');
	$(niceplace).before('<td style="width: 15px; vertical-align: top;"><img src="'+GM_getResourceURL('imagedown')+'" nosorthandle="true" id="koumpia" class="tdDown"></td>');

	var niceplace3 = $(this).children()[0].childNodes[0].childNodes[3].childNodes[7];
	$(niceplace3).remove();
	
	var niceplace4 = $(this).children()[0].childNodes[0].childNodes[3].childNodes[5]; 
	$(niceplace4).attr('colspan',2);
   
       $(this).find('.tdX').click(function(){
           var row = $(this).parents("div:first");
             row.fadeOut(300, function () {
             row.remove();
             });
		   });
		   
       $(this).find('.tdDown').click(function(){
		   var row = $(this).parents("div:first");
		    row.fadeOut(300, function () {
		     row.insertAfter(row.next());
		     row.fadeIn(500);
		      });		      
		   });
		   
       $(this).find('.tdUp').click(function(){
		   var row = $(this).parents("div:first");
		   row.fadeOut(300, function () {
		   row.insertBefore(row.prev());
		   row.fadeIn(500);
		      });
		   }); 
       
       });
