// ==UserScript==
// @name         recaptcha
// @namespace    tHeKiNg
// @description  Alerts you via a popup when the bot check is on screen
// @include      http://api.recaptcha.net/* & http://www.gangsofarabia.com/arabic/*

// ==/UserScript==


recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = ""
	privateKey = ""

// Include the noscript tags in the generated captcha includeNoScript = true }

environments { development { recaptcha { // Set to false to disable the display of captcha enabled = false

// Communicate using HTTPS useSecureAPI = false } } production { recaptcha { // Set to false to disable the display of captcha enabled = true

// Communicate using HTTPS useSecureAPI = true } } }