// ==UserScript==
// @name         all in 1 best smiley For Orkut By HUMZA:D //// ()
// @namespace    HUMZA:D
// @author	 HUMZA:D
// @creator	 Prince
// @description  Click on The Smiley to Insert!Enjoy!
// @include      *CommMsgPost*
// ==/UserScript==

addEventListener('load', function(event) {
function getTextArea(n) {
	return document.getElementsByTagName('textarea')[n];
}


function insertSmiley(){
	var image = this.getElementsByTagName('img')[0].getAttribute("src");
	getTextArea(this.getAttribute("gult")).focus();
	getTextArea(this.getAttribute("gult")).value += "<img src="+image+">";
}

function dip() {
	var smileyarr = new Array();	
	smileyarr[".pray_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J4U4tZchI/AAAAAAAAAZA/mAw0YvXbvGU/s400/pray.png";
	smileyarr[".ashamed0001_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J550QW_6I/AAAAAAAAAZI/USM-IR6VatU/s400/ashamed0001.png";
        smileyarr[".ashamed0005_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J6GH8kW0I/AAAAAAAAAZQ/htPiZYAvf6s/s400/ashamed0005.png";
	smileyarr[".bow_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J6R0yZH2I/AAAAAAAAAZY/u3myX-CySB4/s400/bow.png";
	smileyarr[".character0007_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J6br_Qq1I/AAAAAAAAAZg/T7-rL1OwNlU/s400/character0007.png";
        smileyarr[".character0008_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J61JYSToI/AAAAAAAAAZo/ZjbpzwsTC08/s400/character0008.png";
        smileyarr[".confused0006_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J7Agt26gI/AAAAAAAAAZw/ddHOrVEVKdI/s400/confused0006.png";
        smileyarr[".confused0066_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J7NcgET1I/AAAAAAAAAZ4/iS8EWxG-xr8/s400/confused0066.png";
        smileyarr[".confused0075_"]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4J7h_DYpPI/AAAAAAAAAaA/Q63daVeIvLs/s400/confused0075.png";
        smileyarr[".cool0044_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J7v65XJOI/AAAAAAAAAaI/lz5bqyWZFmw/s400/cool0044.png";
        smileyarr[".cool0027_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J8WQjrapI/AAAAAAAAAaQ/lIVP1mYIGOQ/s400/cool0027.png";
        smileyarr[".cool0043_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J8gZL1uqI/AAAAAAAAAaY/6HoBBCG46OM/s400/cool0043.png";
        smileyarr[".evil_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J8pY802pI/AAAAAAAAAag/ahcPa8cJyu8/s400/evilgrin0007.png";
        smileyarr[".fight_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J-D7ChCZI/AAAAAAAAAao/u9dg8-6pgR0/s400/fighting0025.png";
        smileyarr[".fight1_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J-MABcXtI/AAAAAAAAAaw/dx8wP2Z80gk/s400/fighting0030.png";
        smileyarr[".fight2_"]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4J-V698_PI/AAAAAAAAAa4/uXjoLrCpBA8/s400/fighting0032.png";
        smileyarr[".happy_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J-fuMDr2I/AAAAAAAAAbA/eEiKEuvxk_8/s400/happy0025.png";
        smileyarr[".happy1_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J-oJlGYAI/AAAAAAAAAbI/3v1EbRIomdQ/s400/happy0064.png";
        smileyarr[".indifferent0018_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J-wQLR6MI/AAAAAAAAAbQ/hvuraN1Dvgg/s400/indifferent0018.png";
        smileyarr[".indifferent002_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J-61fTGHI/AAAAAAAAAbY/9VoenEjtIW0/s400/indifferent0024.png";
        smileyarr[".hug_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J_JK3EiDI/AAAAAAAAAbg/30o2VU1I3Vg/s400/innocent0005.png";
        smileyarr[".innocent0006_"]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4J_VrrRbJI/AAAAAAAAAbo/vI1Wc9dbsHo/s400/innocent0006.png";
        smileyarr[".jumping_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J_fpk-7rI/AAAAAAAAAbw/Y1YFUyuNfpk/s400/jumping0001.png";
        smileyarr[".love_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J_uarTt5I/AAAAAAAAAb4/NiHgOERXPVw/s400/love0030.png";
        smileyarr[".^Love_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J_3rJMfDI/AAAAAAAAAcA/sal_jUjVUAM/s400/love0033.png";
        smileyarr[".Kiss_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KACkEYggI/AAAAAAAAAcI/n53cz4mXvmM/s400/love0034.png";
        smileyarr[".lip_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KALDB25_I/AAAAAAAAAcQ/XOwO56vqsL8/s400/love0035.png";
        smileyarr[".kisssmile_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KASn1XiII/AAAAAAAAAcY/YTp9bpRcPwo/s400/love0038.png";
        smileyarr[".flowers_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KAdwH-9GI/AAAAAAAAAcg/K5a9s2ohlRY/s400/love0041.png";
        smileyarr[".mad_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KBzZ23-rI/AAAAAAAAAco/Dfxl5x0njF0/s400/mad0054.png";
	smileyarr[".bye_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KB5UtL6UI/AAAAAAAAAcw/K_CJjGlIPec/s400/msn16.png";
	smileyarr[".party_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KCAyzi_CI/AAAAAAAAAc4/i2KVIFkkaLo/s400/party0012.png";
	smileyarr[".parrty_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KCHtL698I/AAAAAAAAAdA/t_K89m3ukSU/s400/party0029.png";
        smileyarr[".rolleye_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KCQSqABuI/AAAAAAAAAdI/_xaymD_5Owk/s400/rolleye0012.png";
        smileyarr[".rip_"]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4KCYHQLn4I/AAAAAAAAAdQ/Hkn0U3Ju4E4/s400/sick0004.png";
        smileyarr[".sick_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KCi6fnnhI/AAAAAAAAAdY/vaeaQiasckE/s400/sick0025.png";
	smileyarr[".partytym_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KCpsG-E1I/AAAAAAAAAdg/0J4Um8nCtFw/s400/sign0008.png";
	smileyarr[".ban_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KC-dONBNI/AAAAAAAAAdw/QzZjjAFdj9s/s400/sign0024.png";
	smileyarr[".tongue_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KDFiDm5wI/AAAAAAAAAd4/3-r4WNhhsH0/s400/tongue0011.png";
	smileyarr[".winking_"]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KDhxvZ01I/AAAAAAAAAeA/EO24ukfWcNw/s400/winking0071.png";
	smileyarr[".agreement_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KF6JUe72I/AAAAAAAAAeI/49-BZ24LsDQ/s400/agreement3.png";
	smileyarr[".laugh_"]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4KGAtcZJtI/AAAAAAAAAeQ/OPhiegyVe9w/s400/laughing1.png";
	smileyarr[".sad_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KGIZrohKI/AAAAAAAAAeY/d8EW9Q2j-r8/s400/sad6.png";
	smileyarr[".welcum_"]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KGTt9kLkI/AAAAAAAAAeg/0Q5Eyj64MvY/s400/signsandflags36.png";
	smileyarr[".sporty_"]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KGaqTnVZI/AAAAAAAAAeo/Nom-zKcpyaE/s400/sporty18.png";
	smileyarr[".liar"]="http://lh5.google.com/fenil.rulez/SCKg5aghRbI/AAAAAAAAALU/dbfTALWwiT0/44.gif";
	smileyarr[".waiting"]="http://lh6.google.com/fenil.rulez/SCKhSqghRcI/AAAAAAAAALc/8gnITHRPong/45.gif";
	smileyarr[".sigh"]="http://lh6.google.com/fenil.rulez/SCKhSqghRdI/AAAAAAAAALk/EK6qB1q8Uy0/46.gif";
	smileyarr[".phbbt"]="http://lh6.google.com/fenil.rulez/SCKhSqghReI/AAAAAAAAALs/1lfHD5RCXU4/47.gif";
	smileyarr[".cowboy"]="http://lh6.google.com/fenil.rulez/SCKhSqghRfI/AAAAAAAAAL0/gPof1Tpjfuc/48.gif";
	smileyarr[".on call"]="http://lh6.google.com/fenil.rulez/SCKhSqghRgI/AAAAAAAAAL8/1GAtlnCiQWk/100.gif";
	smileyarr[".call me"]="http://lh3.google.com/fenil.rulez/SCKha6ghRhI/AAAAAAAAAME/LPvQj4kHnOo/101.gif";
	smileyarr[".irritated"]="http://lh3.google.com/fenil.rulez/SCKha6ghRiI/AAAAAAAAAMM/bwvltzLcjT8/102.gif";
	smileyarr[".bye"]="http://lh3.google.com/fenil.rulez/SCKha6ghRjI/AAAAAAAAAMU/Alz7wy5Xu04/103.gif";
	smileyarr[".time up"]="http://lh3.google.com/fenil.rulez/SCKha6ghRkI/AAAAAAAAAMc/esXzY4CYEHI/104.gif";
	smileyarr[".day dreaming"]="http://lh4.google.com/fenil.rulez/SCKhbKghRlI/AAAAAAAAAMk/z0lmJ3l6DGc/105.gif";
	smileyarr[".dun wanna see"]="http://lh5.google.com/fenil.rulez/SCKhraghRmI/AAAAAAAAAMs/Fwrq_98xe1Q/109.gif";
	smileyarr[".hurry up"]="http://lh5.google.com/fenil.rulez/SCKhraghRnI/AAAAAAAAAM0/4tlsUt1H15E/110.gif";
	smileyarr[".rock on"]="http://lh5.google.com/fenil.rulez/SCKhraghRoI/AAAAAAAAAM8/jWTex2apZzA/111.gif";
	smileyarr[".thumbs down"]="http://lh5.google.com/fenil.rulez/SCKhraghRpI/AAAAAAAAANE/wMusLZLd9Wo/112.gif";
	smileyarr[".thumbs up"]="http://lh5.google.com/fenil.rulez/SCKhraghRqI/AAAAAAAAANM/X4VuXKdVZP4/113.gif";
	smileyarr[".i dunno"]="http://lh4.google.com/fenil.rulez/SCKh3KghRrI/AAAAAAAAANU/HKXemLzafrM/114.gif";
	smileyarr[".bow"]="http://lh4.google.com/fenil.rulez/SCKh3KghRsI/AAAAAAAAANc/BjLIjfIk_zE/77.gif";
	smileyarr[".chatterbox"]="http://lh5.google.com/fenil.rulez/SCKh3aghRtI/AAAAAAAAANk/r0_gLsT6MDs/76.gif";
	smileyarr[".bring it on"]="http://lh5.google.com/fenil.rulez/SCKh3aghRuI/AAAAAAAAANs/yNwr8jdeMw8/70.gif";
	smileyarr[".whistling"]="http://lh3.google.com/fenil.rulez/SCKiA6ghRvI/AAAAAAAAAN0/O3ukMSdjbj8/65.gif";
	smileyarr[".money eyes"]="http://lh3.google.com/fenil.rulez/SCKiA6ghRwI/AAAAAAAAAN8/UAHgEDYtTWw/64.gif";
	smileyarr[".pray"]="http://lh3.google.com/fenil.rulez/SCKiA6ghRxI/AAAAAAAAAOE/38xlLa3ILqM/63.gif";
	smileyarr[".frustated"]="http://lh4.google.com/fenil.rulez/SCKiBKghRyI/AAAAAAAAAOM/Q1yj6LxCP0I/62.gif";
	smileyarr[".dancing"]="http://lh4.google.com/fenil.rulez/SCKiBKghRzI/AAAAAAAAAOU/SYJMOwMAH_c/69.gif";
	smileyarr[".not listening"]="http://lh5.google.com/fenil.rulez/SCKiNaghR0I/AAAAAAAAAOc/m7RffpUIJpk/107.gif";
	smileyarr[".shame on u"]="http://lh5.google.com/fenil.rulez/SCKiNaghR1I/AAAAAAAAAOk/eVg86YsoBSU/68.gif";
	smileyarr[".oh cum on"]="http://lh6.google.com/fenil.rulez/SCKiNqghR2I/AAAAAAAAAOs/iHZJL67ip7M/78.gif";
	smileyarr[".no idea"]="http://lh6.google.com/fenil.rulez/SCKiNqghR3I/AAAAAAAAAO0/dUXWpcCbpOE/106.gif";
	smileyarr[".feelin beat up"]="http://lh6.google.com/fenil.rulez/SCKiNqghR4I/AAAAAAAAAO8/Wdr6l6Amf_o/66.gif";
	smileyarr[".bug"]="http://lh5.google.com/fenil.rulez/SCKiaaghR5I/AAAAAAAAAPE/YYuluyCX5UY/60.gif";
	smileyarr[".skul"]="http://lh5.google.com/fenil.rulez/SCKiaaghR6I/AAAAAAAAAPM/EXs0tfktP1w/59.gif";
	smileyarr[".idea"]="http://lh5.google.com/fenil.rulez/SCKiaaghR7I/AAAAAAAAAPU/5WeIQHQnrbU/58.gif";
	smileyarr[".goodluck"]="http://lh5.google.com/fenil.rulez/SCKiaaghR8I/AAAAAAAAAPc/yUzmMqalQCQ/54.gif";
	smileyarr[".rose"]="http://lh6.google.com/fenil.rulez/SCKiaqghR9I/AAAAAAAAAPk/YWmvdaDqu_k/53.gif";
	smileyarr[".chic"]="http://lh6.google.com/fenil.rulez/SCKijqghR-I/AAAAAAAAAPs/tCSQaPDPR8U/52.gif";
	smileyarr[".monkey"]="http://lh6.google.com/fenil.rulez/SCKijqghR_I/AAAAAAAAAP0/e_0FWxWoC1A/51.gif";
	smileyarr[".cow"]="http://lh3.google.com/fenil.rulez/SCKij6ghSAI/AAAAAAAAAP8/w6YHjrbX7bc/50.gif";
	smileyarr[".pig"]="http://lh3.google.com/fenil.rulez/SCKij6ghSBI/AAAAAAAAAQE/XsU2AA0wf_o/49.gif";
	smileyarr[".dog"]="http://lh3.google.com/fenil.rulez/SCKij6ghSCI/AAAAAAAAAQM/_JxH2hvgM1s/108.gif";
	smileyarr[".star"]="http://lh5.google.com/fenil.rulez/SCKiuaghSDI/AAAAAAAAAQU/iBH0R9P2HAk/79.gif";
	smileyarr[".OD"]="http://lh5.google.com/fenil.rulez/SCKiuaghSEI/AAAAAAAAAQc/43VMyQoVtQc/72.gif";
	smileyarr[".FENIL"]="http://lh6.google.com/fenil.rulez/SCKiuqghSFI/AAAAAAAAAQk/hKMJpiqV0a8/73.gif";
	smileyarr[".NIYATI"]="http://lh6.google.com/fenil.rulez/SCKiuqghSGI/AAAAAAAAAQs/FSLkAll9vgg/74.gif";
	smileyarr[".pirate"]="http://lh6.google.com/fenil.rulez/SCKizqghSHI/AAAAAAAAAQ0/xuO3al_YRfg/pirate_2.gif";
	smileyarr[".transformer"]="http://lh6.google.com/fenil.rulez/SCKizqghSII/AAAAAAAAAQ8/kby9xg6pFoI/transformer.gif";
	smileyarr[".alien"]="http://lh5.google.com/fenil.rulez/SCKjRaghSJI/AAAAAAAAARE/u68DVv1I9ks/61.gif";
	smileyarr[".bee"]="http://lh6.google.com/fenil.rulez/SCKjRqghSKI/AAAAAAAAARM/cyg71VQRdaQ/115.gif";
	smileyarr[".pumpkin"]="http://lh6.google.com/fenil.rulez/SCKjRqghSLI/AAAAAAAAARU/iyJGgK_dpnA/56.gif";
	smileyarr[".tea"]="http://lh6.google.com/fenil.rulez/SCKjRqghSMI/AAAAAAAAARc/xxhTMrfSAqM/57.gif";
	smileyarr[".FF rulez"]="http://lh4.google.com/fenil.rulez/SCMiK6ghThI/AAAAAAAAAcI/656o_XLJlVQ/infomilies14.gif";
	smileyarr[".yin yan"]="http://lh3.ggpht.com/_zam2DdYJLxc/S0Hl202et4I/AAAAAAAAAB0/2wFxcWeu1zk/75.gif";
	smileyarr[".pray."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J4U4tZchI/AAAAAAAAAZA/mAw0YvXbvGU/s400/pray.png";
	smileyarr[".ashamed0001."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J550QW_6I/AAAAAAAAAZI/USM-IR6VatU/s400/ashamed0001.png";
        smileyarr[".ashamed0005."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J6GH8kW0I/AAAAAAAAAZQ/htPiZYAvf6s/s400/ashamed0005.png";
	smileyarr[".bow."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J6R0yZH2I/AAAAAAAAAZY/u3myX-CySB4/s400/bow.png";
	smileyarr[".character0007."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J6br_Qq1I/AAAAAAAAAZg/T7-rL1OwNlU/s400/character0007.png";
        smileyarr[".character0008."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J61JYSToI/AAAAAAAAAZo/ZjbpzwsTC08/s400/character0008.png";
        smileyarr[".confused0006."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J7Agt26gI/AAAAAAAAAZw/ddHOrVEVKdI/s400/confused0006.png";
        smileyarr[".confused0066."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J7NcgET1I/AAAAAAAAAZ4/iS8EWxG-xr8/s400/confused0066.png";
        smileyarr[".confused0075."]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4J7h_DYpPI/AAAAAAAAAaA/Q63daVeIvLs/s400/confused0075.png";
        smileyarr[".cool0044."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J7v65XJOI/AAAAAAAAAaI/lz5bqyWZFmw/s400/cool0044.png";
        smileyarr[".cool0027."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J8WQjrapI/AAAAAAAAAaQ/lIVP1mYIGOQ/s400/cool0027.png";
        smileyarr[".cool0043."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J8gZL1uqI/AAAAAAAAAaY/6HoBBCG46OM/s400/cool0043.png";
        smileyarr[".evil."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J8pY802pI/AAAAAAAAAag/ahcPa8cJyu8/s400/evilgrin0007.png";
        smileyarr[".fight."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J-D7ChCZI/AAAAAAAAAao/u9dg8-6pgR0/s400/fighting0025.png";
        smileyarr[".fight1."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J-MABcXtI/AAAAAAAAAaw/dx8wP2Z80gk/s400/fighting0030.png";
        smileyarr[".fight2."]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4J-V698_PI/AAAAAAAAAa4/uXjoLrCpBA8/s400/fighting0032.png";
        smileyarr[".happy."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4J-fuMDr2I/AAAAAAAAAbA/eEiKEuvxk_8/s400/happy0025.png";
        smileyarr[".happy1."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J-oJlGYAI/AAAAAAAAAbI/3v1EbRIomdQ/s400/happy0064.png";
        smileyarr[".indifferent0018."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J-wQLR6MI/AAAAAAAAAbQ/hvuraN1Dvgg/s400/indifferent0018.png";
        smileyarr[".indifferent002."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J-61fTGHI/AAAAAAAAAbY/9VoenEjtIW0/s400/indifferent0024.png";
        smileyarr[".hug."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J_JK3EiDI/AAAAAAAAAbg/30o2VU1I3Vg/s400/innocent0005.png";
        smileyarr[".innocent0006."]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4J_VrrRbJI/AAAAAAAAAbo/vI1Wc9dbsHo/s400/innocent0006.png";
        smileyarr[".jumping."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J_fpk-7rI/AAAAAAAAAbw/Y1YFUyuNfpk/s400/jumping0001.png";
        smileyarr[".love."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4J_uarTt5I/AAAAAAAAAb4/NiHgOERXPVw/s400/love0030.png";
        smileyarr[".^Love."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4J_3rJMfDI/AAAAAAAAAcA/sal_jUjVUAM/s400/love0033.png";
        smileyarr[".Kiss."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KACkEYggI/AAAAAAAAAcI/n53cz4mXvmM/s400/love0034.png";
        smileyarr[".lip."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KALDB25_I/AAAAAAAAAcQ/XOwO56vqsL8/s400/love0035.png";
        smileyarr[".kisssmile."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KASn1XiII/AAAAAAAAAcY/YTp9bpRcPwo/s400/love0038.png";
        smileyarr[".flowers."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KAdwH-9GI/AAAAAAAAAcg/K5a9s2ohlRY/s400/love0041.png";
        smileyarr[".mad."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KBzZ23-rI/AAAAAAAAAco/Dfxl5x0njF0/s400/mad0054.png";
	smileyarr[".bye."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KB5UtL6UI/AAAAAAAAAcw/K_CJjGlIPec/s400/msn16.png";
	smileyarr[".party."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KCAyzi_CI/AAAAAAAAAc4/i2KVIFkkaLo/s400/party0012.png";
	smileyarr[".parrty."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KCHtL698I/AAAAAAAAAdA/t_K89m3ukSU/s400/party0029.png";
        smileyarr[".rolleye."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KCQSqABuI/AAAAAAAAAdI/_xaymD_5Owk/s400/rolleye0012.png";
        smileyarr[".rip."]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4KCYHQLn4I/AAAAAAAAAdQ/Hkn0U3Ju4E4/s400/sick0004.png";
        smileyarr[".sick."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KCi6fnnhI/AAAAAAAAAdY/vaeaQiasckE/s400/sick0025.png";
	smileyarr[".partytym."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KCpsG-E1I/AAAAAAAAAdg/0J4Um8nCtFw/s400/sign0008.png";
	smileyarr[".ban."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KC-dONBNI/AAAAAAAAAdw/QzZjjAFdj9s/s400/sign0024.png";
	smileyarr[".tongue."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KDFiDm5wI/AAAAAAAAAd4/3-r4WNhhsH0/s400/tongue0011.png";
	smileyarr[".winking."]="http://lh3.ggpht.com/_HGv2ih-2LGA/S4KDhxvZ01I/AAAAAAAAAeA/EO24ukfWcNw/s400/winking0071.png";
	smileyarr[".agreement."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KF6JUe72I/AAAAAAAAAeI/49-BZ24LsDQ/s400/agreement3.png";
	smileyarr[".laugh."]="http://lh6.ggpht.com/_HGv2ih-2LGA/S4KGAtcZJtI/AAAAAAAAAeQ/OPhiegyVe9w/s400/laughing1.png";
	smileyarr[".sad."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KGIZrohKI/AAAAAAAAAeY/d8EW9Q2j-r8/s400/sad6.png";
	smileyarr[".welcum."]="http://lh5.ggpht.com/_HGv2ih-2LGA/S4KGTt9kLkI/AAAAAAAAAeg/0Q5Eyj64MvY/s400/signsandflags36.png";
	smileyarr[".sporty."]="http://lh4.ggpht.com/_HGv2ih-2LGA/S4KGaqTnVZI/AAAAAAAAAeo/Nom-zKcpyaE/s400/sporty18.png";
	smileyarr[".anger."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44cJKnC_4I/AAAAAAAAA3U/OCUqbzpOlDY/s400/14.png";
	smileyarr[".band1."]="http://lh4.ggpht.com/_Pa4D2ASTVpI/S44cyT0wSuI/AAAAAAAAA40/OdlbWBnnQnE/s400/band1.png";
	smileyarr[".boss."]="http://lh6.ggpht.com/_Pa4D2ASTVpI/S44dAtZtapI/AAAAAAAAA5k/1gTysw4QRsk/s400/big_boss.png";
	smileyarr[".biker."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44dHD1GdAI/AAAAAAAAA58/qv_HwzLSATY/s400/biker.png";
	smileyarr[".alaram."]="http://lh4.ggpht.com/_Pa4D2ASTVpI/S44d1LV914I/AAAAAAAAA70/htunpWyQ7qU/s400/connie_16.png";
	smileyarr[".cards."]="http://lh3.ggpht.com/_Pa4D2ASTVpI/S44do7F1qdI/AAAAAAAAA7E/YmF3WqRnj9c/s400/cards.png";
	smileyarr[".coupledance."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44eJcclnMI/AAAAAAAAA8k/JYOYckWFZg0/s400/dance.png";
	smileyarr[".rawkin."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44fku68cOI/AAAAAAAABAI/wL4jxtxjoqI/s400/headbang.png";
	smileyarr[".frdx."]="http://lh3.ggpht.com/_Pa4D2ASTVpI/S44e52L97sI/AAAAAAAAA-0/rFD6PEpi3nk/s400/friends.png";
	smileyarr[".laie."]="http://lh3.ggpht.com/_Pa4D2ASTVpI/S44fzTPP57I/AAAAAAAABAU/bq9ghnrorqU/s400/Laie_23.png";
	smileyarr[".horseriding."]="http://lh4.ggpht.com/_Pa4D2ASTVpI/S44f2Xhcg5I/AAAAAAAABAg/uNH-kmiPLoo/s400/horseriding.png";
	smileyarr[".icecream."]="http://lh6.ggpht.com/_Pa4D2ASTVpI/S44f6QMGn_I/AAAAAAAABAs/j1CvvHSIMjo/s400/icecream.png";
	smileyarr[".areoplane."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44gW3kbsaI/AAAAAAAABCA/n-aRq7N5udY/s400/Laie_43.png";
	smileyarr[".bogirl."]="http://lh4.ggpht.com/_Pa4D2ASTVpI/S44goWlUF6I/AAAAAAAABCk/Epeh9WDBtww/s400/mmmmm.png";
	smileyarr[".hukka."]="http://lh4.ggpht.com/_Pa4D2ASTVpI/S44h8o2rM5I/AAAAAAAABGU/1JINN5qHRXs/s400/sylar.png";
	smileyarr[".swimming."]="http://lh3.ggpht.com/_Pa4D2ASTVpI/S44h43QtxkI/AAAAAAAABGI/QBJUWVyUBgY/s400/swimming.png";
	smileyarr[".studying."]="http://lh6.ggpht.com/_Pa4D2ASTVpI/S44h1JjHiAI/AAAAAAAABF8/gDH33ZM7hKw/s400/studying.png";
	smileyarr[".sporty."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44hyesR48I/AAAAAAAABFw/TEjOkNrn_I0/s400/sporty0.png";
	smileyarr[".relaxsmoke."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44htA6qwkI/AAAAAAAABFk/vksGZsCkN_k/s400/smoke.png";
	smileyarr[".running."]="http://lh5.ggpht.com/_Pa4D2ASTVpI/S44hhyWzLSI/AAAAAAAABFA/-75uDshUs38/s400/run.png";
	smileyarr[".ty."]="http://lh4.ggpht.com/_Pa4D2ASTVpI/S44iA2gKQmI/AAAAAAAABGg/iM2QowdcXs4/s400/thankyou.png.png";
	smileyarr[".toldu."]="http://lh3.ggpht.com/_Pa4D2ASTVpI/S44iPCuo2dI/AAAAAAAABHQ/ID7HvU1v6U4/s400/toldu.png";
	smileyarr[".stars."]="http://lh5.ggpht.com/_liPiaU72mso/S0uVwlVjx7I/AAAAAAAAA24/-C7YeCHdwSs/Seeing%20stars.gif";
	smileyarr[".respect."]="http://lh3.ggpht.com/_PrM5VcwpZio/S2lHUXwcyXI/AAAAAAAABf4/KZd3NxkaQV0/Laie_69.gif";
	smileyarr[".sadcry."]="http://lh5.ggpht.com/_zam2DdYJLxc/S0RAZn_ie4I/AAAAAAAAADI/e4_Q_ouljhs/cry.gif";
	smileyarr[".victory."]="http://lh4.ggpht.com/_PrM5VcwpZio/SwLZ_TNoN9I/AAAAAAAAAZw/TlFG6g_yNnE/victory.gif";
	smileyarr[".missyou."]="http://lh3.ggpht.com/_PrM5VcwpZio/S1vobYDSrJI/AAAAAAAABSU/Xs13_nB0Ki8/sign0150.gif";
	smileyarr[".flowers4ew."]="http://lh6.ggpht.com/_zam2DdYJLxc/S0RBmsujsSI/AAAAAAAAAEc/A1H1UxZn-ng/flowers%20for%20you.gif";
	smileyarr[".lol."]="http://lh6.ggpht.com/_zam2DdYJLxc/S0RBc0NW_xI/AAAAAAAAAEQ/sGhtI9cKNs0/emoticon%20lol.gif";
	smileyarr[".kissew."]="http://lh5.ggpht.com/_PrM5VcwpZio/SwLY7ldgYqI/AAAAAAAAAX0/gt1nxKomtK8/kiss.gif";
	smileyarr[".tease."]="http://lh4.ggpht.com/_WUkykBFkZ3Y/SZ7SpHExDVI/AAAAAAAAAWk/ozpNYo8OVzI/sm31.gif";
	smileyarr[".love."]="http://lh5.ggpht.com/_PrM5VcwpZio/Sx9UhAWxznI/AAAAAAAAAqI/z8nKLncyRuM/love42.gif";
	smileyarr[".fate."]="http://lh6.ggpht.com/_WUkykBFkZ3Y/SY1zslk-75I/AAAAAAAAANg/9FwQ82VVH4c/wallbash1.gif";
	smileyarr[".toldu."]="http://lh3.ggpht.com/_Pa4D2ASTVpI/S44iPCuo2dI/AAAAAAAABHQ/ID7HvU1v6U4/s400/toldu.png";
	smileyarr[".zipped1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZQJevfDI/AAAAAAAAAiM/h8z3Z0MnQdU/zipped.gif";
	smileyarr[".yep1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZQmJUDTI/AAAAAAAAAiQ/phvlmeVDyE0/yep.gif";
	smileyarr[".woops1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZRI2Ke8I/AAAAAAAAAiU/G76hfga-JNQ/woops.gif";
	smileyarr[".wink1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZRraOJ3I/AAAAAAAAAiY/xIa9LWSKtTs/wink.gif";
	smileyarr[".what1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZSF_67AI/AAAAAAAAAic/eCGYPKTjDvs/what.gif";
	smileyarr[".ugly1_laught"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZSpfJUuI/AAAAAAAAAig/TguCMwDfJIE/ugly_laught.gif";
	smileyarr[".tongue1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZTPvey5I/AAAAAAAAAik/360RzFW2hHc/tongue.gif";
	smileyarr[".thinking1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZTl9OfmI/AAAAAAAAAio/eiWA-XeYFMM/thinking.gif";
	smileyarr[".think1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZUFgUpVI/AAAAAAAAAis/0ZIbhKKeQ0Y/think.gif";
	smileyarr[".smile1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZUlNXnDI/AAAAAAAAAiw/T0qcQgEW9Ug/smile.gif";
	smileyarr[".sleeping1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZU0ZSRhI/AAAAAAAAAi0/O4gdkGqfPl4/sleeping.gif";
	smileyarr[".singing1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZVNiOUaI/AAAAAAAAAi4/7DuGH262jOI/singing.gif";
	smileyarr[".sick_eyed1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZViYUj8I/AAAAAAAAAi8/-02P5UK2IvA/sick_eyed.gif";
	smileyarr[".sick1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZWO93zpI/AAAAAAAAAjA/CLNgVCQn6QM/sick.gif";
	smileyarr[".shy1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZW8GykYI/AAAAAAAAAjE/p9w1luVgETQ/shy.gif";
	smileyarr[".shh1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZXU-6ZPI/AAAAAAAAAjI/Ue5jGB3l4Ms/shh.gif";
	smileyarr[".sad_13"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZX4zMR1I/AAAAAAAAAjM/iJF17C9sfVs/sad_3.gif";
	smileyarr[".sad_12"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZYFTmQFI/AAAAAAAAAjQ/ZMxFhP9SSpg/sad_2.gif";
	smileyarr[".sad_11"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZYnHVkmI/AAAAAAAAAjU/YXef2ua5ckA/sad_1.gif";
	smileyarr[".prof1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZZI7bwVI/AAAAAAAAAjY/DW-v9LapaVg/prof.gif";
	smileyarr[".pray1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZZ86_WJI/AAAAAAAAAjc/OrgwigRSBz0/pray.gif";
	smileyarr[".playboy1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZaZz7C_I/AAAAAAAAAjg/GhURYhAOwlA/playboy.gif";
	smileyarr[".okej1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZa7RJbVI/AAAAAAAAAjk/_GatKcXpgAQ/okej.gif";
	smileyarr[".oh_yeh1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZbXiad0I/AAAAAAAAAjo/13FG3mOBt_A/oh_yeh.gif";
	smileyarr[".no_clue1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZbmAHLTI/AAAAAAAAAjs/lb72JUBn7iE/no_clue.gif";
	smileyarr[".no1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZcN6FIJI/AAAAAAAAAjw/M9GpwcL_k5k/no.gif";
	smileyarr[".nerd_smile1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZc7PuLbI/AAAAAAAAAj0/VxNFAld7nJo/nerd_smile.gif";
	smileyarr[".nerd1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZdXnAWvI/AAAAAAAAAj4/U_E0x_Sio5g/nerd.gif";
	smileyarr[".muscle_boy1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZd9_cq8I/AAAAAAAAAj8/V7-xpzIVU3g/muscle_boy.gif";
	smileyarr[".mad1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZeFOr0hI/AAAAAAAAAkA/Tr6r6iP-0S8/mad.gif";
	smileyarr[".loser1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZe6vsEPI/AAAAAAAAAkE/0oBrSlf7kFY/loser.gif";
	smileyarr[".laught1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZfQyrKCI/AAAAAAAAAkI/K1Jhc0ECvdE/laught.gif";
	smileyarr[".in_love1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZfxdw2eI/AAAAAAAAAkM/BhuL1M2aNOM/in_love.gif";
	smileyarr[".idea1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZgV4NJtI/AAAAAAAAAkQ/fULtFTJkoB8/idea.gif";
	smileyarr[".icon_what1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZgjUGOmI/AAAAAAAAAkU/bU8TaRJJp4Y/icon_what.gif";
	smileyarr[".icon_weather1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZhHnNrgI/AAAAAAAAAkY/q2WIddXWAlc/icon_weather.gif";
	smileyarr[".icon_talk1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZhUEHnmI/AAAAAAAAAkc/K7oMnTNcAWA/icon_talk.gif";
	smileyarr[".icon_sick_computer1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZhpJgRXI/AAAAAAAAAkg/5wKD_MyYrRQ/icon_sick_computer.gif";
	smileyarr[".icon_search1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZiH61NoI/AAAAAAAAAkk/WWg2XV58J18/icon_search.gif";
	smileyarr[".icon_megafone1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZiRak9nI/AAAAAAAAAko/u-72-daHJ1c/icon_megafone.gif";
	smileyarr[".icon_love1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZisSplvI/AAAAAAAAAks/ZxjpMjH1_MY/icon_love.gif";
	smileyarr[".icon_joker1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZjItZ58I/AAAAAAAAAkw/GPruJJ5Kz0k/icon_joker.gif";
	smileyarr[".icon_computer1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZjZxjqII/AAAAAAAAAk0/JIxyNL_Wc5M/icon_computer.gif";
	smileyarr[".i_like_you1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZj56s_PI/AAAAAAAAAk4/nlfCHv4Oa2k/i_like_you.gif";
	smileyarr[".hurray1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZkHKQsoI/AAAAAAAAAk8/n2kRlLNGkQI/hurray.gif";
	smileyarr[".huh1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZk9W5tJI/AAAAAAAAAlA/hhWuXAq6PLc/huh.gif";
	smileyarr[".hide1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZlFBqNBI/AAAAAAAAAlE/74Dfq-ePUE0/hide.gif";
	smileyarr[".handy1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZlwipuvI/AAAAAAAAAlI/nIGptHNKr28/handy.gif";
	smileyarr[".halt1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZmKQEeRI/AAAAAAAAAlM/ABH3JWWGxGs/halt.gif";
	smileyarr[".girl1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZmjIOs6I/AAAAAAAAAlQ/aRsQoQhd9rA/girl.gif";
	smileyarr[".eyes1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZnLn-yaI/AAAAAAAAAlU/johAyyPXMt4/eyes.gif";
	smileyarr[".ew1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZnxbAmeI/AAAAAAAAAlY/fS97riTDHvk/ew.gif";
	smileyarr[".evil_mad1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZofbDMGI/AAAAAAAAAlc/4LQmQYnG87A/evil_mad.gif";
	smileyarr[".evil_laught1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZo4Y9SkI/AAAAAAAAAlg/o7ADQmMj3NA/evil_laught.gif";
	smileyarr[".evil_f_you1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZpLEi2_I/AAAAAAAAAlk/8wnxyXXdD_Q/evil_f_you.gif";
	smileyarr[".evil_ass1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZpZmJo1I/AAAAAAAAAlo/BTvtsPX6Q5s/evil_ass.gif";
	smileyarr[".evil_angry1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZp938JLI/AAAAAAAAAls/LeaZh1xNgGI/evil_angry.gif";
	smileyarr[".elvis1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZqV6HCbI/AAAAAAAAAlw/P7HNdViQXKY/elvis.gif";
	smileyarr[".eating_loads1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZrFX5kfI/AAAAAAAAAl0/JAJCgZIRaCk/eating_loads.gif";
	smileyarr[".death1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZrndGmDI/AAAAAAAAAl4/VO61KME4ID8/death.gif";
	smileyarr[".crying_on_floor1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZsOEBwxI/AAAAAAAAAl8/DOCqSivouik/crying_on_floor.gif";
	smileyarr[".crying_loads1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZsnOq7AI/AAAAAAAAAmA/p4UT26LCO2E/crying_loads.gif";
	smileyarr[".crying_laughter1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZtU-5YRI/AAAAAAAAAmE/_C1315EHmho/crying_laughter.gif";
	smileyarr[".crying1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZtg6xDlI/AAAAAAAAAmI/DxYZj1YBYSk/crying.gif";
	smileyarr[".Copy of zipped1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZuWWQRyI/AAAAAAAAAmM/ffAaCovvTGU/Copy%20of%20zipped.gif";
	smileyarr[".Copy of yep1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZu6mVEKI/AAAAAAAAAmQ/zccM9CnaIwk/Copy%20of%20yep.gif";
	smileyarr[".Copy of anti1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZvOp-PZI/AAAAAAAAAmU/80cUuc6Cp-0/Copy%20of%20anti.gif";
	smileyarr[".Copy of angel1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZvkRlUZI/AAAAAAAAAmY/gpDT9pTRpv8/Copy%20of%20angel.gif";
	smileyarr[".Copy of alien1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZv7nTT8I/AAAAAAAAAmc/_BwEb4q_9Ow/Copy%20of%20alien.gif";
	smileyarr[".cool1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZwb6VJkI/AAAAAAAAAmg/RaX9ai86bmQ/cool.gif";
	smileyarr[".coffee1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZw0U228I/AAAAAAAAAmk/wDZBJF0hoxs/coffee.gif";
	smileyarr[".coctail1"]="http://lh4.ggpht.com/_Nhh98Ix90W8/SccZxX3nRkI/AAAAAAAAAmo/jGBIG7uUQLg/coctail.gif";
	smileyarr[".clown1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZxrKPfnI/AAAAAAAAAms/RPdBOlCF5Ao/clown.gif";
	smileyarr[".chips1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZyPorfdI/AAAAAAAAAmw/FBrLQcUNFu4/chips.gif";
	smileyarr[".army1"]="http://lh3.ggpht.com/_Nhh98Ix90W8/SccZycCy3BI/AAAAAAAAAm0/YzzjTFdUzwE/army.gif";
	smileyarr[".anti1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZy-FjHkI/AAAAAAAAAm4/k_RSiWfEupE/anti.gif";
	smileyarr[".angel1"]="http://lh5.ggpht.com/_Nhh98Ix90W8/SccZzXKMfGI/AAAAAAAAAm8/c9Yh1z_sS9g/angel.gif";
	smileyarr[".alien1"]="http://lh6.ggpht.com/_Nhh98Ix90W8/SccZznjsCdI/AAAAAAAAAnA/pvm7ulbRqRg/alien.gif";


	var tb = document.getElementsByTagName('textarea');
	for(i=0;i<tb.length;i++){
		text=tb[i];
		if (!text) return;
		c=text.parentNode;
		d=document.createElement("div");
		d.className="T";
		d.style.fontSize="11px";
		d.align="left";
		
	        
	    d.style.marginTop="10px";
		c.appendChild(d);
		
		for(title in smileyarr){
			mm=document.createElement("a");
			mm.href="javascript:;";
			mm.setAttribute("gult",i);
			mm.innerHTML="<img src='"+smileyarr[title]+"' title='"+title+"'>";
			mm.addEventListener("click", insertSmiley, true);
			d.appendChild(mm);
		}
	}	
}
dip();
}, false);