// ==UserScript==
// @name           ids_show
// @namespace      http://upwap.ru/*
// @include        http://upwap.ru/*
// @author         Fenex
// @version        0.2
// @icon           http://www.gravatar.com/avatar.php?gravatar_id=d9c74d6be48e0163e9e45b54da0b561c&r=PG&s=48&default=identicon
// ==/UserScript==
var a = document.createElement('div');
a.id='fnx_tool';
a.innerHTML = '<table><tr><td><div onclick="ch1();" style="cursor:pointer;"><input type="checkbox" id="ch_box" onchange="ch();">AutoBack</div></td><td><input type="button" value="Next (+1)" onclick="btn_click(1);"></td><td><input type="button" value="Next (+10)" onclick="btn_click(10);"></td><td><input type="button" value="Next (+20)" onclick="btn_click(20);"></td><td><input type="button" value="Next (+50)" onclick="btn_click(50);"></td><td><input type="button" value="Next (+100)" onclick="btn_click(100);"></td><td><input type="button" value="Next (+500)" onclick="btn_click(500);" title="~  на 3 часа вперед"></td><td><input type="button" value="Next (+1000)" onclick="btn_click(1000);" title="~  на 6 часов вперед"></td><td><input type="button" value="Next (+5000)" onclick="btn_click(5000);" title="~  на 3 дня вперед"></td><td><input type="button" value="Next (+10000)" onclick="btn_click(10000);" title="~  на 1 неделю вперед"></td><td><input type="button" value="Next (+20000)" onclick="btn_click(20000);" title="~  на 2 недели вперед"></td><td><input type="button" value="Next (+40000)" onclick="btn_click(40000);" title="~ на 4 недели вперед"></td></tr><tr><td><input type="button" value="IfNotFound" onclick="location.href=localStorage.myfnx;"></td><td><input type="button" value="Back(-1)" onclick="btn_click(-1);"></td><td><input type="button" value="Back(-10)" onclick="btn_click(-10);"></td><td><input type="button" value="Back (-20)" onclick="btn_click(-20);"></td><td><input type="button" value="Back (-50)" onclick="btn_click(-50);"></td><td><input type="button" value="Back (-100)" onclick="btn_click(-100);"></td><td><input type="button" value="Back (-500)" onclick="btn_click(-500);" title="~ на 3 часа назад"></td><td><input type="button" value="Back (-1000)" onclick="btn_click(-1000);" title="~  на 6 часов назад"></td><td><input type="button" value="Back (-5000)" onclick="btn_click(-5000);" title="~  на 3 дня назад"></td><td><input type="button" value="Back (-10000)" title="~  на 1 неделю назад" onclick="btn_click(-10000);"></td><td><input type="button" value="Back (-20000)" title="~  на 2 недели назад" onclick="btn_click(-20000);"></td><td><input type="button" value="Back (-40000)" title="~ на 4 недели назад" onclick="btn_click(-40000);"></td></tr></table><div id="viewer_tool"></div>';
//document.body.appendChild(a);
var sfb = document.getElementsByTagName('body')[0].getElementsByTagName('div')[0];
sfb.parentNode.insertBefore(a, sfb);

var st = document.createElement('style');
st.innerHTML = 'div#fnx_tool input {cursor:pointer;}';
document.body.appendChild(st);

var s = document.createElement('script');
s.innerHTML = 'if(localStorage.chvar=="1"){document.getElementById("ch_box").checked=true;}if(location.href!="http://upwap.ru/notfound/"){localStorage.myfnx = location.href;}else if(document.getElementById("ch_box").checked==true){location.href=localStorage.myfnx;}var fnx_int = parseInt(location.href.substr(parseInt(location.href.indexOf("ru")+3)));function btn_click(r){location.href = "http://upwap.ru/"+(fnx_int+r);};function imgshow(){a=document.getElementById("fnx_img");b=document.getElementById("img_btn");if(a.style.display=="none"){a.style.display="";b.value="Hide Picture";}else{a.style.display="none";b.value="Show Picture";}};function ch(){if(document.getElementById("ch_box").checked){localStorage.chvar=1}else{localStorage.chvar=0}}function ch1(){document.getElementById("ch_box").checked =(!(document.getElementById("ch_box").checked));ch();}function getView(){var txt;var elems = document.getElementsByTagName("div");for (i = 0; i < elems.length; i++) {if ((elems[i].className == "tpanel")&&((elems[i].innerHTML.indexOf(".png") != -1)||(elems[i].innerHTML.indexOf(".gif") != -1)||(elems[i].innerHTML.indexOf(".jpg") != -1)||(elems[i].innerHTML.indexOf(".jpeg") != -1))){txt = "http://upwap.ru" + elems[i].getElementsByTagName("a")[0].getAttribute("href");break;}}if(txt==undefined){return;}document.getElementById("viewer_tool").innerHTML = "<input type=\'button\' id=\'img_btn\' value=\'Show Picture\' onclick=\'imgshow();\'><br /><img id=\'fnx_img\' style=\'display:none;\' src=" + txt + " />";}getView();';
document.body.appendChild(s);