// ==UserScript==
// @name           Canvas Hacks
// @namespace      http://userscripts.org/users/deadinside
// @include        http://canv.as/*
// ==/UserScript==
var current = ''
function HackMe() {
document.getElementById('sticker_widget').innerHTML = ''
document.getElementById('sticker_widget').innerHTML += '<center>Sticker Hack Test</center><div id="sticker_column_border">'
document.getElementById('sticker_widget').innerHTML += '<div id="sticker_widget">'
document.getElementById('sticker_widget').innerHTML += '<div class="stickers_positive">'
document.getElementById('sticker_widget').innerHTML += '<span class="sticker_container smiley drag" style="background-image:url(/static/img/stickers/smiley.png);" data-remaining="0" data-is_limited="False" data-type_id="1"></span><span class="sticker_container frowny drag" style="background-image:url(/static/img/stickers/frowny.png);" data-remaining="0" data-is_limited="False" data-type_id="2"></span><span class="sticker_container monocle drag" style="background-image:url(/static/img/stickers/monocle.png);" data-remaining="0" data-is_limited="False" data-type_id="3"></span><span class="sticker_container lol drag" style="background-image:url(/static/img/stickers/lol.png);" data-remaining="0" data-is_limited="False" data-type_id="4"></span><span class="sticker_container wow drag" style="background-image:url(/static/img/stickers/wow.png);" data-remaining="0" data-is_limited="False" data-type_id="10"></span><span class="sticker_container question drag" style="background-image:url(http://canv.as/static/img/stickers/question.png);" data-remaining="0" data-is_limited="False" data-type_id="6"></span><span class="sticker_container num1 drag" style="background-image:url(/static/img/stickers/num1.png);" data-remaining="2011" data-is_limited="false" data-type_id="7"><span class="sticker_remaining"><span class="sticker_remaining_count">x<span class="sticker_remaining_number">2011</span></span></span></span><span class="sticker_container cookie drag" style="background-image:url(/static/img/stickers/cookie.png);" data-remaining="0" data-is_limited="False" data-type_id="8"></span><span class="sticker_container heart drag" style="background-image:url(/static/img/stickers/heart.png);" data-remaining="0" data-is_limited="False" data-type_id="9"></span><span class="sticker_container texas drag" style="background-image:url(/static/img/stickers/texas.png);" data-remaining="3" data-is_limited="False" data-type_id="101"></span><span class="sticker_container sxsw drag" style="background-image:url(/static/img/stickers/sxsw.png);" data-remaining="3" data-is_limited="False" data-type_id="102"></span><span class="sticker_container banana drag" style="background-image:url(/static/img/stickers/banana.png);" data-remaining="3" data-is_limited="False" data-type_id="103"></span><span class="sticker_container monocle-hungover drag" style="background-image:url(/static/img/stickers/monocle-hungover.png);" data-remaining="13" data-is_limited="False" data-type_id="107"></span></span><span class="sticker_container cool drag" style="background-image:url(/static/img/stickers/cool.png);" data-remaining="13" data-is_limited="False" data-type_id="303"></span><span class="sticker_container zalgo-black drag" style="background-image:url(/static/img/stickers/zalgo-black.png);" data-remaining="3" data-is_limited="False" data-type_id="108"><span class="sticker_remaining_count">x<span class="sticker_remaining_number">13</span></span></span></span>'
document.getElementById('sticker_widget').innerHTML += '<div class="inventory_toggle" style="">more stickers...</div>'
document.getElementById('sticker_widget').innerHTML += '</div><div class="inventory_wrapper"><div class="stickers_inventory"><div class="inventory_page"></div></div><div class="sticker_footer inventory"><p>Visit the <a href="/shop">shop</a> for more</p></div></div><div class="sticker_footer positive"><p>Drag stickers to upvote.</p></div>'
document.getElementById('sticker_widget').innerHTML += '<div class="stickers_share"><span class="sticker_container facebook drag" style="background-image:url(/static/img/stickers/facebook.png);" data-remaining="0" data-is_limited="False" data-type_id="2001"></span><span class="sticker_container twitter drag" style="background-image:url(/static/img/stickers/twitter.png);" data-remaining="0" data-is_limited="False" data-type_id="2002"></span><span class="sticker_container stumbleupon drag" style="background-image:url(/static/img/stickers/stumbleupon.png);" data-remaining="0" data-is_limited="False" data-type_id="2003"></span><span class="sticker_container tumblr drag" style="background-image:url(/static/img/stickers/tumblr.png);" data-remaining="0" data-is_limited="False" data-type_id="2004"></span></div><div class="sticker_footer share"><p>Drag icons to share.</p></div><div class="sticker_actions"><span class="sticker_container flag drag" style="background-image:url(/static/img/stickers/flag.png);" data-remaining="0" data-is_limited="False" data-type_id="3001"></span><span class="sticker_container downvote drag" style="background-image:url(/static/img/stickers/downvote.png);" data-remaining="0" data-is_limited="False" data-type_id="3002"></span><span class="sticker_container pin drag" style="background-image:url(/static/img/stickers/pin.png);" data-remaining="0" data-is_limited="False" data-type_id="3003"></span></div><div class="sticker_footer actions"><span class="sticker_container poop drag" style="background-image:url(/static/img/stickers/poop.png);" data-remaining="0" data-is_limited="False" data-type_id="502"></span><span class="sticker_container offtopic drag" style="background-image:url(/static/img/stickers/offtopic.png);" data-remaining="0" data-is_limited="False" data-type_id="3005"></span></div><div class="sticker_footer actions"><p>Drag actions to use.</p></div><div class="back_to_top">&uarr; Back to top &uarr;</div> </div></div> </div> '
}
HackMe();
           