// ==UserScript==
// @name            youtube - Danayru Enterpises
// @namespace       Danayru Enterprises
// @description     
// @include         *
// @exclude         
// ==/UserScript==
// Generated by: http://blog.monstuff.com/archives/images/GreaseMonkeyScriptGenerator.html

(function() {
   // freeform code goes here

   // iterate over links and add template
   var orig_page_links = document.links;
   var page_links = new Array(orig_page_links.length);
   for (var i=0; i < page_links.length; i++){
       page_links[i] = orig_page_links[i];
   }
   for (var i=0; i < page_links.length; i++){
       if (page_links[i].href.match(/\.torrent$/i)) {
           var span = document.createElement('span');
           var code_str = " <a href=\"";
           code_str += page_links[i].href;
           code_str += "\"><img src=\"http://s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif\" /></a>";
           span.innerHTML = code_str;
           page_links[i].parentNode.insertBefore(span, page_links[i].nextSibling);
       }
   }
})();
