// ==UserScript==
// @name          Yahoo! Firefox
// @namespace     http://mozilla.wikicities.com/
// @include       http://www.yahoo.com/firefox*
// @description	  Yahoo! Firefox
// ==/UserScript==

(function() {
  var newBody =
'<html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><title>Mozilla Firefox Start Page</title><style>body,td,a,p,.h{font-family:arial,sans-serif;} body {font-size: small;color: #333;margin: 0 20px 2em 20px;line-height: 140%;background: #fff url(http://www.google.com/images/firefox/grgrad.gif) repeat-x;}a:link { color: #039; }a:visited { color: #666; }a:hover { color: #333; }a:active { color: #000; }img,table { border: 0;}#sf{ width: 100%; }#frame {width: 564px;margin: 0 auto;}' +
'</style><script type="text/javascript">function sf(){document.w.p.focus();}</script></head><body onLoad="sf()"><center><form action="http://search.yahoo.com/search" name=w><table id=frame cellpadding=0 cellspacing=0 border=0><tr><td><img src="http://www.google.com/images/firefox/clear.gif" height=20 width=1></td></tr><tr><td><table cellpadding=0 cellspacing=0><tr><td><img alt="Firefox Start" src="http://www.google.com/images/firefox/title.gif" width=440 height=116></td><td style="background: url(http://www.google.com/images/firefox/title_bg.gif) repeat-x;" width=100%></td><td><img alt="Firefox Logo" src="http://www.google.com/images/firefox/fox1.gif" width=105 height=116></td><td><img alt="Firefox Logo" src="http://www.google.com/images/firefox/fox2.gif" width=19 height=85></td></tr></table></td></tr><tr><td><table cellpadding=0 cellspacing=0 width="100%" border=0><tr><td bgcolor="#dddddd"><img src="http://www.google.com/images/firefox/clear.gif" height=1 width=1></td><td width=100%><table cellspacing=0 cellpadding=0 ><tr><td><img src="http://www.google.com/images/firefox/clear.gif" height=1 width=40></td><td width=100%><table cellspacing=0 cellpadding=0><tr><td valign=bottom>' +

'<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEsAAAAgCAMAAABto3VBAAAAFXRFWHRDcmVhdGlvbiBUaW1lAAfVBxwVGRv4QfEUAAAAB3RJTUUH1QccFRwE3T%2Fr1AAAAAlwSFlzAAAOwwAADsMBx2%2BoZAAAAwBQTFRFni8ymjo6oxcgpRokuwsitBIjsRwstxwsuBEkoiUspyYwoi0zriw4pDU7qTM7uic2qztEl0hGmkhGnFRRn1lYp0ZKrkJIrk1RpVRWpllaqFZXrVtetU5Uu0hUslZZu1JbsFxgomxpr2BiqG5sr3Nzrn58smRmvmBmu2dstm5wtHl5uXZ6vX1%2BxAokzAkmxBYswhkuwxwxyhsz1gcl1gkp3AYp3Ass2xM02Ro4yCE3yiY81yE30yE84gQq5Qkt7AMs7Akw5xU35hc66hk%2B8gIu9QEr9QEt%2FQAt8QMw8wYw9AEw8As2%2FgAy%2FQg2%2Fgw68RY78xo%2B%2FhM8yStAyTVI3SRC0TNH0jlQ7B1C9htC%2FRRC%2FhtE4y1J7SZG7jtX%2FCRF%2FiVK%2FStO%2FyVQ%2FzBN%2FjVU%2FDRa%2Fjhd%2FT5lwEdTxE5by0lZxlJf30ZYxF1l31Rp2V1pwWVtyXN70ml20HV%2F%2FEFc6FRp71py%2FEJm%2FUdr%2FUts%2FVJv8lZx%2B1Ny%2FF9x%2FF59%2FWB1%2BGF6%2F2N5%2FGF8%2FmV%2B03qD%2F2WD%2FWuB%2F2uI%2F3SE%2F3eP%2FnuM9n2SpYB9qYJ%2BqoSBr4qHsYiFtouHtYqIsZGOvZCOvJWUuZ2buaGevqOguKmoxYCHyo6VypOX0pCU3pSZzp%2Biw6ilwq%2Bsy6Kiyq6sx7CuxrWzyba1ybi1yby60KWo3qyv1bGy6YaU7I%2Bd55Ce94iZ%2FI2d%2F5%2Bf5J6h%2FI2h8p%2Bu%2FZKj%2FJWp%2F5qr5aSr57W86bO167O66Lm%2F9aKi%2B6St%2F62t%2FaW1%2F623%2Fau5%2F7S0%2FrK9%2F7i4%2F7297bvB9bvA%2FrvE0MC9zMTD0sTD1MnG0svK2cXG2c%2FP39jX3dzc5MnM7MHG7sfJ49fW5Nva7t7f8sTN%2FsLL%2FcnJ%2F8%2FP88rR%2FsXQ%2FMzV%2Bc%2FY99TU%2F9LV%2FdPZ%2Fdrf%2Ft3i4uPj6%2BPk6erq6e3t7Ovr7vLy8eXm8uzs%2FuLk%2FeXp%2F%2Brs%2Fu7y9fDv8%2FT09%2Fj4%2BPTz%2BvT0%2FfDz%2F%2FH0%2F%2Fb3%2Bvf4%2F%2Fb4%2Bfr6%2B%2Fz8%2Fvn6%2F%2Fv8%2Fv7%2BonOyngAAAxBJREFUeNrtlHlUTFEYwEP2SvbsslNjSVOWpmcZ8zK%2BYsgyYymSfR%2BypLI0iMhS9l1ZskSS3dgiLahUWkRFNG2aNxK9uu6dV06O4xzO4Rx%2F9Pvn3u%2Bee3%2F33u997%2Bqgv4dOlavK9S9cIVIn15fYJalgbu6fCT6GK0NDH2RqXQA2bRmkc23euBEAMNqoybOv4Xc53v6wKHOKA2Zp4Q%2BDaZ4yO6BEtlKXcK3Lwge7EJv7eBrA0AR1ycdVAoqmaapvcw2Z7uVEkMcVX50NgvqdEkvTgt2dnVcGkaMoZSCo3bxLt3b2tOQycfUJKM%2FXKxnA%2FE8I5R6zAn69ViYH0jIy8lFqG0uwNNDfhVAhzTuiyve0E1qYmfUbLrtSmicD80ZH36sZdaIrDInHLsOsitwrbQHOsqhAAbyGp7JcyOHWs6jEA3SjVQxCxTQv4LMr8HW2nYx8sn8SnA8CsUF0iXZpuB2YhgDVQVXhKvMCGHQmT07XMY5h0WsbCppFsgh50oJlCgLNO6EEsX4Ew2XaygOo7mouca%2Bl0DoI%2BNvZ7zVRtgJgglRUfWs2DjZYj4GxJNXYpasFeu7ZDJQ3w10C%2BIttYSEXoHsgbBwMvfwr1Vc%2BTpm4xk4V%2BUQSs1gZFah16Ua8wyTQAt8LtHgft%2B1G4J2eDuNTtVHGVKjppxxk8LxyrSoABN5EhVaLzAdawxwNKnKDnk%2FJSDF2vZkCQ1%2FhftEViU21mPTJIFUolaFrpcI6xtmlgb7qyq5N2LWbdJIkNTtHXgKLWHcHO3xxp0d5ckcaRp27MVEocV4%2Bw8GWX9ePQTlL7AUUJeD3buqXhVa4xKG8jJ9c6WscYPB1xMrpRTeaGRJ6FB4iTYucrIMzB%2FTv38CwYwA5BBt%2F2NSkh69%2FDA6mC9u%2FuR%2BWzLkKMtOcAahFSUn5s%2FT09Iw0bo4wUvFCRVCzSE0aPI1JiIqKfq9iK%2FZnGK4ubnbdcevi7Tuca51IJMaIRMOOs2T9lwW1MC1LfvffZNXJYSkPOZfGZ0s5e8s3%2FUD4bRcmJez%2Fe7%2BqXFWuX%2FANtGYDq7a5MnIAAAAASUVORK5CYII%3D"></td><td width=40>&nbsp;</td><td nowrap valign=bottom><script>' +

'function qs(el) {if (window.RegExp && window.encodeURIComponent) {var ue=el.href;var qe=encodeURIComponent(document.f.q.value);if(ue.indexOf("q=")!=-1){el.href=ue.replace(new RegExp("q=[^&$]*"),"q="+qe);}else{el.href=ue+"&q="+qe;}}return 1;}' +

'</script><table border=0 cellspacing=0 cellpadding=4><tr><td nowrap><font size=-1><b>Web</b>&nbsp;&nbsp;&nbsp;&nbsp;<a id=1a class=q href="http://images.search.yahoo.com/" onClick="return qs(this);">Images</a>&nbsp;&nbsp;&nbsp;&nbsp;<a id=2a class=q href="http://groups.yahoo.com/" onClick="return qs(this);">Groups</a>&nbsp;&nbsp;&nbsp;&nbsp;<a id=4a class=q href="http://news.search.yahoo.com/" onClick="return qs(this);">News</a>&nbsp;&nbsp;&nbsp;&nbsp;</font></td></tr></table></td></tr></table><table cellspacing=0 cellpadding=0 width=100%><tr><td nowrap><input type=hidden name=ei value="UTF-8"><input id=yschsp maxLength=256 name=p value="" size=57><br><input type=submit value="Search the Web" name=btnG class=ygbt></td><td valign=top nowrap><font size=-2>&nbsp;&nbsp;<a href=http://search.yahoo.com/web/advanced>Advanced Search</a><br>&nbsp;&nbsp;<a href=http://myweb.search.yahoo.com/myresults/default>My Web</a><br>&nbsp;</font></td><td>&nbsp;</td></tr></table></td></tr></table></td><td bgcolor="#b0b0b0"><img src="http://www.google.com/images/firefox/clear.gif" height=1 width=1></td><td><img src="http://www.google.com/images/firefox/clear.gif" height=1 width=19></td></tr></table></td></tr><tr><td><table cellpadding=0 cellspacing=0><tr><td valign=top><img src="http://www.google.com/images/firefox/footer1.gif" height="34" width="48"></td><td style="background: url(http://www.google.com/images/firefox/footer2.gif) repeat-x;" width=100%>&nbsp;</td><td valign=top><img src="http://www.google.com/images/firefox/footer3.gif" height="34" width="497"></td><td><img src="http://www.google.com/images/firefox/clear.gif" height=1 width=19></td></tr></table></td></tr><tr><td><table cellpadding=0 cellspacing=0 width="100%"><tr><td><br><table cellpadding="4" cellspacing="0" border="0" width="100%"> <tr><td> <img src="http://www.google.com/images/firefox/light.gif" alt height="50" width="40"> </td><td> <font size="-1">Enjoy using Firefox? <a href="http://www.mozilla.org/contribute/">Get involved</a>. Spread the word, make a donation, or volunteer.</font> </td></tr></table> <br> <table cellpadding="4" cellspacing="0" border="0" width="100%"><tr> <td align="center" nowrap><font size="-1"><a href="http://www.mozilla.org/products/firefox/central.html">Firefox Help &amp; Add-ons</a></font></td> <td align="center" nowrap><font size="-1"><a href="http://www.mozilla.org/about/">About Mozilla</a></font></td> <td align="center" nowrap><font size="-1"><a href="http://store.mozilla.org/">CDs &amp; Merchandise</a></font></td> <td align="center" nowrap><font size="-1"><a href="http://www.mozilla.org/contribute/">Get Involved</a></font></td> </tr></table> </td><td><img src="http://www.google.com/images/firefox/clear.gif" height=1 width=19></td></tr></table></td></tr></table></form></center></body></html>';

document.body.innerHTML = newBody;
    
})();


