// ==UserScript==
// @name           YouTube HD Suite (optimize for list page)
// @namespace      http://creazy.net/
// @description    equivalent to YouTube HD Suite By yager, but remove all HTTP requests generated by the original script when list pages are loaded, replaced by fetching HD/MP4 url when you mouse over "RAW" links, and other optimize
// @include        http://*.youtube.com/*
// @include        http://youtube.com/*
// ==/UserScript==

(function() {

    var d = document;
    var w = (typeof(unsafeWindow) != 'undefined') ? unsafeWindow : window;
    var l = location;
    var s = w.swfArgs;

    /**
     * Redirect Higher Quality URL
     */
    function redirect() {
        if ( s['fmt_map'] == '22/2000000/9/0/115' ) {
            l.href = l.href + '&fmt=22';
        } else {
            l.href = l.href + '&fmt=18';
        }
    }
    
    /**
     * create XmlHttpRequest
     */
    function createXHR() {
        if ( w.ActiveXObject ) {
            try {
                return new ActiveXObject("Msxml2.XMLHTTP");
            } catch (e) {
                try {
                    return new ActiveXObject("Microsoft.XMLHTTP");
                } catch (e2) {
                    return null;
                }
            }
        } else if ( w.XMLHttpRequest ) {
            return new XMLHttpRequest();
        } else {
            return null;
        }
    }

    /**
     * check URL
     */
    function checkURL(video_id, cb) {
        var url
            = 'http://'+location.host+'/watch'
            + '?v='+video_id
            + '&fmt=22';
        var XHR = createXHR();
        XHR.open( 'GET', url, true );
        XHR.onreadystatechange = function() { 
            if (XHR.readyState==4) {
                if ( match = XHR.responseText.match(/var swfArgs = ({.*})/) ) {
                    json = eval('('+RegExp.$1+')');
					var isHD = (json['fmt_map'] == '22/2000000/9/0/115');
					var linkhtml = '<a style="padding:1px;background:#' 
									+ ( isHD ? 'f00' : '666' ) + ';color:#fff;" href="/get_video?video_id=' 
									+ json['video_id'] + '&t=' + json['t'] + '&fmt=' + ( isHD ? '22' : '18' ) + '">' 
									+ ( isHD ? 'HD' : 'MP4' ) + '</a>';
					cb(linkhtml);
                }
            }
        }
        XHR.send('');
    }

    /**
     * Add HD or MP4 when mouseover each video title links in YouTube List Page
     */
    function visualize() {
        var titles = d.getElementsByTagName('div');
		var temp = document.createElement("div");
		var style = "padding:1px;background:#f00;color:#fff;";
		var videolink = s ? 'video-mini-title' : 'video-title';
        for ( var i=0, l=titles.length; i<l; i++ ) {
			(function(){
				var t = titles[i];
				if( !t.getAttribute("raw") && t.className.indexOf(videolink) != -1  ) {
					try{
						var match = t.getElementsByTagName("a")[0].href.match(/watch\?v=([a-zA-Z0-9_-]*)/)[1];
						temp.innerHTML = '<strong><a style="' + style + '" href="javascript://">RAW</a></strong>';
						var strong = temp.firstChild;
						t.appendChild(strong);
						t.setAttribute("raw", "1")
						strong.getElementsByTagName("a")[0].addEventListener("mouseover", function(){
							var me = this.parentNode;
							me.innerHTML = '<a href="javascript://" style="' + style + 'background:#ff0;color:#000;">loading...</a>'
							checkURL(match, function(link){
								me.innerHTML = link;
							});
						}, true);
					}catch(e){}
				}
			})();
			
        }
    }
    
    /**
     * Add Customized Embed Link
     */
    function showCopyLink() {
        if( s['fmt_map'].indexOf('22/2000000/9/0/115') >= 0 ) {
            i = 22;
            m = 'High Definition';
        } else {
            i = 18;
            m = 'for iPod';
        }
        url_command
            = 'prompt('
            + '\'Copy & Past the MP4('+m+') URL\','
            + 'document.getElementById(\'watch-url-field\').value+\'&fmt='+i+'\''
            + ');'
            + 'void(0);';
        embed_command
            = 'prompt('
            + '\'Copy & Past the MP4('+m+') tag\','
            + 'document.getElementById(\'embed_code\').value.replace(/(http:\\/\\/[a-zA-Z0_-]*\\.youtube\\.com\\/[-_.a-zA-Z0-9\\/?&=%]+)/g,\'$1&ap=%252526fmt%253D'+i+'\')'
            + ');'
            + 'void(0);';
        // Create Links Block
        d.getElementById('watch-url-div').innerHTML
            += '<div id="URL-YT-video" style="text-align:right;padding-right:30px;">'
            +  '<a href="javascript:'+url_command+'">[ Highest-Quality-URL ]</a>'
            +  '</div>';
        d.getElementById('watch-embed-div').innerHTML
            += '<div id="EMBED-YT-video" style="text-align:right;padding-right:30px;">'
            +  '<a href="javascript:'+embed_command+'">[ Highest-Quality-Embed ]</a>'
            +  '</div>';
    }
    
    /**
     * Add HD or MP4 Download Links
     */
    function showDownloadLinks() {
        var h1s = d.getElementsByTagName('h1');
        if ( h1s.length > 0 && h1s[0].innerHTML ) {
            if ( matches = h1s[0].innerHTML.toLowerCase().match(/([0-9a-z_-]+)/g) ) {
                file_name_base = matches.join('_');
            } else {
                file_name_base = s['video_id'];
            }
        }
        //alert(file_name_base);
        
        var base_url  = '/get_video?video_id='+s['video_id']+'&t='+s['t']+'&fmt=';
        var base_css  = ' style="padding:10px;font:bold 14px/1.5 Arial"';
        var input_css = ' style="width:200px;font-size:10px;"';
        var html
            = '<div id="watche-downlaod-div"><form>'
            + '<div id="watche-downlaod-formats-18"'+base_css+'>'
            + '<input type="text" id="watche-downlaod-filename-18" name="watche-downlaod-filename-18" value="'+file_name_base+'.ipod.mp4"'+input_css+' /><br />'
            + '<a href="'+base_url+'18">[OK] Download MP4(iPod, fmt=18)</a></div>';
        if( s['fmt_map'].indexOf('22/2000000/9/0/115') >= 0 ) {
            html
                += '<div id="watche-downlaod-formats-22"'+base_css+'>'
                +  '<input type="text" id="watche-downlaod-filename-22" name="watche-downlaod-filename-22" value="'+file_name_base+'.hd.mp4"'+input_css+' /><br />'
                +  '<a href="'+base_url+'22">[OK] Download MP4(HD, fmt=22)</a></div>';
        } else {
            html += '<div id="watche-downlaod-formats-22"'+base_css+'>[NG] Download MP4(HD, fmt=22)</div>';
        }
        html += '</form></div>';
        // Create Links Block
        d.getElementById('watch-video-details-inner').innerHTML += html;
    }
    
    /**
     * Controller
     */
    if ( l.host.match(/[a-zA-Z\.]*youtube\.com$/) ) {
        // Watching Page
        if ( l.pathname.match(/\/watch/) ) {
            // always watch in Highest Quality
            if ( !l.search.match(/fmt=[0-9]*/) ) {
                redirect();
            } else {
                showCopyLink();
                showDownloadLinks();
            }
        }
        // Other Page (Top, Browse, seache, ...)
        else {
            // for Auto Pager
            var scrollHeight = d.documentElement.scrollHeight;
            d.addEventListener(
                "scroll",
                function(e){
                    if(d.documentElement.scrollHeight - scrollHeight > 100){
                        scrollHeight = d.documentElement.scrollHeight;
                        visualize();
                    }
                },
                false
            );
        }
        // execute "visualize" all pages
        visualize();
    }

})();