// ==UserScript==
// @name            Language pack  Russian
// @version         1.02
// ==/UserScript==

twpro_lp_custom = {
		info: ['lenivetz', 'mailto:dr.mago@yandex.ru', 10572, '.w1.'],    
		AUTHOR: 'Авторы',
		TRANSLATOR: 'Переводчик',
		TWPRO_DISABLED: 'Cкрипт сломался',
		SORTBYNAME: 'Сортировать по <b>названию</b>',
		SORTBYXP: 'Сортировать по <b>опыту</b>',
		SORTBYWAGES: 'Сортировать по <b>зарплате</b>',
		SORTBYLUCK: 'Сортировать по <b>удаче</b>',
		SORTBYCOMB: 'Сортировать по <b>рейтингу работ</b>',
		SORTBYDANGER: 'Сортировать по <b>опасности</b>',
		SORTBYLABORP: 'Сортировать по <b>трудовым очкам</b>',
		FILTERJOBS: "Спрятать работы, которые мне не доступны",
		FILTERCLOTHING: 'Отображать только лучшие вещи для работы',
		CHOOSEJOB: 'Выберите работу...',
		CALCJOB: 'Идут вычисления...',
		INVENTSTATS: 'Статистика багажа',
		SELLVALUE: 'Цена продажи',
		OBJECTS: 'Объекты',
		PRODUCTS: 'Продукты',
		TOTAL: 'В итоге',
                        QUANTITIES: 'Количество',
		LABORP: 'ТО',
		CONSTRUCTION: ' \u25B7 Строительство',
		HPTOTAL: 'Наибольшее кол-во хп',
		STARTCALC: 'Анализ данных...',
		CONVERT: 'Конвертировать',
		MULTISEL: 'Продажа дублируемых предметов...',
	            SELL: 'Продать выделенное',
		CONFIRMSELL: 'Вы действительно хотите продать %1 предметов?',
		SELLING: 'Продажа...',
		SALEDONE: 'Все выбранные вещи были успешно проданы.',
		NONESELECTED: 'Вы должны выбрать хотя бы 1 вещь!',
		JOBRANKSETTINGS: 'Настройка сортировки работ',
		SEARCHINVENTORY: 'Поиск в багаже',
		NOSEARCHRESULT: 'Поиск%1 не дал результатов.%2Отобразить все вещи%3',
		DISABLEBESTFORJOB: 'Показать скрываемые вещи',
	            SEARCHHELP: 'Поиск в багаже. You can use wildcards (* for zero or more characters, ? for one character)',
		DUELSHOOTINGATT: ' \u25B7 Стрелок - атака',
		DUELSHOOTINGDEF: ' \u25B7 Стрелок - защита',
		DUELVIGOR: ' \u25B7 Дуэлянт - рукопашная',     
		FORTATTACK: ' \u25B7 Фортовик - атака форта',    
		FORTDEFEND: ' \u25B7 Фортовик - защита форта',    
                        FORTMESSAGE: 'Сообщение союзникам',
		FORTMESSAGERCP: 'Количество получателей',
                        HIDEJOBS: 'Настройка работ & наборов вещей',  
		CONFIRM: 'Сохранить изменения',   
		HIDEJOBDESC:  'Выделите те работы, которые вы не хотите видеть в списках подсчёта и нажмите "Сохранить изменения" ',    
		SHOWN: 'Показываемые',    
		HIDDEN: 'Скрытые',     
		SETTINGSSAVED: 'Настройки TW Pro были изменены!',     
		SETTINGSSAVEDSESSION: 'Настройки TW Pro были изменены! (только на этот сеанс)',     
		PERSISTSETTINGS: 'Сохранить изменения для постоянного использования.',  
		CANNOTWEAR: 'Вы не можете одеть этот набор, или он не оказыват никакого влияния на трудовые очки.',     
		SETSETTINGS: 'Отключить подсчёты с комплектами. ',     
		CUSTOMNAME: 'Ввести желаемое название для данной деятельности',     
		CUSTOMCALCULATION: 'Введите рабочий TW Pro Расчёт здесь.', 
		CUSTOMENABLED: 'Установите этот флажок для включения этой работы', 
		NEW: 'Новый',    
		SPEED: ' \u25B7 Скоростное передвижение',   
		REGENERATION: ' \u25B7 Регенерация здоровья',  
		SETSINFO: "Наборы",   
		WITHSETITEMS: 'Бонусы %1 предмета',   
		LABORPOINTS: 'Трудовые очки',   
		USEFULITEM: 'Это число отображает количество предметов которые используются в подсчёте',   
		PERCREGENERATION: 'Регенерация',    
		LUCK: 'удача',   
		PRAYING: 'Молитва',     
		NOITEMSETS: "У вас нету вещей из этого набора",  
		AVERAGEDAMAGE: "Средний урон",    
		PREFERENCES: "Предпочтения",   
		DEFAULTSORTING: " \u25B7 Сортировка по умолчанию",    
		FBHEALTHPRIORITY: "Приоритет здоровья",     
		FBHEALTHPRIORITYZERO: "Отсутствует",    
		FBHEALTHPRIORITYLOW: "Низкий",   
		FBHEALTHPRIORITYMEDIUM: "Средний",    
		FBHEALTHPRIORITYHIGH: "Высокий",  
		FBHEALTHPRIORITYAUTO: "Оптимальный  (авто)",     
		FBBATTLEUNIT: "Ваша тактика боя",    
		FBBATTLEUNITSKIRMISHER: "Стрелок в цепи (уворот) | Передовая линия",    
		FBBATTLEUNITLINEINFANTRYMAN: "Рядовой пехотинец(поливалентный) | Средняя линия", 
		FBBATTLEUNITMARKSMAN: "Стрелок (меткость) | Тыловая линия",    
};